In [1]:
import pandas as pd

Ir = pd.read_csv('/Users/egorilin/Desktop/MSU_AI/IrLumDB.csv')
Ir

,L1,L2,L3,Counterion,Abbreviation_in_the_article,Charge,Max_wavelength(nm),PLQY,tau(s*10^-6),Solvent,DOI,Notes,PLQY_in_train
0,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C([O-])c1ccccn1,NaN,1,0,553,0.2500,4.32,CH2Cl2,10.3390/molecules27010232,NaN,1
1,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,c1ccc(-c2ccccn2)nc1,FP(F)(F)(F)(F)F,2,1,570,0.1700,6.14,CH2Cl2,10.3390/molecules27010232,NaN,1
2,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccnc(-c2cc(C(=O)O)ccn2)c1,FP(F)(F)(F)(F)F,3,1,595,0.1400,0.82,CH3OH,10.3390/molecules27010232,NaN,1
3,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=S(=O)([O-])c1ccc(P(c2ccc(S(=O)(=O)O[Na])cc2)...,NaN,4,0,555,0.0435,41.87,PBS,10.3390/molecules27010232,NaN,1
4,[c-]1ccccc1-c1ccccn1,[c-]1ccccc1-c1ccccn1,CCOP(=O)(OCC)c1ccnc(-c2cc(P(=O)(OCC)OCC)ccn2)c1,FP(F)(F)(F)(F)F,Ir(ppy)2bP,1,667,0.0020,NaN,CH3OH,10.1002/adhm.202100706,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,O=C([O-])c1ccccn1,NaN,(m-CzFSOPy)2IrPic,0,554,0.3810,0.64,CH2Cl2,10.1016/j.dyepig.2018.07.019,NaN,1
1450,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir1-me,0,608,0.4000,2.12,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1
1451,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir2-cf3,0,604,0.4100,2.21,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1
1452,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir3-me,0,628,0.6000,2.06,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1
1453,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir4-cf3,0,602,0.6700,2.09,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1

In [4]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
import traceback

# ============================ КОНФИГУРАЦИЯ ============================
# Убедись, что твой DataFrame называется df и содержит колонки L1, L2, L3
# df = pd.read_csv("your_ligands.csv")   # <-- раскомментируй, если нужно загрузить

# =====================================================================

def find_coordinating_atoms(mol):
    """Возвращает список индексов атомов, которые могут координироваться к Ir"""
    coord_atoms = []
    for atom in mol.GetAtoms():
        symbol = atom.GetSymbol()
        charge = atom.GetFormalCharge()
        idx = atom.GetIdx()

        # Анионный углерод C-
        if symbol == 'C' and charge == -1:
            coord_atoms.append(idx)
        # Азот в ароматическом кольце (пиридин, имидазол и т.д.)
        elif symbol == 'N' and atom.GetIsAromatic():
            coord_atoms.append(idx)
        # Кислород в карбоксилате O-
        elif symbol == 'O' and charge == -1:
            coord_atoms.append(idx)
    return coord_atoms


def create_iridium_complex_from_smiles(l1, l2, l3, row_index=None):
    """Создаёт [Ir(L1)(L2)(L3)] комплекс из трёх SMILES-строк"""
    ligand_smiles = [l1, l2, l3]
    ligand_names = ["L1", "L2", "L3"]

    # Проверяем, что все SMILES — строки, а не NaN
    if any(pd.isna(s) or not isinstance(s, str) for s in ligand_smiles):
        return None, "Один из лигандов пустой или не строка"

    rwmol = Chem.RWMol()
    ir = Chem.Atom(77)  # Иридий
    ir_idx = rwmol.AddAtom(ir)

    all_coord_atoms = []

    for i, smiles in enumerate(ligand_smiles):
        name = ligand_names[i]
        mol = Chem.MolFromSmiles(smiles.strip())
        if mol is None:
            return None, f"Некорректный SMILES в {name}: {smiles}"

        # Смещение индексов
        offset = rwmol.GetNumAtoms()

        # Копируем атомы
        atom_map = {}
        for atom in mol.GetAtoms():
            new_atom = Chem.Atom(atom.GetSymbol())
            new_atom.SetFormalCharge(atom.GetFormalCharge())
            new_atom.SetIsAromatic(atom.GetIsAromatic())
            new_idx = rwmol.AddAtom(new_atom)
            atom_map[atom.GetIdx()] = new_idx

        # Копируем связи
        for bond in mol.GetBonds():
            a1 = atom_map[bond.GetBeginAtomIdx()]
            a2 = atom_map[bond.GetEndAtomIdx()]
            rwmol.AddBond(a1, a2, bond.GetBondType())

        # Находим координационные атомы в текущем лиганде
        coord_local = find_coordinating_atoms(mol)
        if not coord_local:
            return None, f"Не найдены координационные атомы в {name}"

        coord_shifted = [idx + offset for idx in coord_local]
        all_coord_atoms.extend(coord_shifted)

        # Создаём дативные связи Ir←N/C/O
        for c in coord_shifted:
            rwmol.AddBond(ir_idx, c, Chem.BondType.DATIVE)

    # Устанавливаем заряд иридия (чтобы комплекс был нейтральным)
    total_ligand_charge = sum(
        a.GetFormalCharge() for a in rwmol.GetAtoms()
        if a.GetAtomicNum() != 77
    )
    rwmol.GetAtomWithIdx(ir_idx).SetFormalCharge(-total_ligand_charge)

    # Финализируем молекулу
    mol = rwmol.GetMol()
    try:
        Chem.SanitizeMol(mol)
    except Exception as e:
        print(f"   [Строка {row_index}] Санитизация не удалась: {e}")

    try:
        complex_smiles = Chem.MolToSmiles(mol, isomericSmiles=True)
        return complex_smiles, "OK"
    except Exception as e:
        return None, f"Ошибка генерации SMILES: {e}"


# ============================ ОСНОВНОЙ ЦИКЛ ============================

def process_dataframe(df):
    # Создаём новые колонки
    df['Complex_SMILES'] = None
    df['Complex_Status'] = None

    print(f"Обрабатываем {len(df)} строк...")

    for idx in df.index:
        print(f"\nОбрабатываем строку {idx}...")

        try:
            l1 = df.at[idx, 'L1']
            l2 = df.at[idx, 'L2']
            l3 = df.at[idx, 'L3']

            smiles, status = create_iridium_complex_from_smiles(l1, l2, l3, row_index=idx)

            df.at[idx, 'Complex_SMILES'] = smiles
            df.at[idx, 'Complex_Status'] = status

            if status == "OK":
                print(f"   Успех! {smiles[:80]}...")
            else:
                print(f"   Ошибка: {status}")

        except Exception as e:
            print(f"   Критическая ошибка в строке {idx}: {e}")
            traceback.print_exc()
            df.at[idx, 'Complex_Status'] = f"Exception: {str(e)}"

    return df


# ============================ ЗАПУСК ============================

# Если df ещё не в памяти — загрузи его:
# df = pd.read_csv("your_file.csv")

# Запускаем обработку
df = process_dataframe(Ir)

# Сохраняем результат
df.to_csv("iridium_complexes_generated.csv", index=False)
df.to_pickle("iridium_complexes_generated.pkl")  # удобнее для дальнейшей работы

print("\nГОТОВО! Результат сохранён в:")
print("   iridium_complexes_generated.csv")
print("   iridium_complexes_generated.pkl")

# Показываем первые успешные комплексы
successful = df[df['Complex_Status'] == 'OK']
print(f"\nУспешно создано комплексов: {len(successful)} из {len(df)}")
if len(successful) > 0:
    print("\nПримеры SMILES комплексов:")
    print(successful['Complex_SMILES'].head(10).to_list())

Обрабатываем 1454 строк...

Обрабатываем строку 0...
   [Строка 0] Санитизация не удалась: Explicit valence for atom # 20 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]234567(->[c-]8cc(-c9[n]<-2c2c%10ccccc%10c%10ccccc%10c2[n]<-39-c2...

Обрабатываем строку 1...
   [Строка 1] Санитизация не удалась: Explicit valence for atom # 20 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]456789(->[c-]%10cc(-c2[n]<-4c2c4ccccc4c4ccccc4c23)ccc%10-c2c...

Обрабатываем строку 2...
   [Строка 2] Санитизация не удалась: Explicit valence for atom # 20 N, 5, is greater than permitted
   Успех! O=C(O)c1cc[n]2<-[Ir+2]345678(->[c-]9cc(-c%10[n]<-3c3c%11ccccc%11c%11ccccc%11c3[n...

Обрабатываем строку 3...
   [Строка 3] Санитизация не удалась: Explicit valence for atom # 20 N, 5, is greater than permitted
   Успех! O=S(=O)([O][Na])c1ccc(P(c2ccc(S(=O)(=O)[O][Na])cc2)c2ccccc2P(c2ccc(S(=O)(=O)[O][...

Обрабатываем строку 4...
   [Строка 4] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCOP(=O)(OCC)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3ccc...

Обрабатываем строку 5...
   [Строка 5] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCOP(=O)(OCC)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5c6ccccc6cc[n]<-35)(->[c-]3ccccc3...

Обрабатываем строку 6...
   [Строка 6] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCOP(=O)(OCC)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3...

Обрабатываем строку 7...
   [Строка 7] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! CN(C)c1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)ccc3-c3c...

Обрабатываем строку 8...
   [Строка 8] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! Nc1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)ccc3-c3cccc[...

Обрабатываем строку 9...
   [Строка 9] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)ccc3-c3cccc[...

Обрабатываем строку 10...
   [Строка 10] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! COc1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)ccc3-c3cccc...

Обрабатываем строку 11...
   [Строка 11] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! O=Cc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(C=O)ccc1-c1cccc[n]<-31)->[n]...

Обрабатываем строку 12...
   [Строка 12] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! CC[N+](CC)(CC)c1cc[n]2<-[Ir]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)c...

Обрабатываем строку 13...
   [Строка 13] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 8 9 11 18 19
   Успех! CN(C)c1cc[n]2<-[Ir+2]34(->[c-]5cc(C6NC(C(=O)O)CS6)ccc5-c5cccc[n]<-35)(->[c-]3cc(...

Обрабатываем строку 14...
   [Строка 14] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 9 10 12 19 20
   Успех! CN(C)c1cc[n]2<-[Ir+2]34(->[c-]5cc(C6NC(C(=O)O)CCS6)ccc5-c5cccc[n]<-35)(->[c-]3cc...

Обрабатываем строку 15...
   [Строка 15] Санитизация не удалась: Explicit valence for atom # 59 N, 4, is greater than permitted
   Успех! Cc1cc2-c3cccc[n]3<-[Ir+3]34567(->[c-]8c(-c9c%10ccccc%10cc[n]<-39)cc(C(F)(F)F)[n]...

Обрабатываем строку 16...
   [Строка 16] Санитизация не удалась: Explicit valence for atom # 62 N, 4, is greater than permitted
   Успех! FC(F)(F)c1cc2-c3c4ccccc4cc[n]3<-[Ir+3]34567(->[c-]2c(C(F)(F)F)[n]<-31)(->[c-]1c(...

Обрабатываем строку 17...
   [Строка 17] Санитизация не удалась: Explicit valence for atom # 62 N, 4, is greater than permitted
   Успех! FC(F)(F)c1cc2-c3c4ccccc4cc[n]3<-[Ir+3]34567(->[c-]2c(C(F)(F)F)[n]<-31)(->[c-]1c(...

Обрабатываем строку 18...
   [Строка 18] Санитизация не удалась: Explicit valence for atom # 9 N, 5, is greater than permitted
   Успех! CCCCCCCC[n]12<-[Ir+3]3456789%10%11(->[O-]C(=O)c%12ccc(-c%13ccc(S(=O)(=O)c%14ccc(...

Обрабатываем строку 19...
   [Строка 19] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
   Успех! Cc1cc2-c3c[n]4<-[Ir+2]567(->[c-]2cc1C)(->[c-]1cc(C)c(C)cc1-c1c[n]<-5c2cc(C)c(C)c...

Обрабатываем строку 20...
   [Строка 20] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
   Успех! Cc1cc2-c3c[n]4<-[Ir+2]567(->[c-]2cc1C)(->[c-]1cc(C)c(C)cc1-c1c[n]<-5c2cc(F)c(F)c...

Обрабатываем строку 21...
   [Строка 21] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 17
   Успех! Fc1ccc2-c3c[n]4<-[Ir+2]567(->[c-]2c1)(->[c-]1cc(F)ccc1-c1c[n]<-5c2ccccc2[n]<-61)...

Обрабатываем строку 22...
   [Строка 22] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 8 10 11 13 14
   Успех! Cc1cc2c(cc1C)[n]1<-[Ir+2]3456(->[c-]7cc(F)ccc7-c1c[n]<-32)(->[c-]1cc(F)ccc1-c1c[...

Обрабатываем строку 23...
   [Строка 23] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
   Успех! Fc1ccc2-c3c[n]4<-[Ir+2]567(->[c-]2c1)(->[c-]1cc(F)ccc1-c1c[n]<-5c2cc(F)c(F)cc2[n...

Обрабатываем строку 24...
   [Строка 24] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 18
   Успех! Fc1cc2-c3c[n]4<-[Ir+2]567(->[c-]2c(F)c1F)(->[c-]1c(-c2c[n]<-5c5ccccc5[n]<-62)cc(...

Обрабатываем строку 25...
   [Строка 25] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 8 10 12 14 16
   Успех! Cc1cc2c(cc1C)[n]1<-[Ir+2]3456(->[c-]7c(-c1c[n]<-32)cc(F)c(F)c7F)(->[c-]1c(-c2c[n...

Обрабатываем строку 26...
   [Строка 26] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 4 17 18 20
   Успех! Fc1cc2c(cc1F)[n]1<-[Ir+2]3456(->[c-]7c(-c1c[n]<-32)cc(F)c(F)c7F)(->[c-]1c(-c2c[n...

Обрабатываем строку 27...
   [Строка 27] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 17 18 19 20 21 22
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(Cl)c(C(F)(F)F)cc5-c5cc(C)c6ccccc6[n]<-35)(->[c-]3c...

Обрабатываем строку 28...
   [Строка 28] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 17 18 19 20 21 22
   Успех! Cc1cc2-c3cc(C(F)(F)F)c(Cl)c[c-]3<-[Ir+2]34(->[c-]5cc(Cl)c(C(F)(F)F)cc5-c5cc(C)c6...

Обрабатываем строку 29...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 30...
   [Строка 30] Санитизация не удалась: Explicit valence for atom # 17 N, 5, is greater than permitted
   Успех! c1ccc(-c2[n]3<-[Ir+2]456789%10(->[c-]%11ccccc%11-c([n]<-43)[n]<-52-c2ccccc2)(->[...

Обрабатываем строку 31...
   [Строка 31] Санитизация не удалась: Explicit valence for atom # 17 N, 5, is greater than permitted
   Успех! CN(C)c1cc[n]2<-[Ir+2]3456789(->[c-]%10ccccc%10-c%10[n]<-3[n]<-4c(-c3ccccc3)[n]<-...

Обрабатываем строку 32...
   [Строка 32] Санитизация не удалась: Explicit valence for atom # 17 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]3456789%10%11%12(->[c-]%13ccccc%13-c%13[n]<-3[n]<-4c(-c3ccccc3)[n]...

Обрабатываем строку 33...
   [Строка 33] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc(F)cc(F)c3-c3c4ccccc4cc[n]<-13)->[c-]1c...

Обрабатываем строку 34...
   [Строка 34] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3c(F)cc(F)cc3-c3c4ccccc4cc[n]<-13)->[c-]1c...

Обрабатываем строку 35...
   [Строка 35] Санитизация не удалась: Explicit valence for atom # 65 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc(F)c(-c4ccc(C(F)(F)F)cc4)c(F)c3-c3c4ccc...

Обрабатываем строку 36...
   [Строка 36] Санитизация не удалась: Explicit valence for atom # 61 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc(F)c(-c4ccc(C#N)cc4)c(F)c3-c3c4ccccc4cc...

Обрабатываем строку 37...
   [Строка 37] Санитизация не удалась: Explicit valence for atom # 73 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc(F)c(-c4ccc(C(=O)c5ccccc5)cc4)c(F)c3-c3...

Обрабатываем строку 38...
   [Строка 38] Санитизация не удалась: Explicit valence for atom # 65 O, 2, is greater than permitted
   Успех! COC(=O)c1ccc(-c2c(F)c[c-]3<-[Ir+3]4(->[O-]C(=CC(=O)C(C)(C)C)C(C)(C)C)(->[c-]5cc(...

Обрабатываем строку 39...
   [Строка 39] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C#N)ccc3-c3c4ccccc4c(C#N)c[n]<-13)->[c-]1cc...

Обрабатываем строку 40...
   [Строка 40] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C(C)(C)C)ccc3-c3c4ccccc4c(C#N)c[n]<-13)->[c...

Обрабатываем строку 41...
   [Строка 41] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(C)cc(C)cc3-c3c4ccccc4c(C#N)c[n]<-13)->[c-]1c...

Обрабатываем строку 42...
   [Строка 42] Санитизация не удалась: Explicit valence for atom # 17 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]123456(->[c-]7c(-c8cccc[n]<-18)cc1c8ccccc8[n]<-28c1...

Обрабатываем строку 43...
   [Строка 43] Санитизация не удалась: Explicit valence for atom # 17 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]123456(->[c-]7c(-c8cccc[n]<-18)cc1c8ccc[n]<-2c8[n]<...

Обрабатываем строку 44...
   [Строка 44] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]123456(->[c-]7c(-c8cc(C(F)(F)F)cc[n]<-18)cc1c8ccccc...

Обрабатываем строку 45...
   [Строка 45] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]123456(->[c-]7c(-c8cc(C(F)(F)F)cc[n]<-18)cc1c8ccc[n...

Обрабатываем строку 46...
   [Строка 46] Санитизация не удалась: Explicit valence for atom # 43 N, 4, is greater than permitted
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+3]3(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)->[n...

Обрабатываем строку 47...
   [Строка 47] Санитизация не удалась: Explicit valence for atom # 39 N, 4, is greater than permitted
   Успех! C1=CC(=C(c2ccccc2)c2ccc[n-]2<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)->[c-]2ccccc2...

Обрабатываем строку 48...
   [Строка 48] Санитизация не удалась: Explicit valence for atom # 47 N, 4, is greater than permitted
   Успех! C1=CC(=C(c2ccccc2)c2ccc[n-]2<-[Ir+3]23(->[c-]4ccccc4-c4c5ccccc5cc[n]<-24)->[c-]2...

Обрабатываем строку 49...
   [Строка 49] Санитизация не удалась: Explicit valence for atom # 73 N, 4, is greater than permitted
   Успех! C1=CC(=C(c2ccccc2)c2ccc[n-]2<-[Ir+3]23(->[c-]4cc(N(c5ccccc5)c5ccccc5)ccc4-c4c5cc...

Обрабатываем строку 50...
   [Строка 50] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(F)cc(F)c3-c3cccc[n]<-13)->[c-]1cc(F)cc(F)c1...

Обрабатываем строку 51...
   [Строка 51] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-...

Обрабатываем строку 52...
   [Строка 52] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1ccccc1-c1c3c...

Обрабатываем строку 53...
   [Строка 53] Санитизация не удалась: Explicit valence for atom # 65 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(N(c4ccccc4)c4ccccc4)ccc3-c3c4ccccc4cc[n]<-1...

Обрабатываем строку 54...
   [Строка 54] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 18 19 20
   Успех! c1ccc(C(Cc2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(CC(c3ccccc3)c3ccccc3)c...

Обрабатываем строку 55...
   [Строка 55] Санитизация не удалась: Explicit valence for atom # 57 N, 5, is greater than permitted
   Успех! c1ccc(C(Cc2ccc3-c4cccc[n]4<-[Ir+2]456(->[c-]3c2)(->[c-]2cc(CC(c3ccccc3)c3ccccc3)...

Обрабатываем строку 56...
   [Строка 56] Санитизация не удалась: Explicit valence for atom # 17 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5c(-c6cccc[n]<-16)cc1c6ccccc6[n]<-26c2cc...

Обрабатываем строку 57...
   [Строка 57] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5c(-c6cc(C(F)(F)F)cc[n]<-16)cc1c6ccccc6[...

Обрабатываем строку 58...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 59...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 60...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 61...
   [Строка 61] Санитизация не удалась: Explicit valence for atom # 40 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(F)cc(F)c3-c3cccc[n]<-13)->[c-]1c(-c3c4ccccc...

Обрабатываем строку 62...
   [Строка 62] Санитизация не удалась: Explicit valence for atom # 38 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1c(-c3c4ccccc4cc[n]...

Обрабатываем строку 63...
   [Строка 63] Санитизация не удалась: Explicit valence for atom # 48 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]123(->[c-]4ccccc4-c4c(-c5ccccc5)[n]<-1c1ccccc1[n]<-24)->...

Обрабатываем строку 64...
   [Строка 64] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! COc1cc2c3-c4cccc[c-]4<-[Ir+3]456(->[O-]C(C)=CC(C)=O)(->[c-]7ccccc7-c7c8cc(OC)c(O...

Обрабатываем строку 65...
   [Строка 65] Санитизация не удалась: Explicit valence for atom # 55 O, 2, is greater than permitted
   Успех! COc1cc2c3-c4ccc(C(C)(C)C)c[c-]4<-[Ir+3]456(->[O-]C(C)=CC(C)=O)(->[c-]7cc(C(C)(C)...

Обрабатываем строку 66...
   [Строка 66] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! FC(F)(F)c1[n]2<-[Ir+2]345678(->[c-]9ccccc9-c([n]<-32)[n]<-41-c1ccccc1)(->[c-]1cc...

Обрабатываем строку 67...
   [Строка 67] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+2]345678(->[c-]9ccccc9-c9[n]<-3[n]<-4c(C(F)(F)F)[n]<-59-c3ccccc3)...

Обрабатываем строку 68...
   [Строка 68] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! FC(F)(F)c1[n]2<-[Ir+2]3456789(->[c-]%10ccccc%10-c([n]<-32)[n]<-41-c1ccccc1)(->[c...

Обрабатываем строку 69...
   [Строка 69] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 70...
   [Строка 70] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 71...
   [Строка 71] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(C)CC[n]12<-[Ir+2]3456(->[c-]7ccccc7-c1[n]<-3c1cc3ccccc3cc12)(->[c-]1ccccc1-c1...

Обрабатываем строку 72...
   [Строка 72] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7ccccc7-c7[n]<-3c3cc8ccccc8cc3[n]<-47CCC(C)C)(->[c-]...

Обрабатываем строку 73...
   [Строка 73] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(C)CC[n]12<-[Ir+2]3456(->[c-]7ccccc7-c1[n]<-3c1cc3ccccc3cc12)(->[c-]1ccccc1-c1...

Обрабатываем строку 74...
   [Строка 74] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1cc[c-]2<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]4ccc(OC)cc4-c4cc(C(F)(F)F)cc[n]<-...

Обрабатываем строку 75...
   [Строка 75] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1cc[c-]2<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]4c(OC)cccc4-c4cc(C(F)(F)F)cc[n]<-...

Обрабатываем строку 76...
   [Строка 76] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1cccc2-c3cc(C(F)(F)F)cc[n]3<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]12)->[c-]1c(OC...

Обрабатываем строку 77...
   [Строка 77] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1cc[c-]2<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]4ccc(OC)cc4-c4ccc(C(F)(F)F)c[n]<-...

Обрабатываем строку 78...
   [Строка 78] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1cc[c-]2<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]4c(OC)cccc4-c4ccc(C(F)(F)F)c[n]<-...

Обрабатываем строку 79...
   [Строка 79] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1cccc2-c3ccc(C(F)(F)F)c[n]3<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]12)->[c-]1c(OC...

Обрабатываем строку 80...
   [Строка 80] Санитизация не удалась: Explicit valence for atom # 131 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc6ccc7cccc8c7c6c5c5c8[n]<-1c1cc(-c6ccc(N(c...

Обрабатываем строку 81...
   [Строка 81] Санитизация не удалась: Explicit valence for atom # 99 O, 2, is greater than permitted
   Успех! CCCCCCc1ccc(-c2cc3c(cc2-c2ccc(CCCCCC)s2)[n]2<-[Ir+3]456(->[O-]C(C)=CC(C)=O)(->[c...

Обрабатываем строку 82...
   [Строка 82] Санитизация не удалась: Explicit valence for atom # 127 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc6ccc7cccc8c7c6c5c5c8[n]<-1c1cc(-c6ccc(N(c...

Обрабатываем строку 83...
   [Строка 83] Санитизация не удалась: Explicit valence for atom # 167 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(-c6ccc(N(c7ccc(C(C)(C)C)cc7)c7ccc(C(C)(C)...

Обрабатываем строку 84...
   [Строка 84] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=CC(C)=Nc1ccccc1)[O-]<-[Ir+3]12(->[c-]3c(-c4ccc5ccccc5[n]<-14)sc1ccccc13)->[c...

Обрабатываем строку 85...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 86...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 87...
   [Строка 87] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(=CC(C)=Nc1ccccc1)[O-]<-[Ir+3]12(->[c-]3c(-c4c5ccccc5c5ccccc5[n]<-14)sc1ccccc1...

Обрабатываем строку 88...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 89...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 90...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 91...
   [Строка 91] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7c8ccccc8cc[n]<-37)(->[n]3ccc7ccccc7c3-c2c1...

Обрабатываем строку 92...
   [Строка 92] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 11 13 24 25
   Успех! CC1(C)c2ccccc2-c2c[c-]3<-[Ir+2]4567(->[c-]8cc9-c%10ccccc%10C(C)(C)c9cc8-c8c9cccc...

Обрабатываем строку 93...
   [Строка 93] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7cc(F)ccc7-c7[n]<-3c3ccccc3[n]<-47CCC(C)C)(->[c-]3cc...

Обрабатываем строку 94...
   [Строка 94] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7ccsc7-c7[n]<-3c3ccccc3[n]<-47CCC(C)C)(->[c-]3ccsc3-...

Обрабатываем строку 95...
   [Строка 95] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(C)CC[n]12<-[Ir+2]345678(->[c-]9cc(F)ccc9-c1[n]<-3c1ccccc12)(->[c-]1cc(F)ccc1-...

Обрабатываем строку 96...
   [Строка 96] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted

[20:58:59] Explicit valence for atom # 20 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 20 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 20 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 20 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 8 9 11 18 19
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 9 10 12 19 20
[20:58:59] Explicit valence for atom # 59 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 62 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 62 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 17
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 8 10 11 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 18
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 8 10 12 14 16
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 4 17 18 20
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 17 18 19 20 21 22
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 17 18 19 20 21 22
[20:58:59] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 73 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 17 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 17 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 43 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 47 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 73 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 18 19 20
[20:58:59] Explicit valence for atom # 57 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 17 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 40 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 38 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 48 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 131 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 99 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 127 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 167 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 8 9 10 11 13 24 25
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 4 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 4 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 4 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 4 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 4 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 18 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 159 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 6 7 8 20 21 22 23 24 25
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 9 10 11 23 24 25 26 29 30
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 6 7 8 20 21 22 23 25 26
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 6 7 8 20 21 22 23 24 25
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 6 7 8 20 21 22 23 26 27
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 6 7 8 20 21 22 23 25 26
[20:58:59] Explicit valence for atom # 21 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 34 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 95 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 95 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 127 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 127 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 60 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 53 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6

   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6ccccc6-c6c(-c7ccccc7)[n]<-2c2cc(F)c(F)cc2[n]<-36)(->...

Обрабатываем строку 160...
   [Строка 160] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! Cc1cc2c(cc1C)[n]1<-[Ir+3]34567(->[O-]C(=O)c8c[n]<-3cc[n]<-48)(->[c-]3ccccc3-c1c(...

Обрабатываем строку 161...
   [Строка 161] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! Cc1cc2c(cc1C)[n]1<-[Ir+3]34567(->[O-]C(=O)c8c[n]<-3cc[n]<-48)(->[c-]3ccccc3-c1c(...

Обрабатываем строку 162...
   [Строка 162] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23456(->[c-]7ccccc7-c7c(-c8ccccc8)[n]<-2c2cc(F)c(F)cc2[n]<-37)(-...

Обрабатываем строку 163...
   [Строка 163] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCOP(=O)(Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n...

Обрабатываем строку 164...
   [Строка 164] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! O=P(O)(O)Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n...

Обрабатываем строку 165...
   [Строка 165] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 7 14 15 20
   Успех! FC(F)(F)c1cc2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c(C(F)(F)F)c1)(->[c-]1c(-c2cccc[n]<-...

Обрабатываем строку 166...
   [Строка 166] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 7 14 15 20
   Успех! FC(F)(F)c1cc2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c(C(F)(F)F)c1)(->[c-]1c(-c2cccc[n]<-...

Обрабатываем строку 167...
   [Строка 167] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 7 14 15 20
   Успех! FC(F)(F)c1cc2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c(C(F)(F)F)c1)(->[c-]1c(-c2cccc[n]<-...

Обрабатываем строку 168...
   [Строка 168] Санитизация не удалась: Explicit valence for atom # 29 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]456(->[c-]7ccccc7-c7cccc[n]<-47)(->[c-]4ccccc4-c4cccc[n]<-54...

Обрабатываем строку 169...
   [Строка 169] Санитизация не удалась: Explicit valence for atom # 35 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]456(->[c-]7c(-c8cccc[n]<-48)sc4ccccc47)(->[c-]4c(-c7cccc[n]<...

Обрабатываем строку 170...
   [Строка 170] Санитизация не удалась: Explicit valence for atom # 45 N, 5, is greater than permitted
   Успех! COC(=O)c1cc2-c3cccc[c-]3<-[Ir+2]345(->[c-]6ccccc6-c6cc(C(=O)OC)c7ccccc7[n]<-36)(...

Обрабатываем строку 171...
   [Строка 171] Санитизация не удалась: Explicit valence for atom # 23 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]45678(->[c-]9ccccc9-c2[n]<-4c2c4ccccc4c4ccccc4c23)(->[c-]2cc...

Обрабатываем строку 172...
   [Строка 172] Санитизация не удалась: Explicit valence for atom # 23 N, 5, is greater than permitted
   Успех! Ic1cc[c-]2<-[Ir+2]34567(->[c-]8ccc(I)cc8-c8[n]<-3c3c9ccccc9c9ccccc9c3[n]<-48-c3c...

Обрабатываем строку 173...
   [Строка 173] Санитизация не удалась: Explicit valence for atom # 3 O, 2, is greater than permitted
   Успех! O=[N+]1[O-]<-[Ir+2]2345678(->[O-][N+](=O)c9ccc(-c%10[n]<-2c2c%11ccccc%11c%11cccc...

Обрабатываем строку 174...
   [Строка 174] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 9 10 11 12 13 14 16 17 18 19 20 21 22
   Успех! c1ccc2c(c1)ccc1-c3ccc4ccccc4[n]3<-[Ir+2]3456(->[c-]7cccc8c9ccccc9c9c(c87)[n]<-3c...

Обрабатываем строку 175...
   [Строка 175] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! c1cc2[O-]<-[Ir+3]34(->[c-]5c(-c6c7ccccc7c7ccccc7[n]<-36)sc3ccccc35)(->[c-]3c(-c5...

Обрабатываем строку 176...
   [Строка 176] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4c(-c5c6ccccc6c6ccccc6[n]<-25)sc2ccccc24)(->[c-]2c(-c4c...

Обрабатываем строку 177...
   [Строка 177] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! c1cc2[O-]<-[Ir+3]34(->[c-]5c(-c6c7ccccc7c7ccccc7[n]<-36)sc3ccccc35)(->[c-]3c(-c5...

Обрабатываем строку 178...
   [Строка 178] Санитизация не удалась: Explicit valence for atom # 49 N, 4, is greater than permitted
   Успех! c1cc2-c3ccc[n-]3<-[Ir+3]34(->[c-]5c(-c6c7ccccc7c7ccccc7[n]<-36)sc3ccccc35)(->[c-...

Обрабатываем строку 179...
   [Строка 179] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 18 19 20 21 22 23
   Успех! O=C([N-]c1ccccc1)c1cccc2ccc[n](<-[Ir+3]34(->[c-]5c(-c6c7ccccc7c7ccccc7[n]<-36)sc...

Обрабатываем строку 180...
   [Строка 180] Санитизация не удалась: Explicit valence for atom # 53 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4c(-c5cc(-c6ccccc6)c6ccccc6[n]<-25)sc2ccccc24)(->[c-]2c...

Обрабатываем строку 181...
   [Строка 181] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CCOC(=O)c1cc2-c3sc4ccccc4[c-]3<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3c(-c5c...

Обрабатываем строку 182...
   [Строка 182] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4c(-c5cc(C(F)(F)F)c6ccccc6[n]<-25)sc2ccccc24)(->[c-]2c(...

Обрабатываем строку 183...
   [Строка 183] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4c(C#N)c[n]<-13)->[c-]1ccccc1-...

Обрабатываем строку 184...
   [Строка 184] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccsc3-c3c4ccccc4c(C#N)c[n]<-13)->[c-]1ccsc1-c1...

Обрабатываем строку 185...
   [Строка 185] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
   Успех! Fc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)ccc1-c1cccc[n]<-31)->[n]1ccc...

Обрабатываем строку 186...
   [Строка 186] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 13
   Успех! Fc1ccc2-c3cccc[c-]3<-[Ir+2]34(->[c-]5ccccc5-c5ccc(F)c[n]<-35)(->[n]2c1)->[n]1ccc...

Обрабатываем строку 187...
   [Строка 187] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 13 14
   Успех! Fc1ccc2-c3ccc(F)c[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)ccc1-c1ccc(F)c[n]<-31)->[...

Обрабатываем строку 188...
   [Строка 188] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)->[...

Обрабатываем строку 189...
   [Строка 189] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 4 11 12 14
   Успех! Fc1cc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c(F)c1F)(->[c-]1c(-c2cccc[n]<-32)cc(F)c(F)c1F...

Обрабатываем строку 190...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 191...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 192...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 193...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 194...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 195...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 196...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 197...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 198...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 199...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 200...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 201...
   [Строка 201] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[n]3ccccc3-c3cccc[n]<-4...

Обрабатываем строку 202...
   [Строка 202] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7ccc8ccccc8[n]<-37)(->[n]3ccc[n]<-4c3-c3[n]...

Обрабатываем строку 203...
   [Строка 203] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3-c3ccc5ccccc...

Обрабатываем строку 204...
   [Строка 204] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! COc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3-c3ccc5cccc...

Обрабатываем строку 205...
   [Строка 205] Санитизация не удалась: Explicit valence for atom # 25 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]456789(->[c-]%10ccccc%10-c2[n]<-4c2c4cccc%10ccc%11cccc(c%11c...

Обрабатываем строку 206...
   [Строка 206] Санитизация не удалась: Explicit valence for atom # 25 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]456789(->[c-]%10ccccc%10-c2[n]<-4c2c4cccc%10ccc%11cccc(c%11c...

Обрабатываем строку 207...
   [Строка 207] Санитизация не удалась: Explicit valence for atom # 25 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]456789(->[c-]%10ccccc%10-c2[n]<-4c2c4cccc%10ccc%11cccc(c%11c...

Обрабатываем строку 208...
   [Строка 208] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 27 28
   Успех! Cc1ccc(-c2c3-c4ccc(C)c[c-]4<-[Ir+2]4567(->[c-]8cc(C)ccc8-c8c(-c9ccc(C)cc9)[n]<-4...

Обрабатываем строку 209...
   [Строка 209] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 27 28
   Успех! Cc1ccc(-c2c3-c4ccc(C)c[c-]4<-[Ir+2]45678(->[c-]9cc(C)ccc9-c9c(-c%10ccc(C)cc%10)[...

Обрабатываем строку 210...
   [Строка 210] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 57 58 59 60 62 73 74
   Успех! Cc1ccc(-c2c3-c4ccc(C)c[c-]4<-[Ir+2]4567(->[c-]8cc(C)ccc8-c8c(-c9ccc(C)cc9)[n]<-4...

Обрабатываем строку 211...
   [Строка 211] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 29 30
   Успех! COc1ccc(-c2c3-c4ccc(OC)c[c-]4<-[Ir+2]4567(->[c-]8cc(OC)ccc8-c8c(-c9ccc(OC)cc9)[n...

Обрабатываем строку 212...
   [Строка 212] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 29 30
   Успех! COc1ccc(-c2c3-c4ccc(OC)c[c-]4<-[Ir+2]45678(->[c-]9cc(OC)ccc9-c9c(-c%10ccc(OC)cc%...

Обрабатываем строку 213...
   [Строка 213] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 61 62 63 64 66 77 78
   Успех! COc1ccc(-c2c3-c4ccc(OC)c[c-]4<-[Ir+2]4567(->[c-]8cc(OC)ccc8-c8c(-c9ccc(OC)cc9)[n...

Обрабатываем строку 214...
   [Строка 214] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 49 50
   Успех! CCCCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CCCC)ccc1-c1cccc[n]<-31)->[...

Обрабатываем строку 215...
   [Строка 215] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[n]3ccccc3-c3ccc5ccccc5...

Обрабатываем строку 216...
   [Строка 216] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cc6ccccc6c[n]<-35)(->[n]3cc5ccccc5cc3-c2c1)-...

Обрабатываем строку 217...
   [Строка 217] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5c6ccccc6cc[n]<-35)(->[n]3ccccc3-c3ccc5ccccc5...

Обрабатываем строку 218...
   [Строка 218] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 44
   Успех! c1ccc2c(c1)ccc1-c3cccc[n]3<-[Ir+2]34(->[c-]5cccc6ccc7ccc[n]<-3c7c65)(->[c-]3cccc...

Обрабатываем строку 219...
   [Строка 219] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5cc6ccccc6cc5-c2c1)(->[c-]1cc2ccccc2cc1-c1cccc[n]<-31)-...

Обрабатываем строку 220...
   [Строка 220] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5ccc6ccccc6c5-c2c1)(->[c-]1ccc2ccccc2c1-c1cccc[n]<-31)-...

Обрабатываем строку 221...
   [Строка 221] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 9 10 11 12 13 14 15 16 17 18 19 20
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5c(-c2c1)c1ccccc1c1ccccc15)(->[c-]1c(-c2cccc[n]<-32)c2c...

Обрабатываем строку 222...
   [Строка 222] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6cc7ccccc7cc6[n]<-35)(->[n]3ccccc3-c3ccc5...

Обрабатываем строку 223...
   [Строка 223] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5cc6ccccc6cc5-c5ccc6ccccc6[n]<-35)(->[c-]3cc5ccccc5cc3-...

Обрабатываем строку 224...
   [Строка 224] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5cc6ccccc6cc5-c5ccc6cc7ccccc7cc6[n]<-35)(->[c-]3cc5cccc...

Обрабатываем строку 225...
   [Строка 225] Санитизация не удалась: Explicit valence for atom # 19 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+3]45678(->[c-]9ccc%10ccccc%10c9-c2[n]<-4c2ccccc23)(->[c-]2ccc3...

Обрабатываем строку 226...
   [Строка 226] Санитизация не удалась: Explicit valence for atom # 19 N, 5, is greater than permitted
   Успех! Cc1cc2c(cc1C)[n-]1<-[Ir+3]34567(->[c-]8ccc9ccccc9c8-c8[n]<-3c3ccccc3[n]<-48-c3cc...

Обрабатываем строку 227...
   [Строка 227] Санитизация не удалась: Explicit valence for atom # 16 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cccc6c7ccccc7cc(-c7[n]<-1c1ccccc1[n]<-27-c1c...

Обрабатываем строку 228...
   [Строка 228] Санитизация не удалась: Explicit valence for atom # 16 N, 5, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]1234(->[c-]5cccc6c7ccccc7cc(-c7[n]<-1c1ccccc1[n]<-27-c1ccccc...

Обрабатываем строку 229...
   [Строка 229] Санитизация не удалась: Explicit valence for atom # 16 N, 5, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5cccc6c7ccccc7cc(-c7[n]<-1c1ccccc1[n]<-2...

Обрабатываем строку 230...
   [Строка 230] Санитизация не удалась: Explicit valence for atom # 19 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc6ccccc6c5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc...

Обрабатываем строку 231...
   [Строка 231] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! Cc1cc2-c3sc4ccccc4[c-]3<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3c(-c5cc(C)c6c...

Обрабатываем строку 232...
   [Строка 232] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4c(-c5ccc6ccccc6[n]<-25)sc2ccccc24)(->[c-]2c(-c4ccc5ccc...

Обрабатываем строку 233...
   [Строка 233] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 43 44 45 46 48 59 60
   Успех! Cc1cc(C)c(-c2cc[n]3<-[Ir+2]4567(->[c-]8ccccc8-c3c2)(->[c-]2ccccc2-c2cc(-c3c(C)cc...

Обрабатываем строку 234...
   [Строка 234] Санитизация не удалась: Explicit valence for atom # 50 N, 5, is greater than permitted
   Успех! Cc1cc(C)c(-c2cc[n]3<-[Ir+2]4567(->[c-]8ccccc8-c3c2)(->[c-]2ccccc2-c2cc(-c3c(C)cc...

Обрабатываем строку 235...
   [Строка 235] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 51 52 53 54 56 67 68
   Успех! Cc1cc(C)c(-c2cc[n]3<-[Ir+2]4567(->[c-]8ccc9ccccc9c8-c3c2)(->[c-]2ccc3ccccc3c2-c2...

Обрабатываем строку 236...
   [Строка 236] Санитизация не удалась: Explicit valence for atom # 58 N, 5, is greater than permitted
   Успех! Cc1cc(C)c(-c2cc[n]3<-[Ir+2]4567(->[c-]8ccc9ccccc9c8-c3c2)(->[c-]2ccc3ccccc3c2-c2...

Обрабатываем строку 237...
   [Строка 237] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 22
   Успех! Cc1cc(C)c(-c2cc[n]3<-[Ir+2]45(->[c-]6ccc7ccccc7c6-c3c2)(->[c-]2ccc3ccccc3c2-c2cc...

Обрабатываем строку 238...
   [Строка 238] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 22
   Успех! Cc1cc(C)c(-c2cc[n]3<-[Ir+2]45(->[c-]6ccc7ccccc7c6-c3c2)(->[c-]2ccc3ccccc3c2-c2cc...

Обрабатываем строку 239...
   [Строка 239] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1ccccc1-c1c3c...

Обрабатываем строку 240...
   [Строка 240] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! CC(=CC(C)=Nc1ccccc1)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1cccc...

Обрабатываем строку 241...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 242...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 243...
   [Строка 243] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)sc1ccccc13)->[c-]1c(-c3cccc[n...

Обрабатываем строку 244...
   [Строка 244] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! CC(=CC(C)=Nc1ccccc1)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)sc1ccccc13)->[c-]1c(-...

Обрабатываем строку 245...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 246...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 247...
   [Строка 247] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! O=C1[N-]C(=Nc2cccc[n]2<-[Ir+3]23(->[c-]4cc(F)cc(F)c4-c4cccc[n]<-24)->[c-]2cc(F)c...

Обрабатываем строку 248...
   [Строка 248] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! O=C1[N-]C(=Nc2c3ccccc3cc[n]2<-[Ir+3]23(->[c-]4cc(F)cc(F)c4-c4cccc[n]<-24)->[c-]2...

Обрабатываем строку 249...
   [Строка 249] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-...

Обрабатываем строку 250...
   [Строка 250] Санитизация не удалась: Explicit valence for atom # 29 O, 2, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-21)C...

Обрабатываем строку 251...
   [Строка 251] Санитизация не удалась: Explicit valence for atom # 29 O, 2, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-21)c...

Обрабатываем строку 252...
   [Строка 252] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]45(->[c-]6ccccc6-c6cccc[n]<-46)(->[c-]4ccccc4-c4cccc[n]<-...

Обрабатываем строку 253...
   [Строка 253] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 37 39 40 41 42 43 44
   Успех! CC(C)(C)c1cc[c-]2<-[Ir+2]34(->[c-]5ccc(C(C)(C)C)cc5-c5cccc[n]<-35)(->[n]3ccccc3-...

Обрабатываем строку 254...
   [Строка 254] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 37 39 40 41 42 43 44
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5c6ccccc6cc[n]<-35)(->[n]3ccccc3-c3sc5ccccc5[...

Обрабатываем строку 255...
   [Строка 255] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-[n]<-37ccc[n]<-47)(->[n]3ccccc3-c3sc4ccccc4[...

Обрабатываем строку 256...
   [Строка 256] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5sc6ccccc6[n]<-35)(->[n]3ccccc3-c3sc5ccccc5[n...

Обрабатываем строку 257...
   [Строка 257] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! COc1ccc(C(=O)C=C([O-]<-[Ir+3]23(->[c-]4c(-c5cccc[n]<-25)c(=O)oc2ccccc24)->[c-]2c...

Обрабатываем строку 258...
   [Строка 258] Санитизация не удалась: Explicit valence for atom # 40 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=CC(=O)c1ccco1)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)c(=O)oc1ccccc13)...

Обрабатываем строку 259...
   [Строка 259] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted

[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 5 7 14 15 20
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 5 7 14 15 20
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 5 7 14 15 20
[20:58:59] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 35 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 45 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 23 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 23 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 3 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 9 10 11 12 13 14 16 17 18 19 20 21 22
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 49 N, 4, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 18 19 20 21 22 23
[20:58:59] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 13
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 13 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 4 11 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 27 28
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 27 28
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 57 58 59 60 62 73 74
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 29 30
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 29 30
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 61 62 63 64 66 77 78
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 49 50
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 44
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 9 10 11 12 13 14 15 16 17 18 19 20
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[20:58:59] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 43 44 45 46 48 59 60
[20:58:59] Explicit valence for atom # 50 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 51 52 53 54 56 67 68
[20:58:59] Explicit valence for atom # 58 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 22
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 22
[20:58:59] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 29 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 29 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 37 39 40 41 42 43 44
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 37 39 40 41 42 43 44
[20:58:59] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 40 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 44 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 72 N, 4, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 5 6 7 9 16
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 5 6 8 19 20
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 18
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 8 9 10 12 19
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 8 9 10 12 19
[20:58:59] Explicit valence for atom # 21 N, 6, is greater than permitted
[20:58:59] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 69 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 59 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 63 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 5 7 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 5 7 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 5 13 14 17
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 3 5 13 14 17
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 10
[20:58:59] Explicit valence for atom # 59 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 5 7 8
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 28 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 31 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 59 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 8 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 8 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 58 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 51 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 58 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 51 N, 4, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 40
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10 11 12 13 14 21 22
[20:58:59] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 25 26
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
[20:58:59] Explicit valence for atom # 41 O, 2, is greater than permitted

   Успех! N#Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)-...

Обрабатываем строку 297...
   [Строка 297] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! N#Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c3-c3c...

Обрабатываем строку 298...
   [Строка 298] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4c(-c5ccccc5)cccc4[n]<-13)->[c-]1c...

Обрабатываем строку 299...
   [Строка 299] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4c(F)cccc4[n]<-13)->[c-]1ccccc1-c1...

Обрабатываем строку 300...
   [Строка 300] Санитизация не удалась: Explicit valence for atom # 53 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4c(-c5ccc(F)cc5)cccc4[n]<-13)->[c-...

Обрабатываем строку 301...
   [Строка 301] Санитизация не удалась: Explicit valence for atom # 69 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4c(cc3-c3ccc5c(-c6ccccc6)cccc5[n]<-13)C(C)(C...

Обрабатываем строку 302...
   [Строка 302] Санитизация не удалась: Explicit valence for atom # 59 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4c(cc3-c3ccc5c(F)cccc5[n]<-13)C(C)(C)c1ccccc...

Обрабатываем строку 303...
   [Строка 303] Санитизация не удалась: Explicit valence for atom # 71 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4c(cc3-c3ccc5c(-c6ccc(F)cc6)cccc5[n]<-13)C(C...

Обрабатываем строку 304...
   [Строка 304] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc(-c5ccccc5)ccc4[n]<-13)->[c-]1c...

Обрабатываем строку 305...
   [Строка 305] Санитизация не удалась: Explicit valence for atom # 53 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc(-c5ccc(F)cc5)ccc4[n]<-13)->[c-...

Обрабатываем строку 306...
   [Строка 306] Санитизация не удалась: Explicit valence for atom # 63 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccccc4)c4cc(-c5ccccc5)ccc4[n]<-...

Обрабатываем строку 307...
   [Строка 307] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4ccccc4[n]<-13)->[c-]1ccccc1-c1ccc...

Обрабатываем строку 308...
   [Строка 308] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3c(-c4c5ccccc5cc[n]<-14)sc1ccccc13)->[c-]1...

Обрабатываем строку 309...
   [Строка 309] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]12(->[c-]3c(-c4c5ccccc5cc[n]<-14)sc1ccccc13)->[c-]1c(-c3c4cc...

Обрабатываем строку 310...
   [Строка 310] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]12(->[c-]3c(-c4c5ccccc5cc[n]<-14)sc1ccccc13)->[c-]1c(-c3c4cc...

Обрабатываем строку 311...
   [Строка 311] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(C(C)(C)C)ccc5-c5[n]<-1ccc[n]<-25)->[c-]1c...

Обрабатываем строку 312...
   [Строка 312] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 5 7 15
   Успех! COc1cc[c-]2<-[Ir+2]34(->[c-]5ccc(OC)cc5-c5ccc(C)c[n]<-35)(->[n]3cc(C)ccc3-c2c1)-...

Обрабатываем строку 313...
   [Строка 313] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 5 7 15
   Успех! COc1cc[c-]2<-[Ir+2]34(->[c-]5ccc(OC)cc5-c5ccc(C)c[n]<-35)(->[n]3cc(C)ccc3-c2c1)-...

Обрабатываем строку 314...
   [Строка 314] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
   Успех! COc1ccc2-c3ccc(C)c[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(OC)ccc1-c1ccc(C)c[n]<-31)-...

Обрабатываем строку 315...
   [Строка 315] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
   Успех! COc1ccc2-c3ccc(C)c[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(OC)ccc1-c1ccc(C)c[n]<-31)-...

Обрабатываем строку 316...
   [Строка 316] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
   Успех! COc1cc2-c3ccc(C)c[n]3<-[Ir+2]34(->[c-]2cc1OC)(->[c-]1cc(OC)c(OC)cc1-c1ccc(C)c[n]...

Обрабатываем строку 317...
   [Строка 317] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 14 15
   Успех! COc1cc2-c3ccc(C)c[n]3<-[Ir+2]34(->[c-]2cc1OC)(->[c-]1cc(OC)c(OC)cc1-c1ccc(C)c[n]...

Обрабатываем строку 318...
   [Строка 318] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 5 13 14 17
   Успех! COc1cc2-c3ccc(C)c[n]3<-[Ir+2]34(->[c-]2c(OC)c1OC)(->[c-]1c(-c2ccc(C)c[n]<-32)cc(...

Обрабатываем строку 319...
   [Строка 319] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 5 13 14 17
   Успех! COc1cc2-c3ccc(C)c[n]3<-[Ir+2]34(->[c-]2c(OC)c1OC)(->[c-]1c(-c2ccc(C)c[n]<-32)cc(...

Обрабатываем строку 320...
   [Строка 320] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 10
   Успех! c1ccc(-c2cc3-c4sc(-c5cccs5)c[c-]4<-[Ir+2]45(->[c-]6cc(-c7cccs7)sc6-c6cc(-c7ccccc...

Обрабатываем строку 321...
   [Строка 321] Санитизация не удалась: Explicit valence for atom # 59 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(-c4cccs4)sc3-c3cc(-c4ccccc4)c4ccccc4[n]<-13...

Обрабатываем строку 322...
   [Строка 322] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 7 8
   Успех! Cc1cc2-c3sc(-c4cccs4)c[c-]3<-[Ir+2]34(->[c-]5cc(-c6cccs6)sc5-c5cc(C)c6ccccc6[n]<...

Обрабатываем строку 323...
   [Строка 323] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(-c4cccs4)sc3-c3cc(C)c4ccccc4[n]<-13)->[c-]1...

Обрабатываем строку 324...
   [Строка 324] Санитизация не удалась: Explicit valence for atom # 28 N, 5, is greater than permitted
   Успех! C[n+]12<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[c-]3ccccc3-c3cccc[n]<-43)-...

Обрабатываем строку 325...
   [Строка 325] Санитизация не удалась: Explicit valence for atom # 29 N, 5, is greater than permitted
   Успех! CC[n+]12<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[c-]3ccccc3-c3cccc[n]<-43)...

Обрабатываем строку 326...
   [Строка 326] Санитизация не удалась: Explicit valence for atom # 31 N, 5, is greater than permitted
   Успех! CCCC[n+]12<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[c-]3ccccc3-c3cccc[n]<-4...

Обрабатываем строку 327...
   [Строка 327] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6ccsc6-c6[n]<-2cc2ccccc2[n]<-36)(->[c-]2ccsc2-c2[n]<-...

Обрабатываем строку 328...
   [Строка 328] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6ccsc6-c6[n]<-2c(N2CCCCC2)c2ccccc2[n]<-36)(->[c-]2ccs...

Обрабатываем строку 329...
   [Строка 329] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! Cc1cccc(C)c1Oc1c2ccccc2[n]2<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37)(->[c-]3ccsc3-c...

Обрабатываем строку 330...
   [Строка 330] Санитизация не удалась: Explicit valence for atom # 59 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6ccsc6-c6[n]<-2c(N(c2ccccc2)c2ccccc2)c2ccccc2[n]<-36)...

Обрабатываем строку 331...
   [Строка 331] Санитизация не удалась: Explicit valence for atom # 25 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cc(C(F)(F)F)ccc6-c6[n]<-2c2c7ccccc7c7ccccc7c2[n]<-36...

Обрабатываем строку 332...
   [Строка 332] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1ccc(-[n]23<-[Ir+3]4567(->[O-]C(=O)c8cccc[n]<-48)(->[c-]4cc(C(F)(F)F)ccc4-c2[n...

Обрабатываем строку 333...
   [Строка 333] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! COc1ccc(-[n]23<-[Ir+3]4567(->[O-]C(=O)c8cccc[n]<-48)(->[c-]4cc(C(F)(F)F)ccc4-c2[...

Обрабатываем строку 334...
   [Строка 334] Санитизация не удалась: Explicit valence for atom # 8 N, 5, is greater than permitted
   Успех! Cc1cc(C)cc(-[n]23<-[Ir+3]4567(->[O-]C(=O)c8cccc[n]<-48)(->[c-]4cc(C(F)(F)F)ccc4-...

Обрабатываем строку 335...
   [Строка 335] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! COc1ccc(-[n]23<-[Ir+3]4567(->[O-]C(=O)c8cc(N(C)C)cc[n]<-48)(->[c-]4cc(C(F)(F)F)c...

Обрабатываем строку 336...
   [Строка 336] Санитизация не удалась: Explicit valence for atom # 8 N, 5, is greater than permitted
   Успех! Cc1cc(C)cc(-[n]23<-[Ir+3]4567(->[O-]C(=O)c8cc(N(C)C)cc[n]<-48)(->[c-]4cc(C(F)(F)...

Обрабатываем строку 337...
   [Строка 337] Санитизация не удалась: Explicit valence for atom # 58 N, 4, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]34567(->[c-]8cc(OC)[n]<-3c(OC)c8-c3cc(C(C)(C)C)cc[n]<-43)(->[n...

Обрабатываем строку 338...
   [Строка 338] Санитизация не удалась: Explicit valence for atom # 51 N, 4, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]3456(->[c-]7cc(OC)[n]<-3c(OC)c7-c3cc(C(C)(C)C)cc[n]<-43)(->[n]...

Обрабатываем строку 339...
   [Строка 339] Санитизация не удалась: Explicit valence for atom # 58 N, 4, is greater than permitted
   Успех! COc1c2-c3cc(C(C)(C)C)cc[n]3<-[Ir+3]3456789(->[c-]2[n]<-3c(OC)[n]<-41)(->[c-]1c(-...

Обрабатываем строку 340...
   [Строка 340] Санитизация не удалась: Explicit valence for atom # 51 N, 4, is greater than permitted
   Успех! COc1c2-c3cc(C(C)(C)C)cc[n]3<-[Ir+3]345678(->[c-]2[n]<-3c(OC)[n]<-41)(->[c-]1c(-c...

Обрабатываем строку 341...
   [Строка 341] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 40
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5cccc6ccc7ccc[n]<-3c7c65)(->[c-]3cccc5ccc6ccc[n]<-4c6c5...

Обрабатываем строку 342...
   [Строка 342] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5c6ccccc6cc[n]<-35)(->[n]3ccccc3-c3cccc[n]<-4...

Обрабатываем строку 343...
   [Строка 343] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5ccc6ccccc6c5-c2c1)(->[c-]1ccc2ccccc2c1-c1cccc[n]<-31)-...

Обрабатываем строку 344...
   [Строка 344] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5cc6ccccc6cc5-c2c1)(->[c-]1cc2ccccc2cc1-c1cccc[n]<-31)-...

Обрабатываем строку 345...
   [Строка 345] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10 11 12 13 14 21 22
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5cc6ccc7cccc8ccc(c5-c2c1)c6c78)(->[c-]1cc2ccc5cccc6ccc(...

Обрабатываем строку 346...
   [Строка 346] Санитизация не удалась: Explicit valence for atom # 25 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]4567(->[c-]8ccccc8-c2[n]<-4c2c4cccc8ccc9cccc(c9c84)c23)(->[c...

Обрабатываем строку 347...
   [Строка 347] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 25 26
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5cc6c7cccc8cccc(c9cccc(c5-c2c1)c96)c87)(->[c-]1cc2c5ccc...

Обрабатываем строку 348...
   [Строка 348] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
   Успех! c1ccc2c3-c4sc5ccccc5[c-]4<-[Ir+2]45(->[c-]6c(-c7c8ccccc8cc[n]<-47)sc4ccccc64)(->...

Обрабатываем строку 349...
   [Строка 349] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5c(-c6c7ccccc7cc[n]<-36)sc3ccccc35)(->[c-]3c(-c5c6ccccc...

Обрабатываем строку 350...
   [Строка 350] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
   Успех! CC(C)(C)c1cc[n]2<-[Ir+2]34(->[c-]5c(-c6c7ccccc7cc[n]<-36)sc3ccccc35)(->[c-]3c(-c...

Обрабатываем строку 351...
   [Строка 351] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4c(-c5c6ccccc6cc[n]<-25)sc2ccccc24)(->[c-]2c(-c4c5ccccc...

Обрабатываем строку 352...
   [Строка 352] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6ccccc6-c6[n]<-2c2ccccc2[n]<-36Cc2ccccc2)(->[c-]2cccc...

Обрабатываем строку 353...
   [Строка 353] Санитизация не удалась: Explicit valence for atom # 14 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cc(F)ccc6-c6[n]<-2c2ccccc2[n]<-36Cc2ccc(F)cc2)(->[c-...

Обрабатываем строку 354...
   [Строка 354] Санитизация не удалась: Explicit valence for atom # 14 N, 5, is greater than permitted
   Успех! Cc1ccc(C[n]23<-[Ir+3]4567(->[O-]C(=O)c8cccc[n]<-48)(->[c-]4cc(C)ccc4-c2[n]<-5c2c...

Обрабатываем строку 355...
   [Строка 355] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! COc1ccc(C[n]23<-[Ir+3]4567(->[O-]C(=O)c8cccc[n]<-48)(->[c-]4cc(OC)ccc4-c2[n]<-5c...

Обрабатываем строку 356...
   [Строка 356] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc(C(F)(F)F)c[n]<-13)->[c-]1ccccc1-c...

Обрабатываем строку 357...
   [Строка 357] Санитизация не удалась: Explicit valence for atom # 53 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(Oc4ccccc4)ccc3-c3ccc(C(F)(F)F)c[n]<-13)->[c...

Обрабатываем строку 358...
   [Строка 358] Санитизация не удалась: Explicit valence for atom # 57 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(S(=O)(=O)c4ccccc4)ccc3-c3ccc(C(F)(F)F)c[n]<...

Обрабатываем строку 359...
   [Строка 359] Санитизация не удалась: Explicit valence for atom # 65 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(N(c4ccccc4)c4ccccc4)ccc3-c3ccc(C(F)(F)F)c[n...

Обрабатываем строку 360...
   [Строка 360] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
   Успех! c1cc[n]2<-[Ir+2]34(->[c-]5c(-c2c1)sc1ccccc15)(->[c-]1c(-c2cccc[n]<-32)sc2ccccc12...

Обрабатываем строку 361...
   [Строка 361] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5c(-c6cccc[n]<-36)sc3ccccc35)(->[c-]3c(-c5cccc[n]<-45)...

Обрабатываем строку 362...
   [Строка 362] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
   Успех! COc1cc[n]2<-[Ir+2]34(->[c-]5c(-c6cccc[n]<-36)sc3ccccc35)(->[c-]3c(-c5cccc[n]<-45...

Обрабатываем строку 363...
   [Строка 363] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37)(->[c-]3cc(OC)[n]<-4c(C)c3-c3ccc...

Обрабатываем строку 364...
   [Строка 364] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4cc(F)cc(F)c4-c4cccc[n]<-24)(->[c-]2cc(F)cc(F)c2-c2cccc...

Обрабатываем строку 365...
   [Строка 365] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 12
   Успех! COc1c[c-]2<-[Ir+2]3456(->[c-]7cc(OC)[n]<-3c(C)c7-c3cc(C)cc[n]<-43)(->[n]3ccc(C)c...

Обрабатываем строку 366...
   [Строка 366] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 12
   Успех! COc1c[c-]2<-[Ir+2]3456(->[c-]7cc(OC)[n]<-3c(OC)c7-c3cc(C)cc[n]<-43)(->[n]3ccc(C)...

Обрабатываем строку 367...
   [Строка 367] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11
   Успех! COc1c[c-]2<-[Ir+2]3456(->[c-]7cc(OC)[n]<-3c(OC)c7-c3cccc[n]<-43)(->[n]3ccccc3-c2...

Обрабатываем строку 368...
   [Строка 368] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 14
   Успех! Cc1ccc2-c3c[n]4<-[Ir+2]567(->[c-]3cc4C)(->[c-]3cc(C)[n]<-5cc3-c3ccc(C)c[n]<-63)(...

Обрабатываем строку 369...
   [Строка 369] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23456(->[c-]7cc(F)[n]<-2c(F)c7-c2cccc[n]<-32)(->[c-]2cc(F)[n]<-4...

Обрабатываем строку 370...
   [Строка 370] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cc(F)[n]<-2c(F)c6-c2cccc[n]<-32)(->[c-]2cc(F)[n]<-4c...

Обрабатываем строку 371...
   [Строка 371] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cc(F)[n]<-2c(F)c6-c2cccc[n]<-32)(->[c-]2cc(F)[n]<-4c...

Обрабатываем строку 372...
   [Строка 372] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! COCCOc1c[c-]2<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37)(->[c-]3cc(OCCOC)[n]<-4c(OCCO...

Обрабатываем строку 373...
   [Строка 373] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! COCCOc1c[c-]2<-[Ir+3]34567(->[O-]C(=O)c8c[n]<-3cc[n]<-48)(->[c-]3cc(OCCOC)[n]<-5...

Обрабатываем строку 374...
   [Строка 374] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! COCCOc1c[c-]2<-[Ir+3]3456(->[O-]C(=O)c7c8ccccc8cc[n]<-37)(->[c-]3cc(OCCOC)[n]<-4...

Обрабатываем строку 375...
   [Строка 375] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! COCCOc1c[c-]2<-[Ir+3]3456(->[O-]C(=O)c7ccc8ccccc8[n]<-37)(->[c-]3cc(OCCOC)[n]<-4...

Обрабатываем строку 376...
   [Строка 376] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37)(->[c-]3cc(OC)[n]<-4c(OC)c3-c3cc...

Обрабатываем строку 377...
   [Строка 377] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cc(F)[n]<-2c(F)c6-c2cccc[n]<-32)(->[c-]2cc(F)[n]<-4c...

Обрабатываем строку 378...
   [Строка 378] Санитизация не удалась: Explicit valence for atom # 8 N, 5, is greater than permitted
   Успех! CC(C)(C)c1cc[n]2<-[Ir+2]345678(->[c-]9cc(F)cc(F)c9-c9c[n]<-3(Cc3ccccc3)[n]<-4[n]...

Обрабатываем строку 379...
   [Строка 379] Санитизация не удалась: Explicit valence for atom # 8 N, 5, is greater than permitted
   Успех! CN(C)c1cc[n]2<-[Ir+2]345678(->[c-]9cc(F)cc(F)c9-c9c[n]<-3(Cc3ccccc3)[n]<-4[n]<-5...

Обрабатываем строку 380...
   [Строка 380] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 15
   Успех! Cc1ccc2-c3c(F)cc(F)c[c-]3<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5ccc(C)c[n]<-35)(->[n]2...

Обрабатываем строку 381...
   [Строка 381] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 15
   Успех! Cc1ccc2-c3c(F)cc(F)c[c-]3<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5ccc(C)c[n]<-35)(->[n]2...

Обрабатываем строку 382...
   [Строка 382] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! CC(C)(C)c1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c...

Обрабатываем строку 383...
   [Строка 383] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! CN(C)c1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c3-c...

Обрабатываем строку 384...
   [Строка 384] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1ccccc1-...

Обрабатываем строку 385...
   [Строка 385] Санитизация не удалась: Explicit valence for atom # 25 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]4567(->[c-]8ccccc8-c2[n]<-4c2c4cccc8ccc9cccc(c9c84)c23)(->[c...

Обрабатываем строку 386...
   [Строка 386] Санитизация не удалась: Explicit valence for atom # 25 N, 5, is greater than permitted

[20:58:59] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 57 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
[20:58:59] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 12
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 12
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 7 8 9 10 11
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 14
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 8 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 8 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 15
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 16 18 19 20 21
[20:58:59] Explicit valence for atom # 22 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 83 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 10 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 54 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 38 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 29 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 54 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 60 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 42 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 46 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 54 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 41 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 49 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:58:59] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:58:59] Explicit valence for atom # 35 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 18 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:58:59] Explicit valence for atom # 52 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 52 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 52 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 54 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 56 O, 2, is greater than permitted
[20:58:59] Explicit valence for atom # 54 N, 4, is greater than permitted
[20:58:59] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 59 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 3 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 22 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 40 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17 18 19
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted

   [Строка 427] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-...

Обрабатываем строку 428...
   [Строка 428] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 429...
   [Строка 429] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! COC(=O)c1cc[n]2<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]4ccccc4-c2c1)->[c-]1ccccc1-c1...

Обрабатываем строку 430...
   [Строка 430] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc6c(cc5-c5cccc[n]<-15)c1ccccc1[n]<-26-c1ccc...

Обрабатываем строку 431...
   [Строка 431] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc6c(cc5-c5cccc[n]<-15)c1ccccc1[n]<-26-c1ccc...

Обрабатываем строку 432...
   [Строка 432] Санитизация не удалась: Explicit valence for atom # 18 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc6c(cc5-c5ccc(F)c[n]<-15)c1ccccc1[n]<-26-c1...

Обрабатываем строку 433...
   [Строка 433] Санитизация не удалась: Explicit valence for atom # 19 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc6c(cc5-c5cc(C)cc[n]<-15)c1ccccc1[n]<-26-c1...

Обрабатываем строку 434...
   [Строка 434] Санитизация не удалась: Explicit valence for atom # 52 O, 2, is greater than permitted
   Успех! CCCCCCC(=CC(C)=O)[O-]<-[Ir+3]12(->[c-]3ccc(S(=O)(=O)Cc4ccccc4)cc3-c3cccc[n]<-13)...

Обрабатываем строку 435...
   [Строка 435] Санитизация не удалась: Explicit valence for atom # 52 O, 2, is greater than permitted
   Успех! CCCCCCC(=CC(C)=O)[O-]<-[Ir+3]12(->[c-]3cccc(S(=O)(=O)Cc4ccccc4)c3-c3cccc[n]<-13)...

Обрабатываем строку 436...
   [Строка 436] Санитизация не удалась: Explicit valence for atom # 52 O, 2, is greater than permitted
   Успех! CCCCCCC(=CC(C)=O)[O-]<-[Ir+3]12(->[c-]3cc(S(=O)(=O)Cc4ccccc4)ccc3-c3cccc[n]<-13)...

Обрабатываем строку 437...
   [Строка 437] Санитизация не удалась: Explicit valence for atom # 54 O, 2, is greater than permitted
   Успех! CCCCCCC(=CC(C)=O)[O-]<-[Ir+3]12(->[c-]3cc(S(=O)(=O)Cc4ccccc4)cc(F)c3-c3cccc[n]<-...

Обрабатываем строку 438...
   [Строка 438] Санитизация не удалась: Explicit valence for atom # 56 O, 2, is greater than permitted
   Успех! CCCCCCC(=CC(C)=O)[O-]<-[Ir+3]12(->[c-]3c(F)c(S(=O)(=O)Cc4ccccc4)cc(F)c3-c3cccc[n...

Обрабатываем строку 439...
   [Строка 439] Санитизация не удалась: Explicit valence for atom # 54 N, 4, is greater than permitted
   Успех! O=S(=O)(Cc1ccccc1)c1cc[c-]2<-[Ir+3]3456(->[c-]7ccc(S(=O)(=O)Cc8ccccc8)cc7-c7cccc...

Обрабатываем строку 440...
   [Строка 440] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4c5ccccc5ccc4[n]<-13)->[c-]1ccccc1...

Обрабатываем строку 441...
   [Строка 441] Санитизация не удалась: Explicit valence for atom # 59 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccccc4)c4c5ccccc5ccc4[n]<-13)->...

Обрабатываем строку 442...
   [Строка 442] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc5ccccc5cc4[n]<-13)->[c-]1ccccc1...

Обрабатываем строку 443...
   [Строка 443] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1ccccc1-c1c3c...

Обрабатываем строку 444...
   [Строка 444] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3oc4ccccc4[n]<-13)->[c-]1ccccc1-c1oc3c...

Обрабатываем строку 445...
   [Строка 445] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(Cl)ccc3-c3oc4ccccc4[n]<-13)->[c-]1cc(Cl)ccc...

Обрабатываем строку 446...
   [Строка 446] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3oc4cc(Cl)ccc4[n]<-13)->[c-]1ccccc1-c1...

Обрабатываем строку 447...
   [Строка 447] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(F)cc(F)cc3-c3oc4ccccc4[n]<-13)->[c-]1c(F)cc(...

Обрабатываем строку 448...
   [Строка 448] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4ccccc4cc3-c3oc4ccccc4[n]<-13)->[c-]1cc3cccc...

Обрабатываем строку 449...
   [Строка 449] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]12(->[c-]3cc(Cl)ccc3-c3oc4ccccc4[n]<-13)->[c-]1cc(Cl)ccc1-c1...

Обрабатываем строку 450...
   [Строка 450] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]12(->[c-]3c(F)cc(F)cc3-c3oc4ccccc4[n]<-13)->[c-]1c(F)cc(F)cc...

Обрабатываем строку 451...
   [Строка 451] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! O=C(C=C([O-]<-[Ir+3]12(->[c-]3cc4ccccc4cc3-c3oc4ccccc4[n]<-13)->[c-]1cc3ccccc3cc...

Обрабатываем строку 452...
   [Строка 452] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2C[n]34<-[Ir+3]56789(->[c-]2c1)(->[c-]1cc(F)cc(F)c1C[n]<-51ccc[n]<-61)(...

Обрабатываем строку 453...
   [Строка 453] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! CC(C)(C)c1cc[n]2<-[Ir+3]345678(->[c-]9cc(F)cc(F)c9C[n]<-39ccc[n]<-49)(->[c-]3cc(...

Обрабатываем строку 454...
   [Строка 454] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! CC(C)(C)c1cc[n]2<-[Ir+3]345678(->[c-]9cc(F)cc(F)c9C[n]<-39ccc[n]<-49)(->[c-]3cc(...

Обрабатываем строку 455...
   [Строка 455] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Fc1ccc(C(F)(F)F)c2C[n]34<-[Ir+3]56789(->[c-]12)(->[c-]1c(F)ccc(C(F)(F)F)c1C[n]<-...

Обрабатываем строку 456...
   [Строка 456] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-[n]34<-[Ir+3]567(->[O-]c8ccccc8-c8oc9ccccc9[n]<-58)(->[c-]2c1)(->[c-]...

Обрабатываем строку 457...
   [Строка 457] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-[n]34<-[Ir+3]567(->[O-]c8ccccc8-c8sc9ccccc9[n]<-58)(->[c-]2c1)(->[c-]...

Обрабатываем строку 458...
   [Строка 458] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(C)(C)c1cc2-c3cccc[n]3<-[Ir+3]34567(->[c-]8cc(F)cc(F)c8-[n]<-38ccc[n]<-48)(->[...

Обрабатываем строку 459...
   [Строка 459] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(C)(C)c1cc2-c3c[n]4<-[Ir+3]56789(->[c-]%10cc(F)cc(F)c%10-[n]<-5%10ccc[n]<-6%10...

Обрабатываем строку 460...
   [Строка 460] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! CC(C)(C)c1cc2-c3c4ccccc4cc[n]3<-[Ir+3]34567(->[c-]8cc(F)cc(F)c8-[n]<-38ccc[n]<-4...

Обрабатываем строку 461...
   [Строка 461] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-[n]34<-[Ir+3]5678(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-[n]<-51ccc[n]<-61)(-...

Обрабатываем строку 462...
   [Строка 462] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-[n]34<-[Ir+3]5678(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-[n]<-51ccc[n]<-61)(-...

Обрабатываем строку 463...
   [Строка 463] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-[n]34<-[Ir+3]5678(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-[n]<-51ccc[n]<-61)(-...

Обрабатываем строку 464...
   [Строка 464] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C)ccc3-c3c4ccccc4cc[n]<-13)->[c-]1cc(C)ccc1...

Обрабатываем строку 465...
   [Строка 465] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C(F)(F)F)ccc3-c3c4ccccc4cc[n]<-13)->[c-]1cc...

Обрабатываем строку 466...
   [Строка 466] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1ccc2-c3c4ccccc4cc[n]3<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]2c1)->[c-]1cc(OC)cc...

Обрабатываем строку 467...
   [Строка 467] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cccc(C)c3-c3c4ccccc4cc[n]<-13)->[c-]1cccc(C)c1...

Обрабатываем строку 468...
   [Строка 468] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cccc(C(F)(F)F)c3-c3c4ccccc4cc[n]<-13)->[c-]1cc...

Обрабатываем строку 469...
   [Строка 469] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! COc1ccc[c-]2<-[Ir+3]3(->[O-]C(C)=CC(C)=O)(->[c-]4cccc(OC)c4-c4c5ccccc5cc[n]<-34)...

Обрабатываем строку 470...
   [Строка 470] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc4ccc[n]<-1c34)->[c-]1ccccc1-c1ccc...

Обрабатываем строку 471...
   [Строка 471] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(F)ccc3-c3cccc4ccc[n]<-1c34)->[c-]1cc(F)ccc1...

Обрабатываем строку 472...
   [Строка 472] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(F)cc(F)cc3-c3cccc4ccc[n]<-1c34)->[c-]1c(F)cc...

Обрабатываем строку 473...
   [Строка 473] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(F)cc(F)c3-c3cccc4ccc[n]<-1c34)->[c-]1cc(F)c...

Обрабатываем строку 474...
   [Строка 474] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc1)->[c...

Обрабатываем строку 475...
   [Строка 475] Санитизация не удалась: Explicit valence for atom # 19 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc6ccccc6c5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc...

Обрабатываем строку 476...
   [Строка 476] Санитизация не удалась: Explicit valence for atom # 16 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cccc6c7ccccc7cc(-c7[n]<-1c1ccccc1[n]<-27-c1c...

Обрабатываем строку 477...
   [Строка 477] Санитизация не удалась: Explicit valence for atom # 3 N, 5, is greater than permitted
   Успех! CC[n]12<-[Ir+3]34567(->[O-]C(C)=CC(C)=O)(->[c-]8cc1c(cc8-c1[n]<-3c3ccccc3[n]<-41...

Обрабатываем строку 478...
   [Строка 478] Санитизация не удалась: Explicit valence for atom # 22 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc6c(cc5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc1)C(...

Обрабатываем строку 479...
   [Строка 479] Санитизация не удалась: Explicit valence for atom # 14 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cscc5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc1)->[c-...

Обрабатываем строку 480...
   [Строка 480] Санитизация не удалась: Explicit valence for atom # 33 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(-c6ccc(N(c7ccccc7)c7ccccc7)s6)ccc5-c5[n]<...

Обрабатываем строку 481...
   [Строка 481] Санитизация не удалась: Explicit valence for atom # 33 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]123456(->[c-]7cc(-c8cc(-c9ccccc9)[n]<-1c(-c1ccccc1)c8)cc...

Обрабатываем строку 482...
   [Строка 482] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1ccccc1-c1c3c...

Обрабатываем строку 483...
   [Строка 483] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(F)ccc3-c3c4ccccc4cc[n]<-13)->[c-]1cc(F)ccc1...

Обрабатываем строку 484...
   [Строка 484] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(F)ccc3-c3c4ccccc4c4ccccc4[n]<-13)->[c-]1cc(...

Обрабатываем строку 485...
   [Строка 485] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cccc6c7ccccc7c7c(c65)[n]<-1cc[n]<-27)->[c-]1...

Обрабатываем строку 486...
   [Строка 486] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cccc6c7ccccc7c7c(c65)[n]<-1cc(C)[n]<-27)->[c...

Обрабатываем строку 487...
   [Строка 487] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-...

Обрабатываем строку 488...
   [Строка 488] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C)ccc3-c3cccc[n]<-13)->[c-]1cc(C)ccc1-c1ccc...

Обрабатываем строку 489...
   [Строка 489] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cccc4ccc5ccc[n]<-1c5c43)->[c-]1cccc3ccc4ccc[n]...

Обрабатываем строку 490...
   [Строка 490] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3sc4ccccc4[n]<-13)->[c-]1ccccc1-c1sc3c...

Обрабатываем строку 491...
   [Строка 491] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4sc5ccccc5[n]<-24)(->[c-]2ccccc2-c2sc4ccccc4[n...

Обрабатываем строку 492...
   [Строка 492] Санитизация не удалась: Explicit valence for atom # 40 O, 2, is greater than permitted
   Успех! CN=Cc1ccccc1[O-]<-[Ir+3]12(->[c-]3ccccc3-c3sc4ccccc4[n]<-13)->[c-]1ccccc1-c1sc3c...

Обрабатываем строку 493...
   [Строка 493] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccc4ccccc4c3-c3sc4ccccc4[n]<-13)->[c-]1ccc3ccc...

Обрабатываем строку 494...
   [Строка 494] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4ccccc4[n]<-13)->[c-]1ccccc1-c1ccc...

Обрабатываем строку 495...
   [Строка 495] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1ccccc1-...

Обрабатываем строку 496...
   [Строка 496] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(N(c2ccccc2)c2ccc(-c3cc[n]4<-[Ir+2]56(->[c-]7ccccc7-c7cccc[n]<-57)(->[c-]5c...

Обрабатываем строку 497...
   [Строка 497] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17 18 19
   Успех! CCN(CC)c1ccc2c(c1)oc(=O)c1-c3sc4ccccc4[n]3<-[Ir+2]34(->[c-]12)(->[c-]1c(-c2sc5cc...

Обрабатываем строку 498...
   [Строка 498] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccc4ccccc4c3-c3scc[n]<-13)->[c-]1ccc3ccccc3c1-...

Обрабатываем строку 499...
   [Строка 499] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4ccccc4cc3-c3scc[n]<-13)->[c-]1cc3ccccc3cc1-...

Обрабатываем строку 500...
   [Строка 500] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc1)->[c...

Обрабатываем строку 501...
   [Строка 501] Санитизация не удалась: Explicit valence for atom # 16 N, 5, is greater than permitted
   Успех! COc1cc[c-]2<-[Ir+3]345(->[O-]C(C)=CC(C)=O)(->[c-]6ccc(OC)cc6-c6[n]<-3c3ccccc3[n]...

Обрабатываем строку 502...
   [Строка 502] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! COc1ccc2-c3[n]4<-[Ir+3]56(->[O-]C(C)=CC(C)=O)(->[c-]2c1)(->[c-]1cc(OC)ccc1-c1[n]...

Обрабатываем строку 503...
   [Строка 503] Санитизация не удалась: Explicit valence for atom # 16 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc(C#N)cc5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc1...

Обрабатываем строку 504...
   [Строка 504] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(C#N)ccc5-c5[n]<-1c1ccccc1[n]<-25-c1ccccc1...

Обрабатываем строку 505...
   [Строка 505] Санитизация не удалась: Explicit valence for atom # 14 N, 5, is greater than permitted
   Успех! COc1cc2-c3[n]4<-[Ir+3]56(->[O-]C(C)=CC(C)=O)(->[c-]2cc1C#N)(->[c-]1cc(C#N)c(OC)c...

Обрабатываем строку 506...
   [Строка 506] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]345(->[O-]C(C)=CC(C)=O)(->[c-]6cc(OC)c(C#N)cc6-c6[n]<-3c3ccccc...

Обрабатываем строку 507...
   [Строка 507] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! c1cc[c-]2<-[Ir+3]34(->[O-]c5cccc6ccc[n]<-3c56)(->[c-]3ccccc3-c3c5ccccc5c5ccccc5[...

Обрабатываем строку 508...
   [Строка 508] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4c5ccccc5c5ccccc5[n]<-24)(->[c-]2ccccc2-c2c4cc...

Обрабатываем строку 509...
   [Строка 509] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! c1cc[c-]2<-[Ir+3]34(->[O-]c5cccc6ccc7ccc[n]<-3c7c56)(->[c-]3ccccc3-c3c5ccccc5c5c...

Обрабатываем строку 510...
   [Строка 510] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! O=C([N-]c1ccccc1)c1cccc2ccc[n](<-[Ir+3]34(->[c-]5ccccc5-c5c6ccccc6c6ccccc6[n]<-3...

Обрабатываем строку 511...
   [Строка 511] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! N#Cc1c[n]2<-[Ir+3]34(->[O-]c5cccc6ccc[n]<-3c56)(->[c-]3ccccc3-c2c2ccccc12)->[c-]...

Обрабатываем строку 512...
   [Строка 512] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! N#Cc1c[n]2<-[Ir+3]34(->[O-]C(=O)c5cccc6ccc[n]<-3c56)(->[c-]3ccccc3-c2c2ccccc12)-...

Обрабатываем строку 513...
   [Строка 513] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14 15 16 17 18
   Успех! N#Cc1c[n]2<-[Ir+3]3(->[c-]4ccccc4-c2c2ccccc12)(->[c-]1ccccc1-c1c2ccccc2c(C#N)c[n...

Обрабатываем строку 514...
   [Строка 514] Санитизация не удалась: Explicit valence for atom # 33 N, 5, is greater than permitted
   Успех! CC(C)(C)c1ccc(-[n]23<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cc...

Обрабатываем строку 515...
   [Строка 515] Санитизация не удалась: Explicit valence for atom # 34 N, 5, is greater than permitted
   Успех! c1ccc(Oc2ccc(-[n]34<-[Ir+2]5678(->[c-]9ccccc9-c9cccc[n]<-59)(->[c-]5ccccc5-c5ccc...

Обрабатываем строку 516...

[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14 15 16 17 18
[20:59:00] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 77 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 63 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 59 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 42 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 47 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 97 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 59 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 30 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 40 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 89 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 42 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 49 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 57 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 57 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 51 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 53 N, 4, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 5 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 5 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 8 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 5 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 5 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 8 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 67 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 57 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 13 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 2 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 2 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 67 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 69 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 75 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 67 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 83 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 69 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 85 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 75 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 91 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted

   [Строка 558] Санитизация не удалась: Explicit valence for atom # 53 N, 4, is greater than permitted
   Успех! Cc1cc(C)c(-c2cc3-c4c(F)cc(F)c[c-]4<-[Ir+3]456789(->[c-]%10cc(F)cc(F)c%10-c%10cc(...

Обрабатываем строку 559...
   [Строка 559] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8c9cc%10ccccc%10cc9c(-c9ccccc9)[n]<-4...

Обрабатываем строку 560...
   [Строка 560] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]4567(->[c-]8ccsc8-c8c9cc%10ccccc%10cc9c(-c9cccs9)[n]<-4[n...

Обрабатываем строку 561...
   [Строка 561] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]45(->[c-]6ccccc6-c6cccc[n]<-46)(->[c-]4ccccc4-c4cccc[n]<-...

Обрабатываем строку 562...
   [Строка 562] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
   Успех! c1ccc(-c2cc[c-]3<-[Ir+2]45(->[c-]6ccc(-c7ccccc7)cc6-c6cccc[n]<-46)(->[n]4ccccc4-...

Обрабатываем строку 563...
   [Строка 563] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]45(->[c-]6ccccc6-c3c2)(->[c-]2ccccc2-c2cc(-c3ccccc3)cc[n]...

Обрабатываем строку 564...
   [Строка 564] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
   Успех! c1ccc(-c2cc[c-]3<-[Ir+2]45(->[c-]6ccc(-c7ccccc7)cc6-c6cc(-c7ccccc7)cc[n]<-46)(->...

Обрабатываем строку 565...
   [Строка 565] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
   Успех! c1ccc(-c2cc[c-]3<-[Ir+2]45(->[c-]6ccc(-c7ccccc7)cc6-c6cccc[n]<-46)(->[n]4ccccc4-...

Обрабатываем строку 566...
   [Строка 566] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]45(->[c-]6ccccc6-c3c2)(->[c-]2ccccc2-c2cc(-c3ccccc3)cc[n]...

Обрабатываем строку 567...
   [Строка 567] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 11 12
   Успех! c1ccc(-c2cc[c-]3<-[Ir+2]45(->[c-]6ccc(-c7ccccc7)cc6-c6cc(-c7ccccc7)cc[n]<-46)(->...

Обрабатываем строку 568...
   [Строка 568] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-31...

Обрабатываем строку 569...
   [Строка 569] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
   Успех! CCCCNCc1ccc(-c2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(-c3ccc(CNCCCC)cc3)...

Обрабатываем строку 570...
   [Строка 570] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCNC(=O)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<...

Обрабатываем строку 571...
   [Строка 571] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
   Успех! CCNC(=O)c1cc[n]2<-[Ir+2]34(->[c-]5cc(-c6ccccc6)ccc5-c5cccc[n]<-35)(->[c-]3cc(-c5...

Обрабатываем строку 572...
   [Строка 572] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-31...

Обрабатываем строку 573...
   [Строка 573] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-31...

Обрабатываем строку 574...
   [Строка 574] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-31...

Обрабатываем строку 575...
   [Строка 575] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-31...

Обрабатываем строку 576...
   [Строка 576] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
   Успех! CCCCNCc1ccc(-c2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(-c3ccc(CNCCCC)cc3)...

Обрабатываем строку 577...
   [Строка 577] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
   Успех! CCCCNCc1ccc(-c2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(-c3ccc(CNCCCC)cc3)...

Обрабатываем строку 578...
   [Строка 578] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
   Успех! CCCCNCc1ccc(-c2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(-c3ccc(CNCCCC)cc3)...

Обрабатываем строку 579...
   [Строка 579] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 11 12 14 21 22
   Успех! CCCCNCc1ccc(-c2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(-c3ccc(CNCCCC)cc3)...

Обрабатываем строку 580...
   [Строка 580] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
   Успех! Cc1c[n]2<-[Ir+2]34(->[c-]5cc(-c6ccccc6)ccc5-c5cccc[n]<-35)(->[c-]3cc(-c5ccccc5)c...

Обрабатываем строку 581...
   [Строка 581] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(-c6ccccc6)ccc5-c5cccc[n]<-35)(->[c-]3cc(-c5ccccc5)...

Обрабатываем строку 582...
   [Строка 582] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
   Успех! c1ccc(-c2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(-c3ccccc3)ccc2-c2cccc[n]...

Обрабатываем строку 583...
   [Строка 583] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
   Успех! c1ccc(-c2ccc3-c4cccc[n]4<-[Ir+2]45(->[c-]3c2)(->[c-]2cc(-c3ccccc3)ccc2-c2cccc[n]...

Обрабатываем строку 584...
   [Строка 584] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-31...

Обрабатываем строку 585...
   [Строка 585] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 10 11 12
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(-c6ccccc6)ccc5-c5cccc[n]<-35)(->[c-]3cc(-c5ccccc5)...

Обрабатываем строку 586...
   [Строка 586] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! O=Cc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(C=O)ccc1-c1cccc[n]<-31)->[n]...

Обрабатываем строку 587...
   [Строка 587] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! O=Cc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(C=O)ccc1-c1cccc[n]<-31)->[n]...

Обрабатываем строку 588...
   [Строка 588] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! Cc1c[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)ccc3-c3cccc[n...

Обрабатываем строку 589...
   [Строка 589] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! O=Cc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(C=O)ccc1-c1cccc[n]<-31)->[n]...

Обрабатываем строку 590...
   [Строка 590] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! c1cc[c-]2<-[Ir+2]345678(->[c-]9ccccc9-[n]<-39ccc[n]<-49)(->[n]3cccc4c3c3c(ccc[n]...

Обрабатываем строку 591...
   [Строка 591] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! CCCCNC(=O)c1c[n]2<-[Ir+2]345678(->[c-]9ccccc9-[n]<-39ccc[n]<-49)(->[c-]3ccccc3-[...

Обрабатываем строку 592...
   Успех! C1=C[C-]2<-[Ir+2]3456(->[C-]7C=CC=c8ccc9c(c87)[N]<-3C=CC=9)(->[N]3C=CC=c7ccc(c2c...

Обрабатываем строку 593...
   Успех! CCCCNC(=O)c1c[n]2<-[Ir+2]3456(->[C-]7C=CC=c8ccc9c(c87)[N]<-3C=CC=9)(->[C-]3C=CC=...

Обрабатываем строку 594...
   [Строка 594] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7ccc8ccccc8[n]<-37)(->[n]3cccc7c3c3c(ccc[n]...

Обрабатываем строку 595...
   [Строка 595] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCCCNC(=O)c1c[n]2<-[Ir+2]3456(->[c-]7ccccc7-c7ccc8ccccc8[n]<-37)(->[c-]3ccccc3-c...

Обрабатываем строку 596...
   [Строка 596] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c3-c3ccc...

Обрабатываем строку 597...
   [Строка 597] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 598...
   [Строка 598] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1cccc2cc...

Обрабатываем строку 599...
   [Строка 599] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]45(->[c-]6ccccc6-c6cccc[n]<-46)(->[c-]4ccccc4-c4cccc[n]<-...

Обрабатываем строку 600...
   [Строка 600] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6ccccc6-[n]<-26ccc[n]<-36)(->[c-]2ccccc2-[n]<-42ccc[n...

Обрабатываем строку 601...
   [Строка 601] Санитизация не удалась: Explicit valence for atom # 5 N, 5, is greater than permitted
   Успех! Cc1cc[n]23-c4cccc[c-]4<-[Ir+3]->2456(->[O-]C(=O)c2cc7ccccc7c[n]<-42)(->[c-]2cccc...

Обрабатываем строку 602...
   [Строка 602] Санитизация не удалась: Explicit valence for atom # 5 N, 5, is greater than permitted
   Успех! Cc1c[n]2<-[Ir+3]3456(->[O-]C(=O)c7cc8ccccc8c[n]<-37)(->[c-]3ccccc3-[n]<-42c1)->[...

Обрабатываем строку 603...
   [Строка 603] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1cc(C)[n]23-c4cccc[c-]4<-[Ir+3]->2456(->[O-]C(=O)c2cc7ccccc7c[n]<-42)(->[c-]2c...

Обрабатываем строку 604...
   [Строка 604] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1ccc2-[n]34<-[Ir+3]567(->[O-]C(=O)c8cc9ccccc9c[n]<-58)(->[c-]2c1)(->[c-]1cc(C)...

Обрабатываем строку 605...
   [Строка 605] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! Cc1cc[c-]2<-[Ir+3]3456(->[O-]C(=O)c7cc8ccccc8c[n]<-37)(->[c-]3ccc(C)cc3-[n]<-43c...

Обрабатываем строку 606...
   [Строка 606] Санитизация не удалась: Explicit valence for atom # 8 N, 5, is greater than permitted
   Успех! Cc1ccc[c-]2<-[Ir+3]3456(->[O-]C(=O)c7cc8ccccc8c[n]<-37)(->[c-]3cccc(C)c3-[n]<-43...

Обрабатываем строку 607...
   [Строка 607] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! Cc1cc[c-]2<-[Ir+3]3456(->[O-]C(=O)c7cc8ccccc8c[n]<-37)(->[c-]3ccc(C)cc3-[n]<-43c...

Обрабатываем строку 608...
   [Строка 608] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6ccccc6-[n]<-26ccc[n]<-36)(->[c-]2ccccc2-[n]<-42ccc[n...

Обрабатываем строку 609...
   [Строка 609] Санитизация не удалась: Explicit valence for atom # 5 N, 5, is greater than permitted
   Успех! Cc1cc[n]23-c4cccc[c-]4<-[Ir+3]->2456(->[O-]C(=O)c2c7ccccc7cc[n]<-42)(->[c-]2cccc...

Обрабатываем строку 610...
   [Строка 610] Санитизация не удалась: Explicit valence for atom # 5 N, 5, is greater than permitted
   Успех! Cc1c[n]2<-[Ir+3]3456(->[O-]C(=O)c7c8ccccc8cc[n]<-37)(->[c-]3ccccc3-[n]<-42c1)->[...

Обрабатываем строку 611...
   [Строка 611] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1cc(C)[n]23-c4cccc[c-]4<-[Ir+3]->2456(->[O-]C(=O)c2c7ccccc7cc[n]<-42)(->[c-]2c...

Обрабатываем строку 612...
   [Строка 612] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Cc1ccc2-[n]34<-[Ir+3]567(->[O-]C(=O)c8c9ccccc9cc[n]<-58)(->[c-]2c1)(->[c-]1cc(C)...

Обрабатываем строку 613...
   [Строка 613] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! Cc1cc[c-]2<-[Ir+3]3456(->[O-]C(=O)c7c8ccccc8cc[n]<-37)(->[c-]3ccc(C)cc3-[n]<-43c...

Обрабатываем строку 614...
   [Строка 614] Санитизация не удалась: Explicit valence for atom # 8 N, 5, is greater than permitted
   Успех! Cc1ccc[c-]2<-[Ir+3]3456(->[O-]C(=O)c7c8ccccc8cc[n]<-37)(->[c-]3cccc(C)c3-[n]<-43...

Обрабатываем строку 615...
   [Строка 615] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! Cc1cc[c-]2<-[Ir+3]3456(->[O-]C(=O)c7c8ccccc8cc[n]<-37)(->[c-]3ccc(C)cc3-[n]<-43c...

Обрабатываем строку 616...
   [Строка 616] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C(C)(C)C)ccc3-c3cc(C)c4ccccc4[n]<-13)->[c-]...

Обрабатываем строку 617...
   [Строка 617] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C(F)(F)F)ccc3-c3cc(C)c4ccccc4[n]<-13)->[c-]...

Обрабатываем строку 618...
   [Строка 618] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(N(C)C)ccc3-c3cc(C)c4ccccc4[n]<-13)->[c-]1cc...

Обрабатываем строку 619...
   [Строка 619] Санитизация не удалась: Explicit valence for atom # 67 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(N(c4ccccc4)c4ccccc4)ccc3-c3cc(C)c4ccccc4[n]...

Обрабатываем строку 620...
   [Строка 620] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccc4ccccc4c3-c3cc(C)c4ccccc4[n]<-13)->[c-]1ccc...

Обрабатываем строку 621...
   [Строка 621] Санитизация не удалась: Explicit valence for atom # 57 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(-c4cc(C)c5ccccc5[n]<-14)c1ccccc1c1ccccc13)->...

Обрабатываем строку 622...
   [Строка 622] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1c(C)c(C)[n]<-25C)->[c-]1ccccc...

Обрабатываем строку 623...
   [Строка 623] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! Cc1c(C)[n]2(C)<-[Ir+3]3456(->[O-]C(=O)c7cc(N(C)C)cc[n]<-37)(->[c-]3ccccc3-c2[n]<...

Обрабатываем строку 624...
   [Строка 624] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1c(C)c(C)[n]<-25-c1ccccc1)->[c...

Обрабатываем строку 625...
   [Строка 625] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! Cc1c(C)[n]2(-c3ccccc3)<-[Ir+3]3456(->[O-]C(=O)c7cc(N(C)C)cc[n]<-37)(->[c-]3ccccc...

Обрабатываем строку 626...
   [Строка 626] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! Cc1c(C)[n]2(-c3ccccc3)<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37)(->[c-]3ccccc3-c2[n]...

Обрабатываем строку 627...
   [Строка 627] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! Cc1c(C)[n]2(-c3ccccc3)<-[Ir+3]345(->[O-]C(=O)CP(c6ccccc6)c6ccccc6)(->[c-]6ccccc6...

Обрабатываем строку 628...
   [Строка 628] Санитизация не удалась: Explicit valence for atom # 13 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(Cl)cc(Cl)c5-c5[n]<-1c(C)c(C)[n]<-25C)->[c...

Обрабатываем строку 629...
   [Строка 629] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1c(C)c(-c1ccccc1)[n]<-25C)->[c...

Обрабатываем строку 630...
   [Строка 630] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1c(C)c(-c1ccccc1)[n]<-25-c1ccc...

Обрабатываем строку 631...
   [Строка 631] Санитизация не удалась: Explicit valence for atom # 2 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1cc(-c1ccccc1)[n]<-25C)->[c-]1...

Обрабатываем строку 632...
   [Строка 632] Санитизация не удалась: Explicit valence for atom # 2 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccccc5-c5[n]<-1cc[n]<-25C)->[c-]1ccccc1-c1[n...

Обрабатываем строку 633...
   [Строка 633] Санитизация не удалась: Explicit valence for atom # 26 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[c-]3ccccc3-c3cccc[n]<-43)->[n]...

Обрабатываем строку 634...
   [Строка 634] Санитизация не удалась: Explicit valence for atom # 26 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[c-]3ccccc3-c3cccc[n]<-43)->[n]...

Обрабатываем строку 635...
   [Строка 635] Санитизация не удалась: Explicit valence for atom # 34 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]345(->[c-]6ccccc6-c6c7ccccc7cc[n]<-36)(->[c-]3ccccc3-c3c6ccccc6cc[...

Обрабатываем строку 636...
   [Строка 636] Санитизация не удалась: Explicit valence for atom # 34 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]345(->[c-]6ccccc6-c6c7ccccc7cc[n]<-36)(->[c-]3ccccc3-c3c6ccccc6cc[...

Обрабатываем строку 637...
   [Строка 637] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4c(C)c(C)cc(C)c4C)cc[n]<-13)->[c...

Обрабатываем строку 638...
   [Строка 638] Санитизация не удалась: Explicit valence for atom # 55 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(C#C[Si](C(C)C)(C(C)C)C(C)C)cc[n]<-...

Обрабатываем строку 639...
   [Строка 639] Санитизация не удалась: Explicit valence for atom # 67 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccc(C#C[Si](C(C)C)(C(C)C)C(C)C)...

Обрабатываем строку 640...
   [Строка 640] Санитизация не удалась: Explicit valence for atom # 69 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccc(C#C[Si](C(C)C)(C(C)C)C(C)C)...

Обрабатываем строку 641...
   [Строка 641] Санитизация не удалась: Explicit valence for atom # 75 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4c(C)c(C)c(C#C[Si](C(C)C)(C(C)C)...

Обрабатываем строку 642...
   [Строка 642] Санитизация не удалась: Explicit valence for atom # 55 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(C#Cc4ccc(C(C)(C)C)cc4)cc[n]<-13)->...

Обрабатываем строку 643...
   [Строка 643] Санитизация не удалась: Explicit valence for atom # 71 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(C#Cc4ccc(C#Cc5ccc(C(C)(C)C)cc5)cc4...

Обрабатываем строку 644...
   [Строка 644] Санитизация не удалась: Explicit valence for atom # 67 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccc(C#Cc5ccc(C(C)(C)C)cc5)cc4)c...

Обрабатываем строку 645...
   [Строка 645] Санитизация не удалась: Explicit valence for atom # 83 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccc(C#Cc5ccc(C#Cc6ccc(C(C)(C)C)...

Обрабатываем строку 646...
   [Строка 646] Санитизация не удалась: Explicit valence for atom # 69 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccc(C#Cc5ccc(C(C)(C)C)cc5)cc4C)...

Обрабатываем строку 647...
   [Строка 647] Санитизация не удалась: Explicit valence for atom # 85 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccc(C#Cc5ccc(C#Cc6ccc(C(C)(C)C)...

Обрабатываем строку 648...
   [Строка 648] Санитизация не удалась: Explicit valence for atom # 75 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4c(C)c(C)c(C#Cc5ccc(C(C)(C)C)cc5...

Обрабатываем строку 649...
   [Строка 649] Санитизация не удалась: Explicit valence for atom # 91 O, 2, is greater than permitted

[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 71 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 91 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 91 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 91 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 13 15 16 17 18 19 20
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 38 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 38 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 44 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 50 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 56 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 40 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 44 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34 45 46
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 32 43 44
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 49 50
[20:59:00] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 49 50
[20:59:00] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[20:59:00] Explicit valence for atom # 32 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 40 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 36 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 20 21 22 23 24 25
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15
[20:59:00] Explicit valence for atom # 48 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 55 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 3 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 46 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 3 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 30 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 32 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 36 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 91 93 94 95 96 97 98
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 95 97 98 99 100 101 102
[20:59:00] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 17 18 19 20 21 22
[20:59:00] Explicit valence for atom # 2 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[20:59:00] Explicit valence for atom # 2 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[20:59:00] Explicit valence for atom # 2 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[20:59:00] Explicit valence for atom # 2 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 56 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 83 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 87 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 46 48 49 50 51 52 54 55 57 58 59 60 61
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 51 N, 4, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 27 29 30 31 32 33 35 36 38 39 40 41 42
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
[20:59:00] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 32 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 9 10 11 12 13 14 16 17 18 19 20 21 22
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 6 7 8 16 17 18 19 20 21
[20:59:00] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted

   [Строка 682] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CN(C)c1cc2ccc[n]3<-[Ir+2]45(->[c-]6ccccc6-c6cccc[n]<-46)(->[c-]4ccccc4-c4cccc[n]...

Обрабатываем строку 683...
   [Строка 683] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
   Успех! Cc1ccc2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(C)ccc1-c1cccc[n]<-31)->[n]1c...

Обрабатываем строку 684...
   [Строка 684] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
   Успех! Cc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(C)ccc1-c1cccc[n]<-31)->[n]1ccc...

Обрабатываем строку 685...
   [Строка 685] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7ccc8ccccc8[n]<-37)(->[n]3ccccc3CN(Cc3cccc[...

Обрабатываем строку 686...
   [Строка 686] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CN(C)c1cc2ccc[n]3<-[Ir+2]45(->[c-]6ccccc6-c6ccc7ccccc7[n]<-46)(->[c-]4ccccc4-c4c...

Обрабатываем строку 687...
   [Строка 687] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! O=Cc1ccc2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(C=O)ccc1-c1cccc[n]<-31)->[...

Обрабатываем строку 688...
   [Строка 688] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! CN(C)c1cc2ccc[n]3<-[Ir+2]45(->[c-]6cc(C=O)ccc6-c6cccc[n]<-46)(->[c-]4cc(C=O)ccc4...

Обрабатываем строку 689...
   [Строка 689] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4ccc5cccc6ccc(c3-c3cccc[n]<-13)c4c56)->[c-]1...

Обрабатываем строку 690...
   [Строка 690] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)cc1ccc4cccc5ccc3c1c45)->[c-]1...

Обрабатываем строку 691...
   [Строка 691] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 692...
   [Строка 692] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 693...
   [Строка 693] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 694...
   [Строка 694] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 695...
   [Строка 695] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1ccc[n]2<-[Ir+3]34(->[O-]C(=O)c12)(->[c-]1ccccc1-c1cccc[n]<-31)->[...

Обрабатываем строку 696...
   [Строка 696] Санитизация не удалась: Explicit valence for atom # 38 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1cc[n]2<-[Ir+3]34(->[O-]C(=O)c2c1)(->[c-]1ccccc1-c1cccc[n]<-31)->[...

Обрабатываем строку 697...
   [Строка 697] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1ccc2C(=O)[O-]<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc...

Обрабатываем строку 698...
   [Строка 698] Санитизация не удалась: Explicit valence for atom # 38 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1cccc2C(=O)[O-]<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3cccc...

Обрабатываем строку 699...
   [Строка 699] Санитизация не удалась: Explicit valence for atom # 44 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1ccc(C#Cc2cc[n]3<-[Ir+3]45(->[O-]C(=O)c3c2)(->[c-]2ccccc2-c2cccc[n...

Обрабатываем строку 700...
   [Строка 700] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1ccc(C#Cc2ccc3C(=O)[O-]<-[Ir+3]45(->[c-]6ccccc6-c6cccc[n]<-46)(->[...

Обрабатываем строку 701...
   [Строка 701] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cc(-c5ccccc5)cc[n]<-24)(->[c-]2ccccc2-c2cc(-c...

Обрабатываем строку 702...
   [Строка 702] Санитизация не удалась: Explicit valence for atom # 50 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1cc[n]2<-[Ir+3]34(->[O-]C(=O)c2c1)(->[c-]1ccccc1-c1cc(-c2ccccc2)cc...

Обрабатываем строку 703...
   [Строка 703] Санитизация не удалась: Explicit valence for atom # 56 O, 2, is greater than permitted
   Успех! CC(C)[Si](C#Cc1ccc(C#Cc2cc[n]3<-[Ir+3]45(->[O-]C(=O)c3c2)(->[c-]2ccccc2-c2cc(-c3...

Обрабатываем строку 704...
   [Строка 704] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 705...
   [Строка 705] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 706...
   [Строка 706] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! Cc1ccccc1-c1cc[n]2<-[Ir+3]34(->[O-]C(=O)c2c1)(->[c-]1ccccc1-c1cccc[n]<-31)->[c-]...

Обрабатываем строку 707...
   [Строка 707] Санитизация не удалась: Explicit valence for atom # 40 O, 2, is greater than permitted
   Успех! Cc1cc(C)c(C)c(-c2cc[n]3<-[Ir+3]45(->[O-]C(=O)c3c2)(->[c-]2ccccc2-c2cccc[n]<-42)-...

Обрабатываем строку 708...
   [Строка 708] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4cc(F)cc(F)c4-c4cccc[n]<-24)(->[c-]2cc(F)cc(F)c2-c2cccc...

Обрабатываем строку 709...
   [Строка 709] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4cc(F)cc(F)c4-c4cccc[n]<-24)(->[c-]2cc(F)cc(F)c2-c2cccc...

Обрабатываем строку 710...
   [Строка 710] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! Cc1ccccc1-c1cc[n]2<-[Ir+3]34(->[O-]C(=O)c2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)...

Обрабатываем строку 711...
   [Строка 711] Санитизация не удалась: Explicit valence for atom # 44 O, 2, is greater than permitted
   Успех! Cc1cc(C)c(C)c(-c2cc[n]3<-[Ir+3]45(->[O-]C(=O)c3c2)(->[c-]2cc(F)cc(F)c2-c2cccc[n]...

Обрабатываем строку 712...
   [Строка 712] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 34 45 46
   Успех! COc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(OC)ccc1-c1cccc[n]<-31)->[n]1c...

Обрабатываем строку 713...
   [Строка 713] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! COc1ccc2-[n]34<-[Ir+2]567(->[c-]2c1)(->[c-]1cc(OC)ccc1-[n]<-51ccc[n]<-61)(->[n]1...

Обрабатываем строку 714...
   [Строка 714] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 27 28 29 30 32 43 44
   Успех! Cc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(C)ccc1-c1cccc[n]<-31)->[n]1c(-...

Обрабатываем строку 715...
   [Строка 715] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 49 50
   Успех! CCCCc1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(CCCC)ccc1-c1cccc[n]<-31)->[...

Обрабатываем строку 716...
   [Строка 716] Санитизация не удалась: Explicit valence for atom # 9 N, 5, is greater than permitted
   Успех! CC(C)(C)c1ccc2-[n]34<-[Ir+2]567(->[c-]2c1)(->[c-]1cc(C(C)(C)C)ccc1-[n]<-51ccc[n]...

Обрабатываем строку 717...
   [Строка 717] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 49 50
   Успех! CC(C)(C)c1ccc2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(C(C)(C)C)ccc1-c1cccc[n]...

Обрабатываем строку 718...
   [Строка 718] Санитизация не удалась: Explicit valence for atom # 17 N, 5, is greater than permitted
   Успех! CC(C)(C)c1ccc2-c3[n]4<-[Ir+2]567(->[c-]2c1)(->[c-]1cc(C(C)(C)C)ccc1-c1[n]<-5c2cc...

Обрабатываем строку 719...
   [Строка 719] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CC1=CB(c2cccc[n]2<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)->[c-]2ccccc2-c2cccc[n]<...

Обрабатываем строку 720...
   [Строка 720] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! CC1=CB(c2cccc[n]2<-[Ir+3]23(->[c-]4cc(F)cc(F)c4-c4cccc[n]<-24)->[c-]2cc(F)cc(F)c...

Обрабатываем строку 721...
   [Строка 721] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17
   Успех! CC1=CB(c2cccc[n]2<-[Ir+3]2345(->[c-]6ccccc6-c6c(C)[n]<-2c2ccccc2[n]<-36)->[c-]2c...

Обрабатываем строку 722...
   [Строка 722] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10
   Успех! c1ccc(-c2c[n]3<-[Ir+2]45(->[c-]6ccccc6-c3o2)(->[c-]2ccccc2-c2oc(-c3ccccc3)c[n]<-...

Обрабатываем строку 723...
   [Строка 723] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5oc(-c6ccccc6)c[n]<-35)(->[c-]3ccccc3-c3oc(-c...

Обрабатываем строку 724...
   [Строка 724] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10
   Успех! O=C(O)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5oc(-c6ccccc6)c[n]<-35)(->[c-]3ccccc3-c3...

Обрабатываем строку 725...
   [Строка 725] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10
   Успех! c1ccc(-c2c[n]3<-[Ir+2]4567(->[c-]8ccccc8-c3o2)(->[c-]2ccccc2-c2oc(-c3ccccc3)c[n]...

Обрабатываем строку 726...
   [Строка 726] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10
   Успех! Cc1cc2c(cc1C)[n]1<-[Ir+2]3456(->[c-]7ccccc7-c7oc(-c8ccccc8)c[n]<-37)(->[c-]3cccc...

Обрабатываем строку 727...
   [Строка 727] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10
   Успех! O=C(O)c1ccc2c(c1)[n]1<-[Ir+2]3456(->[c-]7ccccc7-c7oc(-c8ccccc8)c[n]<-37)(->[c-]3...

Обрабатываем строку 728...
   [Строка 728] Санитизация не удалась: Explicit valence for atom # 32 N, 5, is greater than permitted
   Успех! O=Cc1ccc2-c3cccc[c-]3<-[Ir+3]3(->[c-]4ccccc4-c4ccc(C=O)c[n]<-34)(->[n]2c1)->[n]1...

Обрабатываем строку 729...
   [Строка 729] Санитизация не удалась: Explicit valence for atom # 40 N, 5, is greater than permitted
   Успех! O=Cc1ccc2-c3ccc(C(F)(F)F)c[c-]3<-[Ir+3]3(->[c-]4cc(C(F)(F)F)ccc4-c4ccc(C=O)c[n]<...

Обрабатываем строку 730...
   [Строка 730] Санитизация не удалась: Explicit valence for atom # 36 N, 5, is greater than permitted
   Успех! COc1ccc2-c3ccc(C=O)c[n]3<-[Ir+3]3(->[c-]2c1)(->[c-]1cc(OC)ccc1-c1ccc(C=O)c[n]<-3...

Обрабатываем строку 731...
   [Строка 731] Санитизация не удалась: Explicit valence for atom # 61 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)cc1c4c3Oc3ccccc3B4c3ccccc3O1)...

Обрабатываем строку 732...
   [Строка 732] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 14 15 16 17 18 19
   Успех! CC(C)(C)c1cc[n]2<-[Ir+2]34(->[c-]5c(-c6ccc7ccccc7[n]<-36)sc3ccccc35)(->[c-]3c(-c...

Обрабатываем строку 733...
   [Строка 733] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 20 21 22 23 24 25
   Успех! CC(C)(C)c1cc[n]2<-[Ir+2]34(->[c-]5c(-c6cc(-c7ccccc7)c7ccccc7[n]<-36)sc3ccccc35)(...

Обрабатываем строку 734...
   [Строка 734] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15
   Успех! CC(C)(C)c1cc[n]2<-[Ir+2]34(->[c-]5c(-c6cc(C(F)(F)F)c7ccccc7[n]<-36)sc3ccccc35)(-...

Обрабатываем строку 735...
   [Строка 735] Санитизация не удалась: Explicit valence for atom # 48 N, 5, is greater than permitted
   Успех! COC(=O)c1cc2-c3cccc[c-]3<-[Ir+2]3456(->[c-]7ccccc7-c7cc(C(=O)OC)c8ccccc8[n]<-37)...

Обрабатываем строку 736...
   [Строка 736] Санитизация не удалась: Explicit valence for atom # 55 N, 5, is greater than permitted
   Успех! COC(=O)c1cc2-c3cccc[c-]3<-[Ir+2]3456(->[c-]7ccccc7-c7cc(C(=O)OC)c8ccccc8[n]<-37)...

Обрабатываем строку 737...
   [Строка 737] Санитизация не удалась: Explicit valence for atom # 3 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+5]2345678(->[O-]C(=O)c9cc(-c%10cccc[c-]<-2%10)[n]<-3c2ccccc92)(->[...

Обрабатываем строку 738...
   [Строка 738] Санитизация не удалась: Explicit valence for atom # 46 N, 5, is greater than permitted
   Успех! O=C(O)c1ccc(-[n]23<-[Ir+2]4567(->[c-]8ccccc8-c8cc(C(=O)O)c9ccccc9[n]<-48)(->[c-]...

Обрабатываем строку 739...
   [Строка 739] Санитизация не удалась: Explicit valence for atom # 3 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+5]2345678(->[O-]C(=O)c9cc(-c%10cccc[c-]<-2%10)[n]<-3c2ccccc92)(->[...

Обрабатываем строку 740...
   [Строка 740] Санитизация не удалась: Explicit valence for atom # 6 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-[n]34<-[Ir+2]5678(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-[n]<-51ccc[n]<-61)(-...

Обрабатываем строку 741...
   [Строка 741] Санитизация не удалась: Explicit valence for atom # 30 O, 2, is greater than permitted
   Успех! CC(N)C(=O)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-21...

Обрабатываем строку 742...
   [Строка 742] Санитизация не удалась: Explicit valence for atom # 32 O, 2, is greater than permitted
   Успех! CC(N)C(=O)[O-]<-[Ir+3]12(->[c-]3cc(F)ccc3-c3cccc[n]<-13)->[c-]1cc(F)ccc1-c1cccc[...

Обрабатываем строку 743...
   [Строка 743] Санитизация не удалась: Explicit valence for atom # 36 O, 2, is greater than permitted
   Успех! CC(N)C(=O)[O-]<-[Ir+3]12(->[c-]3c(F)c(F)cc(F)c3-c3cccc[n]<-13)->[c-]1c(F)c(F)cc(...

Обрабатываем строку 744...
   [Строка 744] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 91 93 94 95 96 97 98
   Успех! CCCCCCCCC1(CCCCCCCC)c2cc3-c4ccc5c(ccc6-c7ccc8cc9-c%10cc%11c(cc%10)-c%10ccc(-c%12...

Обрабатываем строку 745...
   [Строка 745] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 95 97 98 99 100 101 102
   Успех! CCCCCCCCC1(CCCCCCCC)c2cc3C#Cc4ccc5c(ccc6-c7ccc8cc9C#Cc%10cc%11c(cc%10)-c%10ccc(-...

Обрабатываем строку 746...
   [Строка 746] Санитизация не удалась: Explicit valence for atom # 17 N, 5, is greater than permitted
   Успех! COc1ccc2c(c1)[n]1(C(C)C)<-[Ir+2]3456(->[c-]7cc(OC)ccc7-c1[n]<-32)(->[c-]1cc(OC)c...

Обрабатываем строку 747...
   [Строка 747] Санитизация не удалась: Explicit valence for atom # 17 N, 5, is greater than permitted
   Успех! COc1ccc2c(c1)[n]1(C(C)C)<-[Ir+2]3456(->[c-]7cc(OC)ccc7-c1[n]<-32)(->[c-]1cc(OC)c...

Обрабатываем строку 748...
   [Строка 748] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! O=C(O)c1ccc2-c3ccc(C(=O)O)c[n]3<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3cc...

Обрабатываем строку 749...
   [Строка 749] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1ccccc1-...

Обрабатываем строку 750...
   [Строка 750] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! CCCCCC[n]12<-[Ir+3]345(->[O-]C(C)=CC(C)=O)(->[c-]6cc1c(cc6-c1ccc(C=O)c[n]<-31)c1...

Обрабатываем строку 751...
   [Строка 751] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 17 18 19 20 21 22
   Успех! Cc1cc2-c3cc(C(F)(F)F)c(Cl)c[c-]3<-[Ir+2]34(->[c-]5cc(Cl)c(C(F)(F)F)cc5-c5cc(C)c6...

Обрабатываем строку 752...
   [Строка 752] Санитизация не удалась: Explicit valence for atom # 2 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]3456789%10(->[c-]%11cc(F)cc(F)c%11-c([n]<-3[n]<-41)[n]<-52)(->[c-]...

Обрабатываем строку 753...
   [Строка 753] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
   Успех! CN1N=C(c2cccc[c-]2<-[Ir+2]2(->[c-]3ccccc3C3=NN(C)NN3)->[n]3ccccc3-c3cccc[n]<-23)...

Обрабатываем строку 754...
   [Строка 754] Санитизация не удалась: Explicit valence for atom # 2 N, 5, is greater than permitted
   Успех! CC(C)(C)c1cc[n]2<-[Ir+2]3456789%10(->[c-]%11cc(F)cc(F)c%11-c%11[n]<-3[n]<-4[n]<-...

Обрабатываем строку 755...
   [Строка 755] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
   Успех! CN1N=C(c2cccc[c-]2<-[Ir+2]2(->[c-]3ccccc3C3=NN(C)NN3)->[n]3ccc(C(C)(C)C)cc3-c3cc...

Обрабатываем строку 756...
   [Строка 756] Санитизация не удалась: Explicit valence for atom # 2 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]3456789%10(->[c-]%11cc(F)cc(F)c%11-c([n]<-3[n]<-41)[n]<-52)(->[c-]...

Обрабатываем строку 757...
   [Строка 757] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
   Успех! CN1N=C(c2cccc[c-]2<-[Ir+2]2(->[c-]3ccccc3C3=NN(C)NN3)->[n]3cccc4ccc5ccc[n]<-2c5c...

Обрабатываем строку 758...
   [Строка 758] Санитизация не удалась: Explicit valence for atom # 2 N, 5, is greater than permitted
   Успех! CN(C)c1cc[n]2<-[Ir+2]3456789%10(->[c-]%11cc(F)cc(F)c%11-c%11[n]<-3[n]<-4[n]<-5(C...

Обрабатываем строку 759...
   [Строка 759] Санитизация не удалась: Explicit valence for atom # 55 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)sc1c3P(=O)(c3ccccc3)c3ccsc3-1...

Обрабатываем строку 760...
   [Строка 760] Санитизация не удалась: Explicit valence for atom # 56 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(N(c4ccccc4)c4ccccc4)ccc3-c3cccc[n]<-13)->[c...

Обрабатываем строку 761...
   [Строка 761] Санитизация не удалась: Explicit valence for atom # 28 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]123(->[c-]4cc(-[n]<-15c1ccccc1c1ccccc15)ccc4-c1cccc[n]<-...

Обрабатываем строку 762...
   [Строка 762] Санитизация не удалась: Explicit valence for atom # 83 O, 2, is greater than permitted
   Успех! CCCCCCCCc1ccc2c3ccc(CCCCCCCC)[c-]4<-[Ir+3]567(->[O-]C(C)=CC(C)=O)(->[c-]8c(CCCCC...

Обрабатываем строку 763...
   [Строка 763] Санитизация не удалась: Explicit valence for atom # 87 O, 2, is greater than permitted
   Успех! CCCCCCCCOc1ccc2c3ccc(OCCCCCCCC)[c-]4<-[Ir+3]567(->[O-]C(C)=CC(C)=O)(->[c-]8c(OCC...

Обрабатываем строку 764...
   [Строка 764] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 46 48 49 50 51 52 54 55 57 58 59 60 61
   Успех! Cc1c2-c3cccc[c-]3<-[Ir+2]345678(->[c-]9ccccc9-c9c(C)[n]<-3c3cc(F)c(F)cc3[n]<-49)...

Обрабатываем строку 765...
   [Строка 765] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCOC(=O)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3-c3cc...

Обрабатываем строку 766...
   [Строка 766] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! O=C(OCCOCCOCCOCCO)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3c...

Обрабатываем строку 767...
   [Строка 767] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! O=C(OCCOCCOCCOCCOCCOCCOCCOCCOCCO)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n...

Обрабатываем строку 768...
   [Строка 768] Санитизация не удалась: Explicit valence for atom # 51 N, 4, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]345(->[c-]6c(-c2c1)cc(C(F)(F)F)cc6C(F)(F)F)(->[c-]1c(-c2cc(C)cc...

Обрабатываем строку 769...
   [Строка 769] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 27 29 30 31 32 33 35 36 38 39 40 41 42
   Успех! C(=Cc1[n]2<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[c-]3ccccc3-c3cccc[n]<-43)...

Обрабатываем строку 770...
   [Строка 770] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=[N+]1[O-]<-[Ir+2]23456(->[c-]7ccccc7-c7cccc[n]<-27)(->[c-]2ccccc2-c2cccc[n]<-3...

Обрабатываем строку 771...
   [Строка 771] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
   Успех! COc1ccc(C=Cc2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[...

Обрабатываем строку 772...

[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 48 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 48 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 48 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 48 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 48 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 45 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 48 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 36 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 33 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 33 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 33 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 33 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 42 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 42 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 31 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 31 N, 4, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[20:59:00] Explicit valence for atom # 42 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 47 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 47 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 21 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 21 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 30 53 54
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 30 53 54
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 61 62
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 61 62
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 39 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 47 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 42 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 42 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 61 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 57 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 67 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 63 N, 4, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 45 46 47
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 45 46 47
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 45 47 48
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 45 47 48
[20:59:00] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 73 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 66 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 67 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 78 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 36 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 50 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 19 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 29 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 29 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36 37 38 39 40
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36 37 38 39 40
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37 38
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37 38
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 32 44 45 46 47
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 32 44 45 46 47
[20:59:00] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 24 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 24 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 24 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 77 N, 5, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Explicit valence for atom # 63 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 63 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 63 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 63 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 72 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 72 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 72 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 72 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 69 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 69 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 69 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 69 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 79 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 79 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 79 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 79 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 30 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 41 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 37 O, 2, is greater than permitted

   Успех! CCCC[n]12<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 830...
   [Строка 830] Санитизация не удалась: Explicit valence for atom # 29 N, 5, is greater than permitted
   Успех! CCCC[n]12<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 831...
   [Строка 831] Санитизация не удалась: Explicit valence for atom # 29 N, 5, is greater than permitted
   Успех! CCCC[n]12<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 832...
   [Строка 832] Санитизация не удалась: Explicit valence for atom # 29 N, 5, is greater than permitted
   Успех! CCCC[n]12<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 833...
   [Строка 833] Санитизация не удалась: Explicit valence for atom # 33 N, 4, is greater than permitted
   Успех! C1=CC(=C2c3ccc(-c4cccc5c4[n]4<-[Ir+3]67(->[c-]8ccccc8-c8cccc[n]<-68)(->[c-]6cccc...

Обрабатываем строку 834...
   [Строка 834] Санитизация не удалась: Explicit valence for atom # 33 N, 4, is greater than permitted
   Успех! C1=CC(=C2c3ccc(-c4cccc5c4[n]4<-[Ir+3]67(->[c-]8ccccc8-c8cccc[n]<-68)(->[c-]6cccc...

Обрабатываем строку 835...
   [Строка 835] Санитизация не удалась: Explicit valence for atom # 42 N, 4, is greater than permitted
   Успех! Fc1c(F)c(F)c(C(=C2C=CC=N2)c2ccc[n-]2<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)->[c-...

Обрабатываем строку 836...
   [Строка 836] Санитизация не удалась: Explicit valence for atom # 42 N, 4, is greater than permitted
   Успех! Fc1c(F)c(F)c(C(=C2C=CC=N2)c2ccc[n-]2<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)->[c-...

Обрабатываем строку 837...
   [Строка 837] Санитизация не удалась: Explicit valence for atom # 50 N, 4, is greater than permitted
   Успех! CC(=O)OCC1OC(Sc2c(F)c(F)c(C(=C3C=CC=N3)c3ccc[n-]3<-[Ir+3]34(->[c-]5ccccc5-c5cccc...

Обрабатываем строку 838...
   [Строка 838] Санитизация не удалась: Explicit valence for atom # 50 N, 4, is greater than permitted
   Успех! CC(=O)OCC1OC(Sc2c(F)c(F)c(C(=C3C=CC=N3)c3ccc[n-]3<-[Ir+3]34(->[c-]5ccccc5-c5cccc...

Обрабатываем строку 839...
   [Строка 839] Санитизация не удалась: Explicit valence for atom # 31 N, 4, is greater than permitted
   Успех! CC1=NC(=C(c2c(F)c(F)c(F)c(F)c2F)c2c(C)c(I)c(C)[n-]2<-[Ir+3]23(->[c-]4ccccc4-c4cc...

Обрабатываем строку 840...
   [Строка 840] Санитизация не удалась: Explicit valence for atom # 31 N, 4, is greater than permitted
   Успех! CC1=NC(=C(c2c(F)c(F)c(F)c(F)c2F)c2c(C)c(I)c(C)[n-]2<-[Ir+3]23(->[c-]4ccccc4-c4cc...

Обрабатываем строку 841...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 842...
   [Строка 842] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]456789%10%11(->[c-]%12ccccc%12-c%12[n]<-4[n]<-5c(-c4ccccc...

Обрабатываем строку 843...
   [Строка 843] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2[n]3<-[Ir+2]456789%10%11(->[c-]%12ccccc%12-c([n]<-43)[n]<-5[n]<-62)(->[...

Обрабатываем строку 844...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 845...
   [Строка 845] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]456789%10%11(->[c-]%12ccccc%12-c%12[n]<-4[n]<-5c(-c4ccccc...

Обрабатываем строку 846...
   [Строка 846] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2[n]3<-[Ir+2]456789%10%11(->[c-]%12ccccc%12-c([n]<-43)[n]<-5[n]<-62)(->[...

Обрабатываем строку 847...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 848...
   [Строка 848] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]456789%10%11(->[c-]%12ccccc%12-c%12[n]<-4[n]<-5c(-c4ccccc...

Обрабатываем строку 849...
   [Строка 849] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2[n]3<-[Ir+2]456789%10%11(->[c-]%12ccccc%12-c([n]<-43)[n]<-5[n]<-62)(->[...

Обрабатываем строку 850...
   [Строка 850] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+4]234567(->[O-]C(=O)c8ccc[n]<-2c8-c2c1ccc[n]<-32)(->[c-]1ccccc1-[n...

Обрабатываем строку 851...
   [Строка 851] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! O=C1[O-]<-[Ir+4]234567(->[O-]C(=O)c8cc(-c9cc1c1ccccc1[n]<-29)[n]<-3c1ccccc81)(->...

Обрабатываем строку 852...
   [Строка 852] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
   Успех! Cc1ccc2-c3cccc[n]3<-[Ir+2]345(->[c-]2c1)(->[c-]1cc(C)ccc1-c1cccc[n]<-31)->[n]1cc...

Обрабатываем строку 853...
   [Строка 853] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
   Успех! Cc1ccc2-c3cccc[n]3<-[Ir+2]345(->[c-]2c1)(->[c-]1cc(C)ccc1-c1cccc[n]<-31)->[n]1cc...

Обрабатываем строку 854...
   [Строка 854] Санитизация не удалась: Explicit valence for atom # 42 O, 2, is greater than permitted
   Успех! CCCCCCOc1ccc[n]2<-[Ir+3]34(->[O-]C(=O)c12)(->[c-]1ccccc1-c1cc(C)cc[n]<-31)->[c-]...

Обрабатываем строку 855...
   [Строка 855] Санитизация не удалась: Explicit valence for atom # 47 N, 5, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]345(->[O-]C(=O)c6c(OCCCCCC[n]<-37c3ccc(C(C)(C)C)cc3c3cc(C(C)(C)...

Обрабатываем строку 856...
   [Строка 856] Санитизация не удалась: Explicit valence for atom # 47 N, 5, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]34567(->[O-]C(=O)c8c(OCCCCCC[n]<-39c3ccc(-[n]<-4%10c4ccc(C(C)(C...

Обрабатываем строку 857...
   [Строка 857] Санитизация не удалась: Explicit valence for atom # 47 N, 5, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]3456789%10%11(->[O-]C(=O)c%12c(OCCCCCC[n]<-3%13c3ccc(-[n]<-4%14...

Обрабатываем строку 858...
   [Строка 858] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5ccc6c7ccccc7[n]<-1(-c1ccccc1)c6c5-c1ccc...

Обрабатываем строку 859...
   [Строка 859] Санитизация не удалась: Explicit valence for atom # 21 N, 5, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5ccc6c7ccccc7[n]<-1(-c1ccccc1)c6c5-c1cc(...

Обрабатываем строку 860...
   [Строка 860] Санитизация не удалась: Explicit valence for atom # 21 N, 5, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5ccc6c7ccccc7[n]<-1(-c1ccccc1)c6c5-c1cc(...

Обрабатываем строку 861...
   [Строка 861] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 30 53 54
   Успех! c1cc[c-]2<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[n]3ccccc3-c2c1)->[n]1ccc...

Обрабатываем строку 862...
   [Строка 862] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 30 53 54
   Успех! c1cc[c-]2<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[n]3ccccc3-c2c1)->[n]1ccc...

Обрабатываем строку 863...
   [Строка 863] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 61 62
   Успех! c1cc[c-]2<-[Ir+2]345678(->[c-]9ccccc9-c9ccc%10ccccc%10[n]<-39)(->[n]3ccc(-c9[n]<...

Обрабатываем строку 864...
   [Строка 864] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 34 35 36 38 61 62
   Успех! c1cc[c-]2<-[Ir+2]345678(->[c-]9ccccc9-c9ccc%10ccccc%10[n]<-39)(->[n]3ccc(-c9[n]<...

Обрабатываем строку 865...
   [Строка 865] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! c1cc[n]2<-[Ir+2]345678(->[c-]9ccsc9-c2c1)(->[c-]1ccsc1-c1cccc[n]<-31)->[n]1ccc(-...

Обрабатываем строку 866...
   [Строка 866] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! c1cc[n]2<-[Ir+2]345678(->[c-]9ccsc9-c2c1)(->[c-]1ccsc1-c1cccc[n]<-31)->[n]1ccc(-...

Обрабатываем строку 867...
   [Строка 867] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! O=P1([S-])c2cccc[n]2<-[Ir+3]23(->[c-]4cc(F)cc(F)c4-c4cccc[n]<-24)(->[c-]2cc(F)cc...

Обрабатываем строку 868...
   [Строка 868] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc(C(F)(F)F)ccc4[n]<-13)->[c-]1cc...

Обрабатываем строку 869...
   [Строка 869] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc(C(F)(F)F)ccc4[n]<-13)->[c...

Обрабатываем строку 870...
   [Строка 870] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc(F)ccc4[n]<-13)->[c-]1ccccc1-c1...

Обрабатываем строку 871...
   [Строка 871] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc(F)ccc4[n]<-13)->[c-]1cccc...

Обрабатываем строку 872...
   [Строка 872] Санитизация не удалась: Explicit valence for atom # 39 N, 5, is greater than permitted
   Успех! c1ccc(-c2oc3-c4cccc[c-]4<-[Ir+2]45678(->[c-]9ccccc9-c9oc(-c%10ccccc%10)[n]<-4[n]...

Обрабатываем строку 873...
   [Строка 873] Санитизация не удалась: Explicit valence for atom # 47 N, 5, is greater than permitted
   Успех! c1ccc(-c2oc3-c4cccc[c-]4<-[Ir+2]456789(->[c-]%10ccccc%10-c%10oc(-c%11ccccc%11)[n...

Обрабатываем строку 874...
   [Строка 874] Санитизация не удалась: Explicit valence for atom # 42 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)-...

Обрабатываем строку 875...
   [Строка 875] Санитизация не удалась: Explicit valence for atom # 42 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)-...

Обрабатываем строку 876...
   [Строка 876] Санитизация не удалась: Explicit valence for atom # 61 N, 4, is greater than permitted
   Успех! Cc1ccc2c(c1)c(-c1ccccc1)cc1-c3ccc(F)c[c-]3<-[Ir+3]345(->[c-]6cc(F)ccc6-c6cc(-c7c...

Обрабатываем строку 877...
   [Строка 877] Санитизация не удалась: Explicit valence for atom # 57 N, 4, is greater than permitted
   Успех! Cc1ccc2c(c1)c(-c1ccccc1)cc1-c3ccc(F)c[c-]3<-[Ir+3]34567(->[c-]8cc(F)ccc8-c8cc(-c...

Обрабатываем строку 878...
   [Строка 878] Санитизация не удалась: Explicit valence for atom # 67 N, 4, is greater than permitted
   Успех! Cc1ccc2c(c1)c(-c1ccccc1)cc1-c3ccc(C(F)(F)F)c[c-]3<-[Ir+3]345(->[c-]6cc(C(F)(F)F)...

Обрабатываем строку 879...
   [Строка 879] Санитизация не удалась: Explicit valence for atom # 63 N, 4, is greater than permitted
   Успех! Cc1ccc2c(c1)c(-c1ccccc1)cc1-c3ccc(C(F)(F)F)c[c-]3<-[Ir+3]34567(->[c-]8cc(C(F)(F)...

Обрабатываем строку 880...
   [Строка 880] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 45 46 47
   Успех! FC(F)(F)c1ccc2-c3c4ccccc4cc[n]3<-[Ir+2]345(->[c-]2c1)(->[c-]1cc(C(F)(F)F)ccc1-c1...

Обрабатываем строку 881...
   [Строка 881] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 45 46 47
   Успех! FC(F)(F)c1ccc2-c3c4ccccc4cc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(C(F)(F)F)ccc1-c...

Обрабатываем строку 882...
   [Строка 882] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 45 47 48
   Успех! FC(F)(F)c1ccc2-c3c4ccccc4cc[n]3<-[Ir+2]345(->[c-]2c1)(->[c-]1cc(C(F)(F)F)ccc1-c1...

Обрабатываем строку 883...
   [Строка 883] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 45 47 48
   Успех! FC(F)(F)c1ccc2-c3c4ccccc4cc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(C(F)(F)F)ccc1-c...

Обрабатываем строку 884...
   [Строка 884] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-...

Обрабатываем строку 885...
   [Строка 885] Санитизация не удалась: Explicit valence for atom # 73 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(-c4cc5c6c(c4)Oc4ccccc4N6c4ccccc4O5)ccc3-c3c...

Обрабатываем строку 886...
   [Строка 886] Санитизация не удалась: Explicit valence for atom # 37 N, 5, is greater than permitted
   Успех! COc1cc[n]2<-[Ir+2]345(->[c-]6ccccc6-c2c1)(->[c-]1ccccc1-c1cc(OC)cc[n]<-31)->[n]1...

Обрабатываем строку 887...
   [Строка 887] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccc(-c4cc(C)cc(C)c4)cc3-c3cc(C)cc[n]<-13)->[c-...

Обрабатываем строку 888...
   [Строка 888] Санитизация не удалась: Explicit valence for atom # 55 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cc(C(F)(F)F)ccc6-c6ccc(-c7ccc(C(F)(F)F)cc7)[n]<-2[n]...

Обрабатываем строку 889...
   [Строка 889] Санитизация не удалась: Explicit valence for atom # 66 N, 4, is greater than permitted
   Успех! FC(F)(F)c1ccc(-c2ccc3-c4ccc(C(F)(F)F)c[c-]4<-[Ir+3]45678(->[c-]9cc(C(F)(F)F)ccc9...

Обрабатываем строку 890...
   [Строка 890] Санитизация не удалась: Explicit valence for atom # 67 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cc(C(F)(F)F)ccc6-c6c7c(c(-c8ccc(C(F)(F)F)cc8)[n]<-2[...

Обрабатываем строку 891...
   [Строка 891] Санитизация не удалась: Explicit valence for atom # 78 N, 4, is greater than permitted
   Успех! FC(F)(F)c1ccc(-c2c3c(c4-c5ccc(C(F)(F)F)c[c-]5<-[Ir+3]56789(->[c-]%10cc(C(F)(F)F)...

Обрабатываем строку 892...
   [Строка 892] Санитизация не удалась: Explicit valence for atom # 28 O, 2, is greater than permitted
   Успех! CC(N)C(=O)[O-]<-[Ir+3]12(->[c-]3ccsc3-c3cccc[n]<-13)->[c-]1ccsc1-c1cccc[n]<-21...

Обрабатываем строку 893...
   [Строка 893] Санитизация не удалась: Explicit valence for atom # 36 O, 2, is greater than permitted
   Успех! CC(N)C(=O)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)sc1ccccc13)->[c-]1c(-c3cccc[n]<...

Обрабатываем строку 894...
   [Строка 894] Санитизация не удалась: Explicit valence for atom # 50 O, 2, is greater than permitted
   Успех! CCC(CC)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5ccc6c(oc7c6ccc(C)[n]<-17)c5-c1cccc[n]<-2...

Обрабатываем строку 895...
   [Строка 895] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! Cc1ccc2c3cc[c-]4<-[Ir+3]567(->[O-]C(=CC(=O)C(C)(C)C)C(C)(C)C)(->[c-]8ccc9c(oc%10...

Обрабатываем строку 896...
   [Строка 896] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc6c(oc7c6ccc(C)[n]<-17)c5-c1cccc[n]<-21)->...

Обрабатываем строку 897...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 898...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 899...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 900...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 901...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 902...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 903...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 904...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 905...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 906...
   [Строка 906] Санитизация не удалась: Explicit valence for atom # 19 N, 5, is greater than permitted
   Успех! FC(F)(F)c1[n]2<-[Ir+3]345678(->[c-]9ccc%10ccccc%10c9-c9[n]<-3c3ccccc3[n]<-49-c3c...

Обрабатываем строку 907...
   [Строка 907] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! FC(F)(F)c1[n]2<-[Ir+3]345678(->[c-]9c(-c%10[n]<-3c3ccccc3[n]<-4%10-c3ccccc3)ccc3...

Обрабатываем строку 908...
   [Строка 908] Санитизация не удалась: Explicit valence for atom # 29 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccsc5-c5[n]<-1ccc[n]<-25)->[c-]1ccsc1-c1[n]<...

Обрабатываем строку 909...
   [Строка 909] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5c(-c6[n]<-1ccc[n]<-26)sc1ccccc15)->[c-]1c(-c...

Обрабатываем строку 910...
   [Строка 910] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccsc3-c3cc(C(F)(F)F)cc[n]<-13)->[c-]1ccsc1-c1c...

Обрабатываем строку 911...
   [Строка 911] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(-c4cc(C(F)(F)F)cc[n]<-14)sc1ccccc13)->[c-]1c...

Обрабатываем строку 912...
   [Строка 912] Санитизация не удалась: Explicit valence for atom # 29 O, 2, is greater than permitted
   Успех! c1ccc(-c2oc3N=P([O-]<-[Ir+3]456(->[c-]7cccc8ccc9ccc[n]<-4c9c87)(->[c-]4cccc7ccc8...

Обрабатываем строку 913...
   [Строка 913] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! c1ccc(-c2oc3N=P([O-]<-[Ir+3]456(->[c-]7ccccc7-c7ccc8ccccc8[n]<-47)(->[c-]4ccccc4...

Обрабатываем строку 914...
   [Строка 914] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! c1ccc(-c2oc3N=P([O-]<-[Ir+3]456(->[c-]7ccccc7-c7c8ccccc8cc[n]<-47)(->[c-]4ccccc4...

Обрабатываем строку 915...
   [Строка 915] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1ccccc1...

Обрабатываем строку 916...
   [Строка 916] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1ccccc1...

Обрабатываем строку 917...
   [Строка 917] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36 37 38 39 40
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1ccccc1...

Обрабатываем строку 918...
   [Строка 918] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 36 37 38 39 40
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1ccccc1...

Обрабатываем строку 919...
   [Строка 919] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37 38
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1c(-c2[...

Обрабатываем строку 920...
   [Строка 920] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37 38
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1c(-c2[...

Обрабатываем строку 921...
   [Строка 921] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 32 44 45 46 47
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1c(-c2[...

Обрабатываем строку 922...
   [Строка 922] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 29 30 32 44 45 46 47
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1c(-c2[...

Обрабатываем строку 923...
   [Строка 923] Санитизация не удалась: Explicit valence for atom # 26 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[c-]3ccccc3-c3cccc[n]<-43)->[n...

Обрабатываем строку 924...
   [Строка 924] Санитизация не удалась: Explicit valence for atom # 26 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[c-]3ccccc3-c3cccc[n]<-43)->[n...

Обрабатываем строку 925...
   [Строка 925] Санитизация не удалась: Explicit valence for atom # 26 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[c-]3ccccc3-c3cccc[n]<-43)->[n...

Обрабатываем строку 926...
   [Строка 926] Санитизация не удалась: Explicit valence for atom # 24 N, 5, is greater than permitted
   Успех! C[n]12<-[Ir+2]3456(->[c-]7ccsc7-c7cccc[n]<-37)(->[c-]3ccsc3-c3cccc[n]<-43)->[n](...

Обрабатываем строку 927...

[20:59:00] Explicit valence for atom # 43 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 43 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 35 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 35 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 32 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 32 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 35 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 35 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 34 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 28 N, 4, is greater than permitted
[20:59:00] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 6 14
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 6 17
[20:59:00] Explicit valence for atom # 42 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 48 N, 5, is greater than permitted
[20:59:00] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 37 38 40 41 42 43 44
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 40 42 43 44 45 46 48 49 51 52 53 54 55
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 25 26 28 29 30 31 33 41 42 43 44 45 47
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37 39 40 42 43 44 45 46
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 36 38 39 40 41 42 44 45 47 48 49 50 51
[20:59:00] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 57 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 37 38 40 41 42 43 44
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 37 38 40 41 42 43 44
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
[20:59:00] Explicit valence for atom # 73 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 81 O, 2, is greater than permitted
[20:59:00] Explicit valence for atom # 81 O, 2, is greater than permitted
[20:59:00] Can't kekulize mol.  Unkekulized atoms: 3 4 6 15 16
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 17 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 15
[20:59:01] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 30 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 31 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 31 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 38 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 46 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 8 N, 6, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 14 16 17 18 19
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 13 15 16 17 18 19 20
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 26 28 29 30 31 32 33
[20:59:01] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 7 8 9 11 18
[20:59:01] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 33 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 93 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 93 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 93 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 93 O, 2, is greater than permitted

   [Строка 985] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! CCCC(CCC)C(=O)OCc1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(...

Обрабатываем строку 986...
   [Строка 986] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! CCCC(CCC)C(=O)OCc1cc[n]2<-[Ir+2]34(->[c-]5ccsc5-c5cccc[n]<-35)(->[c-]3ccsc3-c3cc...

Обрабатываем строку 987...
   [Строка 987] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! CCCC(CCC)C(=O)OCc1cc[n]2<-[Ir+2]34(->[c-]5ccsc5-c5cccc[n]<-35)(->[c-]3ccsc3-c3cc...

Обрабатываем строку 988...
   [Строка 988] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! CCCC(CCC)C(=O)OCc1cc[n]2<-[Ir+2]34(->[c-]5ccsc5-c5cccc[n]<-35)(->[c-]3ccsc3-c3cc...

Обрабатываем строку 989...
   [Строка 989] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 990...
   [Строка 990] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 991...
   [Строка 991] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 992...
   [Строка 992] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c3-c3ccc...

Обрабатываем строку 993...
   [Строка 993] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c3-c3ccc...

Обрабатываем строку 994...
   [Строка 994] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c3-c3ccc...

Обрабатываем строку 995...
   [Строка 995] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccsc5-c5cccc[n]<-35)(->[c-]3ccsc3-c3cccc[n]<-43)->[n]...

Обрабатываем строку 996...
   [Строка 996] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccsc5-c5cccc[n]<-35)(->[c-]3ccsc3-c3cccc[n]<-43)->[n]...

Обрабатываем строку 997...
   [Строка 997] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccsc5-c5cccc[n]<-35)(->[c-]3ccsc3-c3cccc[n]<-43)->[n]...

Обрабатываем строку 998...
   [Строка 998] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 6 14
   Успех! COc1c2-c3cc(C)cc[n]3<-[Ir+2]345678(->[c-]2[n]<-3c(OC)[n]<-41)(->[c-]1c(-c2cc(C)c...

Обрабатываем строку 999...
   [Строка 999] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 6 17
   Успех! COc1c2-c3ccc(C(F)(F)F)c[n]3<-[Ir+2]345678(->[c-]2[n]<-3c(OC)[n]<-41)(->[c-]1c(-c...

Обрабатываем строку 1000...
   [Строка 1000] Санитизация не удалась: Explicit valence for atom # 42 N, 5, is greater than permitted
   Успех! COc1c2-c3cc(C)cc[n]3<-[Ir+2]3456789%10(->[c-]2[n]<-3c(OC)[n]<-41)(->[c-]1c(-c2cc...

Обрабатываем строку 1001...
   [Строка 1001] Санитизация не удалась: Explicit valence for atom # 48 N, 5, is greater than permitted
   Успех! COc1c2-c3ccc(C(F)(F)F)c[n]3<-[Ir+2]3456789%10(->[c-]2[n]<-3c(OC)[n]<-41)(->[c-]1...

Обрабатываем строку 1002...
   [Строка 1002] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=[N+]1[O-]<-[Ir+2]2345(->[c-]6ccccc6-c6cccc[n]<-26)(->[c-]2ccccc2-c2cccc[n]<-32...

Обрабатываем строку 1003...
   [Строка 1003] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! Brc1ccc(-c2oc3c4ccc[n]5<-[Ir+2]678(->[c-]9ccccc9-c9cccc[n]<-69)(->[c-]6ccccc6-c6...

Обрабатываем строку 1004...
   [Строка 1004] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 37 38 40 41 42 43 44
   Успех! c1ccc(-c2oc3c4ccc[n]5<-[Ir+2]678(->[c-]9ccccc9-c9cccc[n]<-69)(->[c-]6ccccc6-c6cc...

Обрабатываем строку 1005...
   [Строка 1005] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 40 42 43 44 45 46 48 49 51 52 53 54 55
   Успех! c1ccc(N(c2ccccc2)c2ccc(-c3oc4c5ccc[n]6<-[Ir+2]789(->[c-]%10ccccc%10-c%10cccc[n]<...

Обрабатываем строку 1006...
   [Строка 1006] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! Nc1ccc(-c2oc3c4ccc[n]5<-[Ir+2]678(->[c-]9ccccc9-c9cccc[n]<-69)(->[c-]6ccccc6-c6c...

Обрабатываем строку 1007...
   [Строка 1007] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 25 26 28 29 30 31 33 41 42 43 44 45 47
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[n]3ccc(-c7oc8c9ccc[n]<-4c9...

Обрабатываем строку 1008...
   [Строка 1008] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1cccc2c...

Обрабатываем строку 1009...
   [Строка 1009] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 31 33 34 35 36 37 39 40 42 43 44 45 46
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1cccc2c...

Обрабатываем строку 1010...
   [Строка 1010] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1cccc2c...

Обрабатываем строку 1011...
   [Строка 1011] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1cccc2c...

Обрабатываем строку 1012...
   [Строка 1012] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 36 38 39 40 41 42 44 45 47 48 49 50 51
   Успех! c1cc[c-]2<-[Ir+2]345(->[c-]6ccccc6-c6cccc[n]<-36)(->[n]3ccccc3-c2c1)->[n]1cccc2c...

Обрабатываем строку 1013...
   [Строка 1013] Санитизация не удалась: Explicit valence for atom # 49 O, 2, is greater than permitted
   Успех! O=P(N=P([O-]<-[Ir+3]1234(->[c-]5ccccc5-c5c(-c6ccccc6)[n]<-1c1ccccc1[n]<-25)->[c-...

Обрабатываем строку 1014...
   [Строка 1014] Санитизация не удалась: Explicit valence for atom # 53 O, 2, is greater than permitted
   Успех! O=P(N=P([O-]<-[Ir+3]1234(->[c-]5ccccc5-c5c(-c6ccccc6)[n]<-1c1cc(F)c(F)cc1[n]<-25...

Обрабатываем строку 1015...
   [Строка 1015] Санитизация не удалась: Explicit valence for atom # 53 O, 2, is greater than permitted
   Успех! O=P(N=P([O-]<-[Ir+3]1234(->[c-]5cc(F)ccc5-c5c(-c6ccc(F)cc6)[n]<-1c1ccccc1[n]<-25...

Обрабатываем строку 1016...
   [Строка 1016] Санитизация не удалась: Explicit valence for atom # 57 O, 2, is greater than permitted
   Успех! O=P(N=P([O-]<-[Ir+3]1234(->[c-]5cc(F)ccc5-c5c(-c6ccc(F)cc6)[n]<-1c1cc(F)c(F)cc1[...

Обрабатываем строку 1017...
   [Строка 1017] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 37 38 40 41 42 43 44
   Успех! c1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]<-...

Обрабатываем строку 1018...
   [Строка 1018] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! Cc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]<...

Обрабатываем строку 1019...
   [Строка 1019] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! Fc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]<...

Обрабатываем строку 1020...
   [Строка 1020] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)-...

Обрабатываем строку 1021...
   [Строка 1021] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
   Успех! Cc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8cc(F)cc(F)c8-c8cccc[n]<-48)(->[c-]4cc(F)cc(F)c...

Обрабатываем строку 1022...
   [Строка 1022] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
   Успех! Fc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8cc(F)cc(F)c8-c8cccc[n]<-48)(->[c-]4cc(F)cc(F)c...

Обрабатываем строку 1023...
   [Строка 1023] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 31 32 33 34 35 37 38 40 41 42 43 44
   Успех! c1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]<-...

Обрабатываем строку 1024...
   [Строка 1024] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! Cc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]<...

Обрабатываем строку 1025...
   [Строка 1025] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! Fc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]<...

Обрабатываем строку 1026...
   [Строка 1026] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 41 42 44 45 46 47 48
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)-...

Обрабатываем строку 1027...
   [Строка 1027] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
   Успех! Cc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8cc(F)cc(F)c8-c8cccc[n]<-48)(->[c-]4cc(F)cc(F)c...

Обрабатываем строку 1028...
   [Строка 1028] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
   Успех! Fc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8cc(F)cc(F)c8-c8cccc[n]<-48)(->[c-]4cc(F)cc(F)c...

Обрабатываем строку 1029...
   [Строка 1029] Санитизация не удалась: Explicit valence for atom # 73 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3ccccc3-c3c(-c4ccc(C(F)(F)F)cc4)c(-c4ccccc...

Обрабатываем строку 1030...
   [Строка 1030] Санитизация не удалась: Explicit valence for atom # 81 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc(C(F)(F)F)ccc3-c3c(-c4ccc(C(F)(F)F)cc4)...

Обрабатываем строку 1031...
   [Строка 1031] Санитизация не удалась: Explicit valence for atom # 81 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc(C(C)(C)C)ccc3-c3c(-c4ccc(C(F)(F)F)cc4)...

Обрабатываем строку 1032...
   [Строка 1032] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 15 16
   Успех! Nc1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5ccc(C=O)c[n]<-35)(->[c-]3cc(C=O)ccc3-c3...

Обрабатываем строку 1033...
   [Строка 1033] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 17 18
   Успех! Nc1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5ccc(C(F)(F)F)c[n]<-35)(->[c-]3cc(C=O)cc...

Обрабатываем строку 1034...
   [Строка 1034] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 15
   Успех! Cc1ccc2-c3ccc(C=O)c[c-]3<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5ccc(C)c[n]<-35)(->[n]2c1...

Обрабатываем строку 1035...
   [Строка 1035] Санитизация не удалась: Explicit valence for atom # 7 N, 5, is greater than permitted
   Успех! C1=N[O-]<-[Ir+3]2345(->[c-]6ccccc6-[n]<-26ccc[n]<-36)(->[c-]2ccccc2-[n]<-42ccc[n...

Обрабатываем строку 1036...
   [Строка 1036] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! C1=N[O-]<-[Ir+3]23(->[c-]4ccccc4-c4oc(-c5ccccc5)c[n]<-24)(->[c-]2ccccc2-c2oc(-c4...

Обрабатываем строку 1037...
   [Строка 1037] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! C1=N[O-]<-[Ir+3]2345(->[c-]6ccccc6-c6c(-c7ccccc7)[n]<-2c2ccccc2[n]<-36)(->[c-]2c...

Обрабатываем строку 1038...
   [Строка 1038] Санитизация не удалась: Explicit valence for atom # 30 N, 5, is greater than permitted
   Успех! CC(C)[n+]12<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[c-]3ccccc3-c3cccc[n]<-...

Обрабатываем строку 1039...
   [Строка 1039] Санитизация не удалась: Explicit valence for atom # 31 N, 5, is greater than permitted
   Успех! CC(C)C[n+]12<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[c-]3ccccc3-c3cccc[n]<...

Обрабатываем строку 1040...
   [Строка 1040] Санитизация не удалась: Explicit valence for atom # 26 N, 5, is greater than permitted
   Успех! c1ccc(C[n+]23<-[Ir+2]456789(->[c-]%10ccccc%10-c%10cccc[n]<-4%10)(->[c-]4ccccc4-c...

Обрабатываем строку 1041...
   [Строка 1041] Санитизация не удалась: Explicit valence for atom # 33 N, 5, is greater than permitted
   Успех! CSc1ccc(-[n+]23<-[Ir+2]456789(->[c-]%10ccccc%10-c%10cccc[n]<-4%10)(->[c-]4ccccc4...

Обрабатываем строку 1042...
   [Строка 1042] Санитизация не удалась: Explicit valence for atom # 26 N, 5, is greater than permitted
   Успех! c1ccc(C[n+]23<-[Ir+2]456789(->[c-]%10ccccc%10-c%10cccc[n]<-4%10)(->[c-]4ccccc4-c...

Обрабатываем строку 1043...
   [Строка 1043] Санитизация не удалась: Explicit valence for atom # 31 N, 5, is greater than permitted
   Успех! CC(C)C[n+]12<-[Ir+2]345678(->[c-]9ccccc9-c9cccc[n]<-39)(->[c-]3ccccc3-c3cccc[n]<...

Обрабатываем строку 1044...
   [Строка 1044] Санитизация не удалась: Explicit valence for atom # 38 O, 2, is greater than permitted
   Успех! CC(N)C(=O)[O-]<-[Ir+3]12(->[c-]3cc(C(F)(F)F)ccc3-c3cccc[n]<-13)->[c-]1cc(C(F)(F)...

Обрабатываем строку 1045...
   [Строка 1045] Санитизация не удалась: Explicit valence for atom # 46 O, 2, is greater than permitted
   Успех! CC(N)C(=O)[O-]<-[Ir+3]12(->[c-]3cc(C(F)(F)F)ccc3-c3c4ccccc4cc[n]<-13)->[c-]1cc(C...

Обрабатываем строку 1046...
   [Строка 1046] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]C(=O)c8cccc[n]<-48)(->[c-]4cc8ccccc8cc4-c3c[n]<-51...

Обрабатываем строку 1047...
   [Строка 1047] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]C(=O)c8cc9ccccc9c[n]<-48)(->[c-]4cc8ccccc8cc4-c3c[...

Обрабатываем строку 1048...
   [Строка 1048] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]C(=O)c8ccc9ccccc9[n]<-48)(->[c-]4cc8ccccc8cc4-c3c[...

Обрабатываем строку 1049...
   [Строка 1049] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]c8ccccc8-c8cccc[n]<-48)(->[c-]4cc8ccccc8cc4-c3c[n]...

Обрабатываем строку 1050...
   [Строка 1050] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]C(=O)c8cccc[n]<-48)(->[c-]4ccc8ccccc8c4-c3c[n]<-51...

Обрабатываем строку 1051...
   [Строка 1051] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]C(=O)c8cc9ccccc9c[n]<-48)(->[c-]4ccc8ccccc8c4-c3c[...

Обрабатываем строку 1052...
   [Строка 1052] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]C(=O)c8ccc9ccccc9[n]<-48)(->[c-]4ccc8ccccc8c4-c3c[...

Обрабатываем строку 1053...
   [Строка 1053] Санитизация не удалась: Explicit valence for atom # 19 N, 6, is greater than permitted
   Успех! Cc1csc2[n]3<-[Ir+3]4567(->[O-]c8ccccc8-c8cccc[n]<-48)(->[c-]4ccc8ccccc8c4-c3c[n]...

Обрабатываем строку 1054...
   [Строка 1054] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
   Успех! Fc1cc(F)c2-c3ccc(C(F)(F)F)c[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1ccc(C...

Обрабатываем строку 1055...
   [Строка 1055] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)->[...

Обрабатываем строку 1056...
   [Строка 1056] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1ccccc1-...

Обрабатываем строку 1057...
   [Строка 1057] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
   Успех! Fc1cc(F)c2-c3ccc(C(F)(F)F)c[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1ccc(C...

Обрабатываем строку 1058...
   [Строка 1058] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)->[...

Обрабатываем строку 1059...
   [Строка 1059] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1ccccc1-...

Обрабатываем строку 1060...
   [Строка 1060] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
   Успех! Fc1cc(F)c2-c3ccc(C(F)(F)F)c[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1ccc(C...

Обрабатываем строку 1061...
   [Строка 1061] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)->[...

Обрабатываем строку 1062...
   [Строка 1062] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1ccccc1-...

Обрабатываем строку 1063...
   [Строка 1063] Санитизация не удалась: Explicit valence for atom # 27 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]23(->[c-]4ccccc4-c4cccc[n]<-24)(->[c-]2ccccc2-c2cccc[n]<-32)->[n...

Обрабатываем строку 1064...
   [Строка 1064] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1cc[c-]2<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3ccc([Si](C)(C)C)...

Обрабатываем строку 1065...
   [Строка 1065] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1ccc2-c3cccc[n]3<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]2c1)->[c-...

Обрабатываем строку 1066...
   [Строка 1066] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1cc[n]2<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3ccccc3-c2c1)->[c-...

Обрабатываем строку 1067...
   [Строка 1067] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1ccc2-c3cccc[c-]3<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3ccccc3-...

Обрабатываем строку 1068...
   [Строка 1068] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1cc[c-]2<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3ccc([Si](C)(C)C)...

Обрабатываем строку 1069...
   [Строка 1069] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1cc[c-]2<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3ccc([Si](C)(C)C)...

Обрабатываем строку 1070...
   [Строка 1070] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1cc[n]2<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3cc([Si](C)(C)C)cc...

Обрабатываем строку 1071...
   [Строка 1071] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! C[Si](C)(C)c1ccc2-c3ccc([Si](C)(C)C)c[n]3<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->...

Обрабатываем строку 1072...
   [Строка 1072] Санитизация не удалась: Explicit valence for atom # 8 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]1234(->[c-]5cc(F)ccc5-c5c[n]<-16ccccc6[n]<-25)->[c-...

Обрабатываем строку 1073...

[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 30 41 42
[20:59:01] Explicit valence for atom # 26 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 32 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 23 24 25
[20:59:01] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 51 52 54
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 24 25
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 26 28
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 30 32
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 34 36
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 34 36
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 35 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 17 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 35 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 37 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 6 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 13
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 33 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 53 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 16 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 8 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 4 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 55 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 57 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 69 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 25 26 28 29 30 31 33 47 48 49 50 51 53
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 35 37 38 39 40 41 43 44 46 47 48 49 50
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 29 30 32 33 34 35 37 51 52 53 54 55 57
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 38 40 41 42 43 44 46 47 49 50 51 52 53
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 39 41 42 43 44 45 47 48 50 51 52 53 54
[20:59:01] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 44 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 46 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 48 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14 15 16 17 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 8
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 13
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 13
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 11 12 13
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 11 12 13
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[20:59:01] Explicit valence for atom # 17 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 14 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 54 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 56 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 62 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 62 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 37 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 25 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 17 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 5 16 17 20
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 5 16 17 20
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 10 11
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 30 53 54
[20:59:01] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 29 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 123 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 131 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 41
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 41 43 44 45 46 47 48
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 40
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 39
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 39
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 39
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 75 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 75 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 31 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 18 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 18 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 25 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 29 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 25 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 45 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 46 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 46 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 45 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 49 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 48 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted

   [Строка 1135] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]45(->[c-]6ccccc6-c6sc7ccccc7[n]<-46)(->[c-]4ccccc4-c4sc6c...

Обрабатываем строку 1136...
   [Строка 1136] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 13
   Успех! Cc1cc[c-]2<-[Ir+2]34(->[c-]5ccc(C)cc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1c(C...

Обрабатываем строку 1137...
   [Строка 1137] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[n]3cccc5ccc6ccc[n]<-4c...

Обрабатываем строку 1138...
   [Строка 1138] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc(-c2ccccc2)c2ccc3c(-c4ccccc4)cc(C)[n]4<-[Ir+2]56(->[c-]7ccccc7-c7ccc8ccccc8...

Обрабатываем строку 1139...
   [Строка 1139] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2cc[n]3<-[Ir+2]45(->[c-]6ccccc6-c6ccc7ccccc7[n]<-46)(->[c-]4ccccc4-c4ccc...

Обрабатываем строку 1140...
   [Строка 1140] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1c[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3-c3ccc5ccccc5...

Обрабатываем строку 1141...
   [Строка 1141] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1ccc2ccc3ccc(C)[n]4<-[Ir+2]56(->[c-]7ccccc7-c7ccc8ccccc8[n]<-57)(->[c-]5ccccc5...

Обрабатываем строку 1142...
   [Строка 1142] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2ccc3ccc4ccc(-c5ccccc5)[n]5<-[Ir+2]67(->[c-]8ccccc8-c8ccc9ccccc9[n]<-68)...

Обрабатываем строку 1143...
   [Строка 1143] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3-c3ccc5ccccc...

Обрабатываем строку 1144...
   [Строка 1144] Санитизация не удалась: Explicit valence for atom # 39 N, 4, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]34567(->[c-]8cc(F)cc(F)c8-c2c1)(->[c-]1cc(F)cc(F)c1-c1cc(C)cc[n...

Обрабатываем строку 1145...
   [Строка 1145] Санитизация не удалась: Explicit valence for atom # 33 N, 4, is greater than permitted
   Успех! c1cc[c-]2<-[Ir+3]34567(->[c-]8ccccc8-c8cccc[n]<-38)(->[n]3ccccc3-c2c1)->[n]1cccc...

Обрабатываем строку 1146...
   [Строка 1146] Санитизация не удалась: Explicit valence for atom # 53 N, 4, is greater than permitted
   Успех! c1ccc(-c2cc3-c4cccc[c-]4<-[Ir+3]45678(->[c-]9ccccc9-c9cc(-c%10ccccc%10)c%10ccccc...

Обрабатываем строку 1147...
   [Строка 1147] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-...

Обрабатываем строку 1148...
   [Строка 1148] Санитизация не удалась: Explicit valence for atom # 16 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(-c6ccc7c(c6)c6ccccc6[n]<-17-c1ccccc1)ccc5...

Обрабатываем строку 1149...
   [Строка 1149] Санитизация не удалась: Explicit valence for atom # 8 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(-c6ccc(-[n]<-17c1ccccc1c1ccccc17)cc6)ccc5...

Обрабатываем строку 1150...
   [Строка 1150] Санитизация не удалась: Explicit valence for atom # 4 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(-[n]<-16c1ccccc1c1ccccc16)ccc5-c1cccc[n]<...

Обрабатываем строку 1151...
   [Строка 1151] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(-c4ccccc4)ccc3-c3cccc[n]<-13)->[c-]1cc(-c3c...

Обрабатываем строку 1152...
   [Строка 1152] Санитизация не удалась: Explicit valence for atom # 53 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc4ccc5cccc6ccc(c3-c3cccc[n]<-13)c4c56)->...

Обрабатываем строку 1153...
   [Строка 1153] Санитизация не удалась: Explicit valence for atom # 61 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc4ccc5cccc6ccc(c3-c3ccc(C(F)(F)F)c[n]<-1...

Обрабатываем строку 1154...
   [Строка 1154] Санитизация не удалась: Explicit valence for atom # 55 O, 2, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3cc4ccc5cccc6ccc(c3-c3ccc(F)c[n]<-13)c4c56...

Обрабатываем строку 1155...
   [Строка 1155] Санитизация не удалась: Explicit valence for atom # 55 O, 2, is greater than permitted
   Успех! Cc1ccc2-c3c4ccc5cccc6ccc(c[c-]3<-[Ir+3]3(->[O-]C(=CC(=O)C(C)(C)C)C(C)(C)C)(->[c-...

Обрабатываем строку 1156...
   [Строка 1156] Санитизация не удалась: Explicit valence for atom # 57 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(N(c6ccccc6)c6ccccc6)ccc5-c5[n]<-1ccc[n]<-...

Обрабатываем строку 1157...
   [Строка 1157] Санитизация не удалась: Explicit valence for atom # 69 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc([Si](c6ccccc6)(c6ccccc6)c6ccccc6)ccc5-c5[...

Обрабатываем строку 1158...
   [Строка 1158] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 25 26 28 29 30 31 33 47 48 49 50 51 53
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[n]3ccccc3-c2c1)->[n]1cccc2...

Обрабатываем строку 1159...
   [Строка 1159] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 42 43 45 46 47 48 49
   Успех! CN1CCN(c2ccc(-c3[n]4<-[Ir+2]5678(->[c-]9ccccc9-c9cccc[n]<-59)(->[c-]5ccccc5-c5cc...

Обрабатываем строку 1160...
   [Строка 1160] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 35 37 38 39 40 41 43 44 46 47 48 49 50
   Успех! C[N+]1(C)CCN(c2ccc(-c3[n]4<-[Ir+]5678(->[c-]9ccccc9-c9cccc[n]<-59)(->[c-]5ccccc5...

Обрабатываем строку 1161...
   [Строка 1161] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 29 30 32 33 34 35 37 51 52 53 54 55 57
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)-...

Обрабатываем строку 1162...
   [Строка 1162] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 38 40 41 42 43 44 46 47 49 50 51 52 53
   Успех! CN1CCN(c2ccc(-c3[n]4<-[Ir+2]5678(->[c-]9cc(F)cc(F)c9-c9cccc[n]<-59)(->[c-]5cc(F)...

Обрабатываем строку 1163...
   [Строка 1163] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 39 41 42 43 44 45 47 48 50 51 52 53 54
   Успех! C[N+]1(C)CCN(c2ccc(-c3[n]4<-[Ir+]5678(->[c-]9cc(F)cc(F)c9-c9cccc[n]<-59)(->[c-]5...

Обрабатываем строку 1164...
   [Строка 1164] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cccc6c7ccccc7c7c(c65)[n]<-1c1c([n]<-27)CCCC1...

Обрабатываем строку 1165...
   [Строка 1165] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! O=C1[O-]<-[Ir+3]2345(->[c-]6cccc7c8ccccc8c8c(c76)[n]<-2c2c([n]<-38)CCCC2)(->[c-]...

Обрабатываем строку 1166...
   [Строка 1166] Санитизация не удалась: Explicit valence for atom # 44 O, 2, is greater than permitted
   Успех! CCCN=Cc1ccccc1[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1ccccc1-c1c...

Обрабатываем строку 1167...
   [Строка 1167] Санитизация не удалась: Explicit valence for atom # 46 O, 2, is greater than permitted
   Успех! Cc1ccc(N=Cc2ccccc2[O-]<-[Ir+3]23(->[c-]4ccccc4-c4c5ccccc5cc[n]<-24)->[c-]2ccccc2...

Обрабатываем строку 1168...
   [Строка 1168] Санитизация не удалась: Explicit valence for atom # 48 O, 2, is greater than permitted
   Успех! CCCN=Cc1ccccc1[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4c(C#N)c[n]<-13)->[c-]1ccccc...

Обрабатываем строку 1169...
   [Строка 1169] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! CCC[N-]C(=O)c1cccc[n]1<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1ccccc1...

Обрабатываем строку 1170...
   [Строка 1170] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1ccc([N-]C(=O)c2cccc[n]2<-[Ir+3]23(->[c-]4ccccc4-c4c5ccccc5cc[n]<-24)->[c-]2cc...

Обрабатываем строку 1171...
   [Строка 1171] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! O=C([N-]c1ccc(C(F)(F)F)cc1)c1cccc[n]1<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-1...

Обрабатываем строку 1172...
   [Строка 1172] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14 15 16 17 18
   Успех! N#Cc1c[n]2<-[Ir+3]3(->[c-]4ccccc4-c2c2ccccc12)(->[c-]1ccccc1-c1c2ccccc2c(C#N)c[n...

Обрабатываем строку 1173...
   [Строка 1173] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 8
   Успех! C=Cc1ccc[n]2<-[Ir+2]34(->[c-]5ccccc5-c12)(->[c-]1ccccc1-c1c(C=C)ccc[n]<-31)->[n]...

Обрабатываем строку 1174...
   [Строка 1174] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 13
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c2c1C=Cc1ccccc1)(->[c-]1ccccc1-c1c(C=Cc2ccccc2...

Обрабатываем строку 1175...
   [Строка 1175] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 13
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5c(C=Cc6ccccc6)c(C)cc[n]<-35)(->[c-]3ccccc3-c...

Обрабатываем строку 1176...
   [Строка 1176] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-...

Обрабатываем строку 1177...
   [Строка 1177] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 11 12 13
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7cc(CN8CCCCC8)ccc7-c7cccc[n]<-37)(->[c-]3cc(CN7CCCCC...

Обрабатываем строку 1178...
   [Строка 1178] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7cc(C)ccc7-c7cccc[n]<-37)(->[c-]3cc(C)ccc3-c3cccc[n]...

Обрабатываем строку 1179...
   [Строка 1179] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
   Успех! CCCCNCc1ccc2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(CNCCCC)ccc1-c1cccc[n]<-...

Обрабатываем строку 1180...
   [Строка 1180] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 11 12 13
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7cc(CN8CCCCC8)ccc7-c7cccc[n]<-37)(->[c-]3cc(CN7CCCCC...

Обрабатываем строку 1181...
   [Строка 1181] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7cc(C)ccc7-c7cccc[n]<-37)(->[c-]3cc(C)ccc3-c3cccc[n]...

Обрабатываем строку 1182...
   [Строка 1182] Санитизация не удалась: Explicit valence for atom # 17 N, 6, is greater than permitted
   Успех! CC(C)(C)C(=O)C=C([O-]<-[Ir+3]123456(->[c-]7c(-c8[n]<-1ccc[n]<-28)cc1c2ccccc2[n]<...

Обрабатываем строку 1183...
   [Строка 1183] Санитизация не удалась: Explicit valence for atom # 14 N, 6, is greater than permitted
   Успех! Cc1cc2-c3cc4c5ccccc5[n]56<-[Ir+3]789%10(->[O-]C(=CC(=O)C(C)(C)C)C(C)(C)C)(->[c-]...

Обрабатываем строку 1184...
   [Строка 1184] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(C)cc(C)cc3-c3c4ccc5ccccc5c4cc[n]<-13)->[c-]1...

Обрабатываем строку 1185...
   [Строка 1185] Санитизация не удалась: Explicit valence for atom # 54 O, 2, is greater than permitted
   Успех! CCC(CC)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3c(C)cc(C)cc3-c3c4ccc5ccccc5c4cc[n]<-13)->[...

Обрабатываем строку 1186...
   [Строка 1186] Санитизация не удалась: Explicit valence for atom # 56 O, 2, is greater than permitted
   Успех! CCC(CC)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3c(C)cc(C)cc3-c3c4ccc5cc(C)ccc5c4cc[n]<-13)...

Обрабатываем строку 1187...
   [Строка 1187] Санитизация не удалась: Explicit valence for atom # 62 O, 2, is greater than permitted
   Успех! CCC(CC)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3c(C)cc(C)cc3-c3c4ccc5cc(C(C)(C)C)ccc5c4cc[...

Обрабатываем строку 1188...
   [Строка 1188] Санитизация не удалась: Explicit valence for atom # 62 O, 2, is greater than permitted
   Успех! CCC(CC)C(=O)C=C([O-]<-[Ir+3]12(->[c-]3c(C)cc(C)cc3-c3c4ccc5cc([Si](C)(C)C)ccc5c4...

Обрабатываем строку 1189...
   [Строка 1189] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc(C#N)c[n]<-13)->[c-]1ccccc1-c1ccc(...

Обрабатываем строку 1190...
   [Строка 1190] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(C#N)cc[n]<-13)->[c-]1ccccc1-c1cc(C...

Обрабатываем строку 1191...
   [Строка 1191] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(C#N)ccc3-c3cccc[n]<-13)->[c-]1cc(C#N)ccc1-c...

Обрабатываем строку 1192...
   [Строка 1192] Санитизация не удалась: Explicit valence for atom # 37 N, 4, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]3456(->[c-]7cc(F)cc(F)c7-c2c1)(->[c-]1cc(F)cc(F)c1-c1cc(C)cc[n]...

Обрабатываем строку 1193...
   [Строка 1193] Санитизация не удалась: Explicit valence for atom # 25 O, 2, is greater than permitted
   Успех! c1ccc2-c3cccc[n]3<-[Ir+3]34(->[O-]c2c1)(->[c-]1ccccc1-c1cccc[n]<-31)->[c-]1ccccc...

Обрабатываем строку 1194...
   [Строка 1194] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 17 18
   Успех! COc1ccc2-c3c4ccccc4cc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(OC)ccc1-c1c2ccccc2cc[n]...

Обрабатываем строку 1195...
   [Строка 1195] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 5 16 17 20
   Успех! COc1cc(OC)[c-]2<-[Ir+2]34(->[c-]5c(OC)cc(OC)cc5-c5c6ccccc6cc[n]<-35)(->[n]3ccc5c...

Обрабатываем строку 1196...
   [Строка 1196] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 5 16 17 20
   Успех! COc1cc2-c3c4ccccc4cc[n]3<-[Ir+2]34(->[c-]2c(OC)c1OC)(->[c-]1c(-c2c5ccccc5cc[n]<-...

Обрабатываем строку 1197...
   [Строка 1197] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! FC(F)(F)c1ccc(C2=Nc3oc(-c4ccccc4)[n]4<-[Ir+3]5678(->[O-]2)(->[c-]2cc(C(F)(F)F)cc...

Обрабатываем строку 1198...
   [Строка 1198] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! FC(F)(F)c1cc(C2=Nc3oc(-c4ccccc4)[n]4<-[Ir+3]5678(->[O-]2)(->[c-]2cc(C(F)(F)F)ccc...

Обрабатываем строку 1199...
   [Строка 1199] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! FC(F)(F)c1ccc(C2=Nc3oc(-c4ccccc4)[n]4<-[Ir+3]5678(->[O-]2)(->[c-]2c(-c9[n]<-5ccc...

Обрабатываем строку 1200...
   [Строка 1200] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! FC(F)(F)c1cc(C2=Nc3oc(-c4ccccc4)[n]4<-[Ir+3]5678(->[O-]2)(->[c-]2c(-c9[n]<-5ccc[...

Обрабатываем строку 1201...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1202...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1203...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1204...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1205...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1206...
   [Строка 1206] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)ccc3-c3cccc[...

Обрабатываем строку 1207...
   [Строка 1207] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 10 11
   Успех! Cc1cc[n]2<-[Ir+2]3456(->[c-]7cc(-c8sc9ccccc9[n]<-38)ccc7-c3cccc[n]<-43)(->[c-]3c...

Обрабатываем строку 1208...
   [Строка 1208] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! O=Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)-...

Обрабатываем строку 1209...
   [Строка 1209] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 25 26 27 28 30 53 54
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[n]3ccccc3-c2c1)->[n]1ccc(-...

Обрабатываем строку 1210...
   [Строка 1210] Санитизация не удалась: Explicit valence for atom # 29 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]456(->[c-]7ccccc7-c7cccc[n]<-47)(->[c-]4ccccc4-c4cccc[n]<-54...

Обрабатываем строку 1211...
   [Строка 1211] Санитизация не удалась: Explicit valence for atom # 29 N, 5, is greater than permitted
   Успех! c1ccc(-[n]23<-[Ir+2]45678(->[c-]9ccccc9-c9cccc[n]<-49)(->[c-]4ccccc4-c4cccc[n]<-...

Обрабатываем строку 1212...
   [Строка 1212] Санитизация не удалась: Explicit valence for atom # 123 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc6c(-c7ccc(N(c8ccccc8)c8ccccc8)cc7)c(-c7cc...

Обрабатываем строку 1213...
   [Строка 1213] Санитизация не удалась: Explicit valence for atom # 131 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5ccc6c(-c7ccc(N(c8ccccc8)c8ccccc8)cc7)c(-c7cc...

Обрабатываем строку 1214...
   [Строка 1214] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! C=CCC(N)c1ccc2-c3cccc[c-]3<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3ccccc3-c3c...

Обрабатываем строку 1215...
   [Строка 1215] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! O=Cc1ccc2-c3cccc[c-]3<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3ccccc3-c3ccc(C=...

Обрабатываем строку 1216...
   [Строка 1216] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7cccc[n]<-37)(->[n]3ccccc3-c2c1)->[n]1ccccc...

Обрабатываем строку 1217...
   [Строка 1217] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 16 18
   Успех! Fc1cc(F)c2-c3ccc(C(F)(F)F)c[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1ccc...

Обрабатываем строку 1218...
   [Строка 1218] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10
   Успех! c1ccc(-c2c[n]3<-[Ir+2]4567(->[c-]8ccccc8-c3o2)(->[c-]2ccccc2-c2oc(-c3ccccc3)c[n]...

Обрабатываем строку 1219...
   [Строка 1219] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1ccc(-c2c3-c4cccc[c-]4<-[Ir+2]456789(->[c-]%10ccccc%10-c%10c(-c%11ccccc%11)[n]<...

Обрабатываем строку 1220...
   [Строка 1220] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 34 36 37 38 39 40 41
   Успех! COC(=O)CNC([S-])=Cc1[n]2<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3...

Обрабатываем строку 1221...
   [Строка 1221] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 41 43 44 45 46 47 48
   Успех! COC(=O)C(Cc1ccccc1)NC([S-])=Cc1[n]2<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-...

Обрабатываем строку 1222...
   [Строка 1222] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 33 35 36 37 38 39 40
   Успех! CCCCOC([S-])=Cc1[n]2<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc...

Обрабатываем строку 1223...
   [Строка 1223] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 39
   Успех! OCCNC([S-])=Cc1[n]2<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[...

Обрабатываем строку 1224...
   [Строка 1224] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 39
   Успех! C=CCNC([S-])=Cc1[n]2<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc...

Обрабатываем строку 1225...
   [Строка 1225] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 39
   Успех! C#CCNC([S-])=Cc1[n]2<-[Ir+3]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc...

Обрабатываем строку 1226...
   [Строка 1226] Санитизация не удалась: Explicit valence for atom # 43 O, 2, is greater than permitted
   Успех! Cc1c2-c3cccc[c-]3<-[Ir+3]345(->[O-]C(=CC(=O)C(C)(C)C)C(C)(C)C)(->[c-]6ccccc6-c6c...

Обрабатываем строку 1227...
   [Строка 1227] Санитизация не удалась: Explicit valence for atom # 75 O, 2, is greater than permitted

[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 40 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 36 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 44 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 44 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 13 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 53 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 5 6 8 15 16
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 5 6 8 15 16
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 10 11 12 13 14 15
[20:59:01] Explicit valence for atom # 88 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 78 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 82 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 72 N, 4, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 17 18 21 22 23 24 25 26
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14 17 18 19 20 21 22
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 14 15 17 24 25
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 25
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17 18 19
[20:59:01] Explicit valence for atom # 55 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17 18 19
[20:59:01] Explicit valence for atom # 55 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 36 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 36 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 21 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 16
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 5 6 8 15 20
[20:59:01] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 11 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 30 32 33 35 36 38 39 41 42 44 45
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 40 41 43 44 45 46 47
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 32 34 35 37 38 40 41 43 44 46 47
[20:59:01] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 51 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 20 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
[20:59:01] Explicit valence for atom # 38 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 36 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 30 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 34 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 54 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 65 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 66 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 63 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 9 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 39 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 33 N, 4, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 15
[20:59:01] Explicit valence for atom # 35 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 39 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 37 39 40 41 42 43 45 46 48 49 50 51 52
[20:59:01] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 15 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 14 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 48 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 48 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 37 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 37 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 45 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 47 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 59 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 60 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 60 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 61 O, 2, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 5 6 8 15 16
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 5 6 8 19 20
[20:59:01] Explicit valence for atom # 23 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 31 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 39 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 44 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 32 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 17 18 19
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 10 11 19 20
[20:59:01] Explicit valence for atom # 61 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 27 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 35 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 43 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 7 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 15 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 15 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 15 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted
[20:59:01] Explicit valence for atom # 19 N, 6, is greater than permitted

   [Строка 1287] Санитизация не удалась: Explicit valence for atom # 88 N, 4, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]345(->[c-]6cc(OC)c(S(=O)(=O)c7ccc(C)cc7)c(F)c6-c6cc(-c7c(C)cc(...

Обрабатываем строку 1288...
   [Строка 1288] Санитизация не удалась: Explicit valence for atom # 78 N, 4, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]345(->[c-]6cc(OC)c(S(C)(=O)=O)c(OC)c6-c6cc(-c7c(C)cc(C)cc7C)cc...

Обрабатываем строку 1289...
   [Строка 1289] Санитизация не удалась: Explicit valence for atom # 82 N, 4, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]345(->[c-]6cc(OC)c(S(=O)(=O)c7ccc(C)cc7)c(F)c6-c6cc(-c7c(C)cc(...

Обрабатываем строку 1290...
   [Строка 1290] Санитизация не удалась: Explicit valence for atom # 72 N, 4, is greater than permitted
   Успех! COc1c[c-]2<-[Ir+3]345(->[c-]6cc(OC)c(S(C)(=O)=O)c(OC)c6-c6cc(-c7c(C)cc(C)cc7C)cc...

Обрабатываем строку 1291...
   [Строка 1291] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 17 18 21 22 23 24 25 26
   Успех! O=C1c2ccccc2C(=O)c2c[c-]3<-[Ir+2]45(->[c-]6cc7C(=O)c8ccccc8C(=O)c7cc6-c6ccc7cccc...

Обрабатываем строку 1292...
   [Строка 1292] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14 17 18 19 20 21 22
   Успех! O=C1c2ccccc2C(=O)c2c[c-]3<-[Ir+2]45(->[c-]6cc7C(=O)c8ccccc8C(=O)c7cc6-c6cccc[n]<...

Обрабатываем строку 1293...
   [Строка 1293] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 14 15 17 24 25
   Успех! O=C1c2ccccc2C(=O)c2cc(-c3ccc4-c5cccc[n]5<-[Ir+2]56(->[c-]4c3)(->[c-]3cc(-c4ccc7C...

Обрабатываем строку 1294...
   [Строка 1294] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 14 15 16 17 25
   Успех! O=C1c2ccccc2C(=O)c2cc(-c3ccc4-c5cccc[c-]5<-[Ir+2]56(->[c-]7ccccc7-c7ccc(-c8ccc9C...

Обрабатываем строку 1295...
   [Строка 1295] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17 18 19
   Успех! CCN(CC)c1ccc2c(c1)oc(=O)c1-c3sc4ccccc4[n]3<-[Ir+2]34(->[c-]12)(->[c-]1c(-c2sc5cc...

Обрабатываем строку 1296...
   [Строка 1296] Санитизация не удалась: Explicit valence for atom # 55 N, 5, is greater than permitted
   Успех! CCN(CC)c1ccc2c(c1)oc(=O)c1-c3sc4ccccc4[n]3<-[Ir+2]345(->[c-]12)(->[c-]1c(-c2sc6c...

Обрабатываем строку 1297...
   [Строка 1297] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17 18 19
   Успех! CCN(CC)c1ccc2c(c1)oc(=O)c1-c3sc4ccccc4[n]3<-[Ir+2]34(->[c-]12)(->[c-]1c(-c2sc5cc...

Обрабатываем строку 1298...
   [Строка 1298] Санитизация не удалась: Explicit valence for atom # 55 N, 5, is greater than permitted
   Успех! CCN(CC)c1ccc2c(c1)oc(=O)c1-c3sc4ccccc4[n]3<-[Ir+2]345(->[c-]12)(->[c-]1c(-c2sc6c...

Обрабатываем строку 1299...
   [Строка 1299] Санитизация не удалась: Explicit valence for atom # 36 O, 2, is greater than permitted
   Успех! O=S1(=O)[O-]<-[Ir+3]23(->[c-]4cc(C(F)(F)F)ccc4-c4cccc[n]<-24)(->[c-]2cc(C(F)(F)F...

Обрабатываем строку 1300...
   [Строка 1300] Санитизация не удалась: Explicit valence for atom # 36 O, 2, is greater than permitted
   Успех! O=S1(=O)[O-]<-[Ir+3]23(->[c-]4cccc(C(F)(F)F)c4-c4cccc[n]<-24)(->[c-]2cccc(C(F)(F...

Обрабатываем строку 1301...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1302...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1303...
   [Строка 1303] Санитизация не удалась: Explicit valence for atom # 21 N, 5, is greater than permitted
   Успех! CC(C)(C)c1ccc2c(c1)c1cc(C(C)(C)C)ccc1[n]21-c2cccc(-c3cc4C(=O)c5c(F)c[c-]6<-[Ir+3...

Обрабатываем строку 1304...
   [Строка 1304] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! O=C(c1ccccc1)c1c(F)c[c-]2<-[Ir+3]34(->[O-]C(=O)c5cccc[n]<-35)(->[c-]3cc(F)c(C(=O...

Обрабатываем строку 1305...
   [Строка 1305] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[c-]3ccccc3-c3cccc[n]<-43)->[...

Обрабатываем строку 1306...
   [Строка 1306] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 16
   Успех! COc1cc(OC)c2-c3cccc[n]3<-[Ir+2]34(->[c-]2c1)(->[c-]1cc(OC)cc(OC)c1-c1cccc[n]<-31...

Обрабатываем строку 1307...
   [Строка 1307] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 3 4 6 13 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(C=O)ccc5-c5cccc[n]<-35)(->[c-]3cc(C=O)ccc3-c3cccc[...

Обрабатываем строку 1308...
   [Строка 1308] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 5 6 8 15 20
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(C(F)(F)F)cc(C(F)(F)F)c5-c5cccc[n]<-35)(->[c-]3cc(C...

Обрабатываем строку 1309...
   [Строка 1309] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! Cc1cccc(C)c1-[n]12<-[Ir+2]345678(->[c-]9ccccc9-c1[n]<-3c(C)[n]<-42)(->[c-]1ccccc...

Обрабатываем строку 1310...
   [Строка 1310] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! Cc1cccc(C)c1-[n]12<-[Ir+2]3456789(->[c-]%10ccccc%10-c1[n]<-3c(C)[n]<-42)(->[c-]1...

Обрабатываем строку 1311...
   [Строка 1311] Санитизация не удалась: Explicit valence for atom # 11 N, 5, is greater than permitted
   Успех! Cc1[n]2<-[Ir+2]3456789(->[c-]%10ccccc%10-c2[n]<-3(C)[n]<-41)(->[c-]1ccccc1-c1[n]...

Обрабатываем строку 1312...
   [Строка 1312] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 34 35 36 38 39 41 42 43 44 45
   Успех! Clc1ccc(-c2[n]3<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]...

Обрабатываем строку 1313...
   [Строка 1313] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 30 32 33 35 36 38 39 41 42 44 45
   Успех! Clc1ccc(-c2[n]3<-[Ir+2]456789(->[c-]%10ccccc%10-c%10cccc[n]<-4%10)(->[c-]4ccccc4...

Обрабатываем строку 1314...
   [Строка 1314] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 32 34 35 36 37 38 40 41 43 44 45 46 47
   Успех! C[n+]12<-[Ir]345678(->[c-](ccc1)c2-c1cccc[n]<-31)(->[c-]1ccc[n+]<-4(C)c1-c1cccc[...

Обрабатываем строку 1315...
   [Строка 1315] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 32 34 35 37 38 40 41 43 44 46 47
   Успех! C[n+]12<-[Ir]3456789%10(->[c-](ccc1)c2-c1cccc[n]<-31)(->[c-]1ccc[n+]<-4(C)c1-c1c...

Обрабатываем строку 1316...
   [Строка 1316] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4ccccc4[n]<-13)->[c-]1ccccc1-c1ccc...

Обрабатываем строку 1317...
   [Строка 1317] Санитизация не удалась: Explicit valence for atom # 51 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cc(-c4ccccc4)c4ccccc4[n]<-13)->[c-]1c...

Обрабатываем строку 1318...
   [Строка 1318] Санитизация не удалась: Explicit valence for atom # 65 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc4cc(N(c5ccccc5)c5ccccc5)ccc4[n]<-1...

Обрабатываем строку 1319...
   [Строка 1319] Санитизация не удалась: Explicit valence for atom # 61 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4ccccc4cc3-c3cc(-c4ccccc4)c4cc(C)ccc4[n]<-13...

Обрабатываем строку 1320...
   [Строка 1320] Санитизация не удалась: Explicit valence for atom # 61 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc4ccccc4cc3-c3cc(-c4ccccc4)c4cc(F)ccc4[n]<-13...

Обрабатываем строку 1321...
   [Строка 1321] Санитизация не удалась: Explicit valence for atom # 20 N, 5, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]123456(->[c-]7cc8c(cc7-c7cccc[n]<-17)C(CCCCCC[n]<-21c2cc...

Обрабатываем строку 1322...
   [Строка 1322] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3c4ccccc4cc[n]<-13)->[c-]1ccccc1-c1c3c...

Обрабатываем строку 1323...
   [Строка 1323] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3sc4ccccc4[n]<-13)->[c-]1ccccc1-c1sc3c...

Обрабатываем строку 1324...
   [Строка 1324] Санитизация не удалась: Explicit valence for atom # 31 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3cccc[n]<-13)->[c-]1ccccc1-c1cccc[n]<-...

Обрабатываем строку 1325...
   [Строка 1325] Санитизация не удалась: Explicit valence for atom # 35 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(F)cc(F)c3-c3cccc[n]<-13)->[c-]1cc(F)cc(F)c1...

Обрабатываем строку 1326...
   [Строка 1326] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5c6ccccc6cc[n]<-35)(->[c-]3ccccc3-c3c5ccccc5c...

Обрабатываем строку 1327...
   [Строка 1327] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5sc6ccccc6[n]<-35)(->[c-]3ccccc3-c3sc5ccccc5[...

Обрабатываем строку 1328...
   [Строка 1328] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 14
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5cc(F)cc(F)c5-c5cccc[n]<-35)(->[c-]3cc(F)cc(F)c3-c3ccc...

Обрабатываем строку 1329...
   [Строка 1329] Санитизация не удалась: Explicit valence for atom # 38 N, 5, is greater than permitted
   Успех! c1ccc(C[n]23<-[Ir+2]4567(->[c-]8ccccc8-c8c9ccccc9cc[n]<-48)(->[c-]4ccccc4-c4c8cc...

Обрабатываем строку 1330...
   [Строка 1330] Санитизация не удалась: Explicit valence for atom # 36 N, 5, is greater than permitted
   Успех! c1ccc(C[n]23<-[Ir+2]4567(->[c-]8ccccc8-c8sc9ccccc9[n]<-48)(->[c-]4ccccc4-c4sc8cc...

Обрабатываем строку 1331...
   [Строка 1331] Санитизация не удалась: Explicit valence for atom # 30 N, 5, is greater than permitted
   Успех! c1ccc(C[n]23<-[Ir+2]4567(->[c-]8ccccc8-c8cccc[n]<-48)(->[c-]4ccccc4-c4cccc[n]<-5...

Обрабатываем строку 1332...
   [Строка 1332] Санитизация не удалась: Explicit valence for atom # 34 N, 5, is greater than permitted
   Успех! Fc1cc(F)c2-c3cccc[n]3<-[Ir+2]3456(->[c-]2c1)(->[c-]1cc(F)cc(F)c1-c1cccc[n]<-31)-...

Обрабатываем строку 1333...
   [Строка 1333] Санитизация не удалась: Explicit valence for atom # 54 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3cc(Oc4ccccc4)ccc3-c3cccc[n]<-13)->[c-]1ccc3ccc...

Обрабатываем строку 1334...
   [Строка 1334] Санитизация не удалась: Explicit valence for atom # 65 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccc(B(c4c(C)cc(C)cc4C)c4c(C)cc(C)cc4C)cc3-c3sc...

Обрабатываем строку 1335...
   [Строка 1335] Санитизация не удалась: Explicit valence for atom # 66 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccccc3-c3ccc(B(c4c(C)cc(C)cc4C)c4c(C)cc(C)cc4C...

Обрабатываем строку 1336...
   [Строка 1336] Санитизация не удалась: Explicit valence for atom # 63 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3ccc4ccccc4c3-c3cc4c(c[n]<-13)S(=O)(=O)c1ccccc1...

Обрабатываем строку 1337...
   [Строка 1337] Санитизация не удалась: Explicit valence for atom # 9 N, 5, is greater than permitted
   Успех! CCCCCCCC[n]12<-[Ir+3]3456789%10(->[O-]C(=O)c%11cccc[n]<-3%11)(->[c-]3cc(-c%11ccc...

Обрабатываем строку 1338...
   [Строка 1338] Санитизация не удалась: Explicit valence for atom # 9 N, 5, is greater than permitted
   Успех! CCCCCCCC[n]12<-[Ir+3]3456789%10(->[O-]C(=O)c%11cccc[n]<-3%11)(->[c-]3cc(-c%11ccc...

Обрабатываем строку 1339...
   [Строка 1339] Санитизация не удалась: Explicit valence for atom # 9 N, 5, is greater than permitted
   Успех! CCCCCCCC[n]12<-[Ir+3]3456789%10(->[O-]C(=O)c%11cccc[n]<-3%11)(->[c-]3cc(-c%11ccc...

Обрабатываем строку 1340...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1341...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1342...
   [Строка 1342] Санитизация не удалась: Explicit valence for atom # 39 N, 4, is greater than permitted
   Успех! c1cc[c-]2<-[Ir+3]34(->[c-]5ccccc5-c5oc6ccccc6[n]<-35)(->[n]3ccccc3-c3ccc[n-]<-43...

Обрабатываем строку 1343...
   [Строка 1343] Санитизация не удалась: Explicit valence for atom # 33 N, 4, is greater than permitted
   Успех! c1cc[c-]2<-[Ir+3]345(->[c-]6ccccc6-c6oc7ccccc7[n]<-36)(->[n]3cc[n]<-4c(-c4ccc[n-...

Обрабатываем строку 1344...
   [Строка 1344] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[n]3ccccc3-c3cccc[n]<-4...

Обрабатываем строку 1345...
   [Строка 1345] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]3456(->[c-]7ccccc7-c7ccc8ccccc8[n]<-37)(->[n]3ccc[n]<-4c3-c3[n]...

Обрабатываем строку 1346...
   [Строка 1346] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! Cc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3-c3ccc5ccccc...

Обрабатываем строку 1347...
   [Строка 1347] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! COc1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c5ccc6ccccc6[n]<-35)(->[c-]3ccccc3-c3ccc5cccc...

Обрабатываем строку 1348...
   [Строка 1348] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
   Успех! c1cc[c-]2<-[Ir+2]34(->[c-]5ccccc5-c5cccc[n]<-35)(->[n]3ccccc3-c2c1)->[n]1ccccc1-...

Обрабатываем строку 1349...
   [Строка 1349] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 15
   Успех! CN(C)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-c2c1)(->[c-]1ccccc1-c1cc(N(C)C)cc[n]<-31)-...

Обрабатываем строку 1350...
   [Строка 1350] Санитизация не удалась: Explicit valence for atom # 35 N, 5, is greater than permitted
   Успех! CN(C)c1cc[n]2<-[Ir+2]345(->[c-]6ccccc6-c2c1)(->[c-]1ccccc1-c1cc(N(C)C)cc[n]<-31)...

Обрабатываем строку 1351...
   [Строка 1351] Санитизация не удалась: Explicit valence for atom # 39 N, 5, is greater than permitted
   Успех! CN(C)c1cc[n]2<-[Ir+2]345(->[c-]6ccccc6-c2c1)(->[c-]1ccccc1-c1cc(N(C)C)cc[n]<-31)...

Обрабатываем строку 1352...
   [Строка 1352] Санитизация не удалась: Can't kekulize mol.  Unkekulized atoms: 37 39 40 41 42 43 45 46 48 49 50 51 52
   Успех! CN1c2ccccc2C(C)(C)C1c1oc2c3ccc[n]4<-[Ir+2]567(->[c-]8ccccc8-c8cccc[n]<-58)(->[c-...

Обрабатываем строку 1353...
   [Строка 1353] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! COC(=O)c1cccc(C(=CC(=O)c2cccs2)[O-]<-[Ir+3]23(->[c-]4ccccc4-c4oc(-c5ccccc5)c[n]<...

Обрабатываем строку 1354...
   [Строка 1354] Санитизация не удалась: Explicit valence for atom # 14 N, 5, is greater than permitted
   Успех! COC(=O)c1cccc(C(=CC(=O)c2cccs2)[O-]<-[Ir+3]2345(->[c-]6cc(Cl)ccc6-c6[n]<-2c2cccc...

Обрабатываем строку 1355...
   [Строка 1355] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! COC(=O)c1cccc(C(=CC(=O)c2cccs2)[O-]<-[Ir+3]2345(->[c-]6ccccc6-c6[n]<-2c2ccccc2[n...

Обрабатываем строку 1356...
   [Строка 1356] Санитизация не удалась: Explicit valence for atom # 15 N, 5, is greater than permitted
   Успех! COC(=O)c1cccc(C(=CC(=O)c2cccs2)[O-]<-[Ir+3]2345(->[c-]6cc(OC)c(OC)cc6-c6[n]<-2c2...

Обрабатываем строку 1357...
   [Строка 1357] Санитизация не удалась: Explicit valence for atom # 14 N, 5, is greater than permitted
   Успех! COC(=O)c1cccc(C(=CC(=O)c2cccs2)[O-]<-[Ir+3]2345(->[c-]6ccsc6-c6[n]<-2c2ccccc2[n]...

Обрабатываем строку 1358...
   [Строка 1358] Санитизация не удалась: Explicit valence for atom # 48 O, 2, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]34567(->[O-]c8cc[n]<-3c1c82)(->[c-]1cc(C(F)(F)F)ccc1-c1c2ccccc2...

Обрабатываем строку 1359...
   [Строка 1359] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]34567(->[O-]c8cc(C)[n]<-3c1c82)(->[c-]1cc(C(F)(F)F)ccc1-c1c2ccc...

Обрабатываем строку 1360...
   [Строка 1360] Санитизация не удалась: Explicit valence for atom # 48 O, 2, is greater than permitted
   Успех! Cc1cc[n]2<-[Ir+3]34567(->[O-]c8cc(-c9ccccc9)[n]<-3c1c82)(->[c-]1cc(C(F)(F)F)ccc1...

Обрабатываем строку 1361...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1362...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1363...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1364...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1365...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1366...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1367...
   Ошибка: Не найдены координационные атомы в L3

Обрабатываем строку 1368...
   [Строка 1368] Санитизация не удалась: Explicit valence for atom # 37 N, 4, is greater than permitted
   Успех! Cc1ccc2-c3c(F)cc(F)c[c-]3<-[Ir+3]345678(->[c-]9cc(F)cc(F)c9-c9ccc(C)[n]<-3[n]<-4...

Обрабатываем строку 1369...
   [Строка 1369] Санитизация не удалась: Explicit valence for atom # 33 O, 2, is greater than permitted
   Успех! Cc1ccc2-c3c(F)cc(F)c[c-]3<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37)(->[c-]3cc(F)cc(F...

Обрабатываем строку 1370...
   [Строка 1370] Санитизация не удалась: Explicit valence for atom # 37 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]1234(->[c-]5cc(F)cc(F)c5-c5ccc(C)[n]<-1[n]<-25)->[c-]1cc...

Обрабатываем строку 1371...
   [Строка 1371] Санитизация не удалась: Explicit valence for atom # 39 O, 2, is greater than permitted
   Успех! Cc1ccc2-c3c(F)cc(F)c[c-]3<-[Ir+3]345(->[O-]C(=CC(=O)C(C)(C)C)C(C)(C)C)(->[c-]6cc...

Обрабатываем строку 1372...
   [Строка 1372] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! FC(F)(F)c1c[c-]2<-[Ir+3]345678(->[O-]c9ccccc9-c9[n]<-3[n]<-4c(-c3ccccc3)[n]<-59-...

Обрабатываем строку 1373...
   [Строка 1373] Санитизация не удалась: Explicit valence for atom # 41 O, 2, is greater than permitted
   Успех! FC(F)(F)c1cc2-c3cccc[n]3<-[Ir+3]345678(->[O-]c9ccccc9-c9[n]<-3[n]<-4c(-c3ccccc3)...

Обрабатываем строку 1374...
   [Строка 1374] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]123456(->[c-]7c(-c8[n]<-1ccc[n]<-28)cc(C(F)(F)F)[n]<-3c7...

Обрабатываем строку 1375...
   [Строка 1375] Санитизация не удалась: Explicit valence for atom # 45 O, 2, is greater than permitted
   Успех! O=P(N=P([O-]<-[Ir+3]123456(->[c-]7c(-c8[n]<-1ccc[n]<-28)cc(C(F)(F)F)[n]<-3c7C(F)...

Обрабатываем строку 1376...
   [Строка 1376] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! O=P(N=P([O-]<-[Ir+3]123456(->[c-]7c(-c8[n]<-1cc(F)c[n]<-28)cc(C(F)(F)F)[n]<-3c7C...

Обрабатываем строку 1377...
   [Строка 1377] Санитизация не удалась: Explicit valence for atom # 47 O, 2, is greater than permitted
   Успех! O=P(N=P([O-]<-[Ir+3]123456(->[c-]7cc(C(F)(F)F)[n]<-1c(C(F)(F)F)c7-c1[n]<-2cc(F)c...

Обрабатываем строку 1378...
   [Строка 1378] Санитизация не удалась: Explicit valence for atom # 59 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(Oc4ccccc4)cc(Oc4ccccc4)cc3-c3cccc[n]<-13)->[...

Обрабатываем строку 1379...
   [Строка 1379] Санитизация не удалась: Explicit valence for atom # 60 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(Oc4ccccc4)cc(Oc4ccccc4)cc3-c3cccc[n]<-13)->[...

Обрабатываем строку 1380...
   [Строка 1380] Санитизация не удалась: Explicit valence for atom # 61 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(-c4cccc[n]<-14)cc1c4c3Oc3ccccc3N4c3ccccc3O1)...

Обрабатываем строку 1381...
   [Строка 1381] Санитизация не удалась: Explicit valence for atom # 60 O, 2, is greater than permitted
   Успех! CC(=O)C=C(C)[O-]<-[Ir+3]12(->[c-]3c(Oc4ccccc4)cc(Oc4ccccc4)cc3-c3cccc[n]<-13)->[...

Обрабатываем строку 1382...
   [Строка 1382] Санитизация не удалась: Explicit valence for atom # 61 O, 2, is greater than permitted

[20:59:01] Explicit valence for atom # 44 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 61 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 37 39 40
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 37 39 40 41 42 43 44
[20:59:01] Explicit valence for atom # 37 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 37 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 37 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 37 N, 5, is greater than permitted
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 41 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 33 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 49 O, 2, is greater than permitted
[20:59:01] Explicit valence for atom # 5 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 5 N, 5, is greater than permitted
[20:59:01] Explicit valence for atom # 51 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 54 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 51 N, 4, is greater than permitted
[20:59:01] Explicit valence for atom # 54 N, 4, is greater than permitted

In [16]:
import pandas as pd
from rdkit import Chem
import traceback

# ============================================================
# НАСТРОЙКИ
# ------------------------------------------------------------
# Ожидается, что у тебя уже есть DataFrame Ir с колонками 'L1', 'L2', 'L3'
# Например:
# Ir = pd.read_csv("your_ligands.csv")
#
# Код внизу:
# Ir = process_dataframe_canonical(Ir)
# Ir.to_csv("iridium_complexes_canonical.csv", index=False)
# ============================================================

HALOGENS = {"F", "Cl", "Br", "I"}
MAIN_DONORS = {"C", "N", "O", "S", "P"}  # то, что хотим "повернуть" к Ir


def find_primary_donor_atom(mol):
    """
    Возвращает индекс "главного" донорного атома лиганда по эвристике:
    приоритет (чем меньше score, тем важнее):
      0) C-  (циклометаллированный углерод)
      1) ароматический N
      2) O-
      3) S/P с зарядом <= 0
      10) галогены X- (F-, Cl-, Br-, I-), если больше ничего нет
    Если подходящих атомов нет, возвращает None.
    """
    candidates = []

    for atom in mol.GetAtoms():
        sym = atom.GetSymbol()
        ch = atom.GetFormalCharge()
        idx = atom.GetIdx()
        arom = atom.GetIsAromatic()

        score = None

        if sym == "C" and ch == -1:
            score = 0
        elif sym == "N" and arom:
            score = 1
        elif sym == "O" and ch == -1:
            score = 2
        elif sym in {"S", "P"} and ch <= 0:
            score = 3
        elif sym in HALOGENS and ch == -1:
            score = 10

        if score is not None:
            candidates.append((score, idx))

    if not candidates:
        return None

    candidates.sort()
    return candidates[0][1]


def canonical_ligand_smiles_rooted_at_donor(smiles):
    """
    Берёт SMILES лиганда и возвращает кортеж:
        (lig_smiles, donor_symbol, total_charge)

    где lig_smiles — канонический для данного лиганда SMILES,
    "заякоренный" (rootedAtAtom) на донорном атоме.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Некорректный SMILES лиганда: {smiles}")

    donor_idx = find_primary_donor_atom(mol)
    if donor_idx is None:
        raise ValueError(f"Не найден донорный атом в лигандe: {smiles}")

    lig_smiles = Chem.MolToSmiles(
        mol,
        isomericSmiles=True,
        rootedAtAtom=donor_idx
        # canonical здесь по сути выключается при rootedAtAtom,
        # но порядок и запись для данного root детерминированы.
    )

    donor_symbol = mol.GetAtomWithIdx(donor_idx).GetSymbol()
    total_charge = sum(a.GetFormalCharge() for a in mol.GetAtoms())

    return lig_smiles, donor_symbol, total_charge


def ir_charge_from_ligand_charges(lig_charges):
    """
    Считает заряд Ir так, чтобы комплекс в целом был нейтрален.
    Если хочешь всегда [Ir+3], можешь просто вернуть 3.
    """
    total_ligand_charge = sum(lig_charges)
    return -total_ligand_charge


def ir_charge_to_bracket(charge):
    """
    Преобразует целый заряд Ir в строку вида:
      0   -> [Ir]
      +3  -> [Ir+3]
      -2  -> [Ir-2]
    """
    if charge == 0:
        return "[Ir]"
    if charge > 0:
        return f"[Ir+{charge}]"
    # отрицательный заряд
    return f"[Ir{charge}]"


def make_canonical_ir_complex_smiles(l1, l2, l3):
    """
    Делает канонический (по нашим правилам) SMILES комплекса [Ir(L1)(L2)(L3)]:

    1) Каждый лиганд записывается SMILES, начинающимся с донорного атома.
    2) Лиганды сортируются:
        - сперва доноры C/N/O/S/P (MAIN_DONORS),
        - потом галогены (HALOGENS),
        - затем вообще прочее (на всякий случай).
    3) Заряд Ir выбирается так, чтобы суммарный заряд комплекса был 0.

    Возвращает строку вида:
        [Ir+q](Lig1_SMILES)(Lig2_SMILES)(Lig3_SMILES)
    """
    ligands_raw = [l1, l2, l3]
    ligands_info = []   # (priority_group, donor_symbol, lig_smiles, lig_charge)
    ligand_charges = []

    for smi in ligands_raw:
        if pd.isna(smi) or not isinstance(smi, str):
            raise ValueError(f"Один из лигандов пустой или не строка: {smi}")

        lig_smiles, donor_symbol, charge = canonical_ligand_smiles_rooted_at_donor(smi)
        ligand_charges.append(charge)

        # приоритет: 0 — C/N/O/S/P, 1 — галогены, 2 — другое
        if donor_symbol in MAIN_DONORS:
            group = 0
        elif donor_symbol in HALOGENS:
            group = 1
        else:
            group = 2

        ligands_info.append((group, donor_symbol, lig_smiles, charge))

    # сортируем по (group, lig_smiles) — это задаёт детерминированный порядок
    ligands_info_sorted = sorted(ligands_info, key=lambda x: (x[0], x[2]))
    ligand_smiles_sorted = [x[2] for x in ligands_info_sorted]

    # считаем заряд Ir (или поставь константу +3, если нужно строго [Ir+3])
    ir_q = ir_charge_from_ligand_charges(ligand_charges)
    ir_block = ir_charge_to_bracket(ir_q)

    complex_smiles = ir_block + "(" + ")(".join(ligand_smiles_sorted) + ")"
    return complex_smiles


def create_iridium_complex_from_ligands_canonical(l1, l2, l3, row_index=None):
    """
    Обёртка для одного ряда DataFrame:
    возвращает (complex_smiles, status_string)
    """
    try:
        complex_smiles = make_canonical_ir_complex_smiles(l1, l2, l3)
        return complex_smiles, "OK"
    except Exception as e:
        msg = f"Ошибка генерации SMILES (строка {row_index}): {e}"
        return None, msg


def process_dataframe_canonical(df):
    """
    Обрабатывает DataFrame с колонками 'L1', 'L2', 'L3' и
    добавляет:
      - 'Complex_SMILES_canonical'
      - 'Complex_Status_canonical'
    """
    df = df.copy()
    df['Complex_SMILES_canonical'] = None
    df['Complex_Status_canonical'] = None

    print(f"Обрабатываем {len(df)} строк для канонических Ir-комплексов...")

    for idx in df.index:
        try:
            l1 = df.at[idx, 'L1']
            l2 = df.at[idx, 'L2']
            l3 = df.at[idx, 'L3']

            smiles, status = create_iridium_complex_from_ligands_canonical(l1, l2, l3, row_index=idx)
            df.at[idx, 'Complex_SMILES_canonical'] = smiles
            df.at[idx, 'Complex_Status_canonical'] = status

            if status == "OK":
                print(f"[{idx}] OK: {smiles}")
            else:
                print(f"[{idx}] {status}")

        except Exception as e:
            print(f"[{idx}] Критическая ошибка: {e}")
            traceback.print_exc()
            df.at[idx, 'Complex_SMILES_canonical'] = None
            df.at[idx, 'Complex_Status_canonical'] = f"Exception: {str(e)}"

    print("Готово.")
    return df


# ============================================================
# ПРИМЕР ЗАПУСКА
# ------------------------------------------------------------
# Ir = pd.read_csv("your_ligands.csv")   # должен содержать L1, L2, L3
Ir = process_dataframe_canonical(Ir)
Ir.to_csv("iridium_complexes_canonical.csv", index=False)
Ir.to_pickle("iridium_complexes_canonical.pkl")
# ============================================================

Обрабатываем 1454 строк для канонических Ir-комплексов...
[0] OK: [Ir+3]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)(n1ccccc1C(=O)[O-])
[1] OK: [Ir+2]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)(n1ccccc1-c1ccccn1)
[2] OK: [Ir+2]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)(n1ccc(C(=O)O)cc1-c1cc(C(=O)O)ccn1)
[3] OK: [Ir+3]([O-]S(=O)(=O)c1ccc(P(c2ccc(S(=O)(=O)[O][Na])cc2)c2ccccc2P(c2ccc(S(=O)(=O)[O][Na])cc2)c2ccc(S(=O)(=O)[O][Na])cc2)cc1)([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)ccc1-c1ccccn1)
[4] OK: [Ir+2]([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccccn1)(n1ccc(P(=O)(OCC)OCC)cc1-c1cc(P(=O)(OCC)OCC)ccn1)
[5] OK: [Ir+2]([c-]1ccccc1-c1nccc2ccccc12)([c-]1ccccc1-c1nccc2ccccc12)(n1ccc(P(=O)(OCC)OCC)cc1-c1cc(P(=O)(OCC)OCC)ccn1)
[6] OK: [Ir+2]([c-]1ccccc1-c1ccc2ccccc2n1)([c-]1ccccc1-c1ccc2ccccc2n1)(n1ccc(P(=O)(OCC)OCC)cc1-c1cc(P(=O)(OCC)OCC)ccn1)
[7] OK: [Ir+2]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc(N(C)C)cc1-c1cc(N(C)C)ccn1)
[8] OK: [Ir+2]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc(N)cc1-c1cc(N)ccn1)
[9] OK: [Ir+2]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc(C)cc1-c1cc(C)ccn1)
[10] OK: [Ir+2]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc(OC)cc1-c1cc(OC)ccn1)
[11] OK: [Ir+2]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc(CO)cc1-c1cc(CO)ccn1)
[12] OK: [Ir]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc([N+](CC)(CC)CC)cc1-c1cc([N+](CC)(CC)CC)ccn1)
[13] OK: [Ir+2]([c-]1cc(C2NC(C(=O)O)CS2)ccc1-c1ccccn1)([c-]1cc(C2NC(C(=O)O)CS2)ccc1-c1ccccn1)(n1ccc(N(C)C)cc1-c1cc(N(C)C)ccn1)
[14] OK: [Ir+2]([c-]1cc(C2NC(C(=O)O)CCS2)ccc1-c1ccccn1)([c-]1cc(C2NC(C(=O)O)CCS2)ccc1-c1ccccn1)(n1ccc(N(C)C)cc1-c1cc(N(C)C)ccn1)
[15] OK: [Ir+3]([c-]1c(-c2nccc3ccccc23)cc(C(F)(F)F)nc1C(F)(F)F)([c-]1c(-c2nccc3ccccc23)cc(C(F)(F)F)nc1C(F)(F)F)(n1ccccc1-c1cc(C)n[n-]1)
[16] OK: [Ir+3]([c-]1c(-c2nccc3ccccc23)cc(C(F)(F)F)nc1C(F)(F)F)([c-]1c(-c2nccc3ccccc23)cc(C(F)(F)F)nc1C(F)(F)F)(n1ccccc1-c1cc(C(F)(F)F)n[n-]1)
[17] OK: [Ir+3]([c-]1c(-c2nccc3ccccc23)cc(C(F)(F)F)nc1C(F)(F)F)([c-]1c(-c2nccc3ccccc23)cc(C(F)(F)F)nc1C(F)(F)F)(n1ccccc1-c1cc(-c2ccccc2)n[n-]1)
[18] OK: [Ir+3]([c-]1cc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nn(CCCCCCCC)nc2c1-c1nccc2ccccc12)([c-]1cc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)c2nn(CCCCCCCC)nc2c1-c1nccc2ccccc12)(n1(-c2ccc(S(=O)(=O)c3ccc(-c4ccc(C(=O)[O-])nc4)cc3)cc2)c2ccc(C(C)(C)C)cc2c2cc(C(C)(C)C)ccc21)
[19] OK: [Ir+2]([c-]1cc(C)c(C)cc1-c1cnc2cc(C)c(C)cc2n1)([c-]1cc(C)c(C)cc1-c1cnc2cc(C)c(C)cc2n1)(n1ccccc1-c1ccccn1)
[20] OK: [Ir+2]([c-]1cc(C)c(C)cc1-c1cnc2cc(F)c(F)cc2n1)([c-]1cc(C)c(C)cc1-c1cnc2cc(F)c(F)cc2n1)(n1ccccc1-c1ccccn1)
[21] OK: [Ir+2]([c-]1cc(F)ccc1-c1cnc2ccccc2n1)([c-]1cc(F)ccc1-c1cnc2ccccc2n1)(n1ccccc1-c1ccccn1)
[22] OK: [Ir+2]([c-]1cc(F)ccc1-c1cnc2cc(C)c(C)cc2n1)([c-]1cc(F)ccc1-c1cnc2cc(C)c(C)cc2n1)(n1ccccc1-c1ccccn1)
[23] OK: [Ir+2]([c-]1cc(F)ccc1-c1cnc2cc(F)c(F)cc2n1)([c-]1cc(F)ccc1-c1cnc2cc(F)c(F)cc2n1)(n1ccccc1-c1ccccn1)
[24] OK: [Ir+2]([c-]1c(-c2cnc3ccccc3n2)cc(F)c(F)c1F)([c-]1c(-c2cnc3ccccc3n2)cc(F)c(F)c1F)(n1ccccc1-c1ccccn1)
[25] OK: [Ir+2]([c-]1c(-c2cnc3cc(C)c(C)cc3n2)cc(F)c(F)c1F)([c-]1c(-c2cnc3cc(C)c(C)cc3n2)cc(F)c(F)c1F)(n1ccccc1-c1ccccn1)
[26] OK: [Ir+2]([c-]1c(-c2cnc3cc(F)c(F)cc3n2)cc(F)c(F)c1F)([c-]1c(-c2cnc3cc(F)c(F)cc3n2)cc(F)c(F)c1F)(n1ccccc1-c1ccccn1)
[27] OK: [Ir+2]([c-]1cc(Cl)c(C(F)(F)F)cc1-c1cc(C)c2ccccc2n1)([c-]1cc(Cl)c(C(F)(F)F)cc1-c1cc(C)c2ccccc2n1)(n1ccc(C)cc1-c1cc(C)ccn1)
[28] OK: [Ir+2]([c-]1cc(Cl)c(C(F)(F)F)cc1-c1cc(C)c2ccccc2n1)([c-]1cc(Cl)c(C(F)(F)F)cc1-c1cc(C)c2ccccc2n1)(n1ccc(C(C)(C)C)cc1-c1cc(C(C)(C)C)ccn1)
[29] OK: [Ir+2](P(c1ccccc1)(c1ccccc1)c1ccccc1Oc1ccccc1P(c1ccccc1)c1ccccc1)([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccccn1)
[30] OK: [Ir+2]([c-]1ccccc1-c1nnc(-c2ccccc2)n1-c1ccccc1)([c-]1ccccc1-c1nnc(-c2ccccc2)n1-c1ccccc1)(n1(-c2ccccn2)cccn1)
[31] OK: [Ir+2]([c-]1ccccc1-c1nnc(-c2ccccc2)n1-c1ccccc1)([c-]1ccccc1-c1nnc(-c2ccccc2)n1-c1ccccc1)(n1ccc(N(C)C)cc1-n1cccn1)
[32] OK: [Ir+2]([c-]1ccccc1-c1nnc(-c2ccccc2)n1-c1ccccc1)([c-]1ccccc1-c1nnc(-c2ccccc2)n1-c1ccccc1)([c-]1n(C)cc[n+]1C[n+]1[c-]n(C)cc1)
[33] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1cc(F)cc(F)c1-c1nccc2ccccc12)([c-]1cc(F)cc(F)c1-c1nccc2ccccc12)
[34] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(F)cc(F)cc1-c1nccc2ccccc12)([c-]1c(F)cc(F)cc1-c1nccc2ccccc12)
[35] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1cc(F)c(-c2ccc(C(F)(F)F)cc2)c(F)c1-c1nccc2ccccc12)([c-]1cc(F)c(-c2ccc(C(F)(F)F)cc2)c(F)c1-c1nccc2ccccc12)
[36] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1cc(F)c(-c2ccc(C#N)cc2)c(F)c1-c1nccc2ccccc12)([c-]1cc(F)c(-c2ccc(C#N)cc2)c(F)c1-c1nccc2ccccc12)
[37] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1cc(F)c(-c2ccc(C(=O)c3ccccc3)cc2)c(F)c1-c1nccc2ccccc12)([c-]1cc(F)c(-c2ccc(C(=O)c3ccccc3)cc2)c(F)c1-c1nccc2ccccc12)
[38] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1cc(F)c(-c2ccc(C(=O)OC)cc2)c(F)c1-c1nccc2ccccc12)([c-]1cc(F)c(-c2ccc(C(=O)OC)cc2)c(F)c1-c1nccc2ccccc12)
[39] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(C#N)ccc1-c1ncc(C#N)c2ccccc12)([c-]1cc(C#N)ccc1-c1ncc(C#N)c2ccccc12)
[40] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(C(C)(C)C)ccc1-c1ncc(C#N)c2ccccc12)([c-]1cc(C(C)(C)C)ccc1-c1ncc(C#N)c2ccccc12)
[41] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(C)cc(C)cc1-c1ncc(C#N)c2ccccc12)([c-]1c(C)cc(C)cc1-c1ncc(C#N)c2ccccc12)
[42] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(-c2ccccn2)cc2c3ccccc3n3c4ncccc4c1c23)([c-]1c(-c2ccccn2)cc2c3ccccc3n3c4ncccc4c1c23)
[43] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(-c2ccccn2)cc2c3ccccc3n3c4ncccc4c1c23)([c-]1c(-c2ccccn2)cc2c3cccnc3n3c4ccccc4c1c23)
[44] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(-c2cc(C(F)(F)F)ccn2)cc2c3ccccc3n3c4ncccc4c1c23)([c-]1c(-c2cc(C(F)(F)F)ccn2)cc2c3ccccc3n3c4ncccc4c1c23)
[45] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(-c2cc(C(F)(F)F)ccn2)cc2c3ccccc3n3c4ncccc4c1c23)([c-]1c(-c2cc(C(F)(F)F)ccn2)cc2c3cccnc3n3c4ccccc4c1c23)
[46] OK: [Ir+3]([c-]1cc(F)cc(F)c1-c1ccccn1)([c-]1cc(F)cc(F)c1-c1ccccn1)([n-]1cccc1/C(=C1/C=CC=N1)c1ccccc1)
[47] OK: [Ir+3]([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccccn1)([n-]1cccc1/C(=C1/C=CC=N1)c1ccccc1)
[48] OK: [Ir+3]([c-]1ccccc1-c1nccc2ccccc12)([c-]1ccccc1-c1nccc2ccccc12)([n-]1cccc1/C(=C1/C=CC=N1)c1ccccc1)
[49] OK: [Ir+3]([c-]1cc(N(c2ccccc2)c2ccccc2)ccc1-c1nccc2ccccc12)([c-]1cc(N(c2ccccc2)c2ccccc2)ccc1-c1nccc2ccccc12)([n-]1cccc1/C(=C1/C=CC=N1)c1ccccc1)
[50] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(F)cc(F)c1-c1ccccn1)([c-]1cc(F)cc(F)c1-c1ccccn1)
[51] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccccn1)
[52] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccccc1-c1nccc2ccccc12)([c-]1ccccc1-c1nccc2ccccc12)
[53] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(N(c2ccccc2)c2ccccc2)ccc1-c1nccc2ccccc12)([c-]1cc(N(c2ccccc2)c2ccccc2)ccc1-c1nccc2ccccc12)
[54] OK: [Ir+2]([c-]1cc(CC(c2ccccc2)c2ccccc2)ccc1-c1ccccn1)([c-]1cc(CC(c2ccccc2)c2ccccc2)ccc1-c1ccccn1)(n1ccccc1-c1ccccn1)
[55] OK: [Ir+2]([c-]1cc(CC(c2ccccc2)c2ccccc2)ccc1-c1ccccn1)([c-]1cc(CC(c2ccccc2)c2ccccc2)ccc1-c1ccccn1)(n1(-c2ccccc2)ccc(-c2ccccn2)n1)
[56] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(-c2ccccn2)cc2c3ccccc3n3c4ccccc4c1c23)([c-]1c(-c2ccccn2)cc2c3ccccc3n3c4ccccc4c1c23)
[57] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(-c2cc(C(F)(F)F)ccn2)cc2c3ccccc3n3c4ccccc4c1c23)([c-]1c(-c2cc(C(F)(F)F)ccn2)cc2c3ccccc3n3c4ccccc4c1c23)
[58] Ошибка генерации SMILES (строка 58): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)N(C(C)C)C(C)C
[59] Ошибка генерации SMILES (строка 59): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)N(C(C)C)C(C)C
[60] Ошибка генерации SMILES (строка 60): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)N(C(C)C)C(C)C
[61] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(-c2nccc3ccccc23)sc2ccccc12)([c-]1cc(F)cc(F)c1-c1ccccn1)
[62] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(-c2nccc3ccccc23)sc2ccccc12)([c-]1ccccc1-c1ccccn1)
[63] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(-c2nccc3ccccc23)sc2ccccc12)([c-]1ccccc1-c1nc2ccccc2nc1-c1ccccc1)
[64] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccccc1-c1ncnc2cc(OC)c(OC)cc12)([c-]1ccccc1-c1ncnc2cc(OC)c(OC)cc12)
[65] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(C(C)(C)C)ccc1-c1ncnc2cc(OC)c(OC)cc12)([c-]1cc(C(C)(C)C)ccc1-c1ncnc2cc(OC)c(OC)cc12)
[66] OK: [Ir+2]([c-]1ccccc1-c1nnc(C(F)(F)F)n1-c1ccccc1)([c-]1ccccc1-c1nnc(C(F)(F)F)n1-c1ccccc1)(n1ccccc1-c1ccccn1)
[67] OK: [Ir+2]([c-]1ccccc1-c1nnc(C(F)(F)F)n1-c1ccccc1)([c-]1ccccc1-c1nnc(C(F)(F)F)n1-c1ccccc1)(n1ccc(C)cc1-c1cc(C)ccn1)
[68] OK: [Ir+2]([c-]1ccccc1-c1nnc(C(F)(F)F)n1-c1ccccc1)([c-]1ccccc1-c1nnc(C(F)(F)F)n1-c1ccccc1)(n1(-c2ccccc2)ccnc1-c1ccccn1)
[69] OK: [Ir+2]([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccccn1)(n1ccc(C)cc1-c1cc(/C=N/O)ccn1)
[70] OK: [Ir+2]([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccccn1)(n1ccc(C)cc1-c1cc(C#N)ccn1)
[71] OK: [Ir+2]([c-]1ccccc1-c1nc2cc3ccccc3cc2n1CCC(C)C)([c-]1ccccc1-c1nc2cc3ccccc3cc2n1CCC(C)C)(n1ccccc1-c1ccccn1)
[72] OK: [Ir+2]([c-]1ccccc1-c1nc2cc3ccccc3cc2n1CCC(C)C)([c-]1ccccc1-c1nc2cc3ccccc3cc2n1CCC(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[73] OK: [Ir+2]([c-]1ccccc1-c1nc2cc3ccccc3cc2n1CCC(C)C)([c-]1ccccc1-c1nc2cc3ccccc3cc2n1CCC(C)C)(n1cccc2ccc3cccnc3c12)
[74] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccc(OC)cc1-c1cc(C(F)(F)F)ccn1)([c-]1ccc(OC)cc1-c1cc(C(F)(F)F)ccn1)
[75] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(OC)cccc1-c1cc(C(F)(F)F)ccn1)([c-]1ccc(OC)cc1-c1cc(C(F)(F)F)ccn1)
[76] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(OC)cccc1-c1cc(C(F)(F)F)ccn1)([c-]1c(OC)cccc1-c1cc(C(F)(F)F)ccn1)
[77] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccc(OC)cc1-c1ccc(C(F)(F)F)cn1)([c-]1ccc(OC)cc1-c1ccc(C(F)(F)F)cn1)
[78] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(OC)cccc1-c1ccc(C(F)(F)F)cn1)([c-]1ccc(OC)cc1-c1ccc(C(F)(F)F)cn1)
[79] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1c(OC)cccc1-c1ccc(C(F)(F)F)cn1)([c-]1c(OC)cccc1-c1ccc(C(F)(F)F)cn1)
[80] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccc2ccc3cccc4c5nc6cc(-c7ccc(N(c8ccccc8)c8ccccc8)cc7)c(-c7ccc(N(c8ccccc8)c8ccccc8)cc7)cc6nc5c1c2c34)([c-]1ccc2ccc3cccc4c5nc6cc(-c7ccc(N(c8ccccc8)c8ccccc8)cc7)c(-c7ccc(N(c8ccccc8)c8ccccc8)cc7)cc6nc5c1c2c34)
[81] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccc2ccc3cccc4c5nc6cc(-c7ccc(CCCCCC)s7)c(-c7ccc(CCCCCC)s7)cc6nc5c1c2c34)([c-]1ccc2ccc3cccc4c5nc6cc(-c7ccc(CCCCCC)s7)c(-c7ccc(CCCCCC)s7)cc6nc5c1c2c34)
[82] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccc2ccc3cccc4c5nc6cc(-c7ccc(N(c8ccccc8)c8ccccc8)s7)c(-c7ccc(N(c8ccccc8)c8ccccc8)s7)cc6nc5c1c2c34)([c-]1ccc2ccc3cccc4c5nc6cc(-c7ccc(N(c8ccccc8)c8ccccc8)s7)c(-c7ccc(N(c8ccccc8)c8ccccc8)s7)cc6nc5c1c2c34)
[83] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(-c2ccc(N(c3ccc(C(C)(C)C)cc3)c3ccc(C(C)(C)C)cc3)cc2)cc2c1c1nc3cc4ccccc4cc3nc1c1ccc(-c3ccc(N(c4ccc(C(C)(C)C)cc4)c4ccc(C(C)(C)C)cc4)cc3)cc21)([c-]1cc(-c2ccc(N(c3ccc(C(C)(C)C)cc3)c3ccc(C(C)(C)C)cc3)cc2)cc2c1c1nc3cc4ccccc4cc3nc1c1ccc(-c3ccc(N(c4ccc(C(C)(C)C)cc4)c4ccc(C(C)(C)C)cc4)cc3)cc21)
[84] OK: [Ir+3]([O-]/C(C)=C\C(C)=N\c1ccccc1)([c-]1c(-c2ccc3ccccc3n2)sc2ccccc12)([c-]1c(-c2ccc3ccccc3n2)sc2ccccc12)
[85] OK: [Ir+3](S=C([S-])N(C(C)C)C(C)C)([c-]1c(-c2ccc3ccccc3n2)sc2ccccc12)([c-]1c(-c2ccc3ccccc3n2)sc2ccccc12)
[86] Ошибка генерации SMILES (строка 86): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)c1ccccc1
[87] OK: [Ir+3]([O-]/C(C)=C\C(C)=N\c1ccccc1)([c-]1c(-c2nc3ccccc3c3ccccc23)sc2ccccc12)([c-]1c(-c2nc3ccccc3c3ccccc23)sc2ccccc12)
[88] Ошибка генерации SMILES (строка 88): Не найден донорный атом в лигандe: C/C(=C/C(C)=N/c1ccccc1)[N-]c1ccccc1
[89] Ошибка генерации SMILES (строка 89): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)c1ccccc1
[90] Ошибка генерации SMILES (строка 90): Не найден донорный атом в лигандe: C1CN=C2[N-]CCCN2C1
[91] OK: [Ir+2]([c-]1ccccc1-c1nccc2ccccc12)([c-]1ccccc1-c1nccc2ccccc12)(n1c2ccc3ccccc3c2nc2ccc3nccnc3c12)
[92] OK: [Ir+2]([c-]1cc2c(cc1-c1nccc3ccccc13)C(C)(C)c1ccccc1-2)([c-]1cc2c(cc1-c1nccc3ccccc13)C(C)(C)c1ccccc1-2)(n1c2ccc3ccccc3c2nc2ccc3nccnc3c12)
[93] OK: [Ir+2]([c-]1cc(F)ccc1-c1nc2ccccc2n1CCC(C)C)([c-]1cc(F)ccc1-c1nc2ccccc2n1CCC(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[94] OK: [Ir+2]([c-]1ccsc1-c1nc2ccccc2n1CCC(C)C)([c-]1ccsc1-c1nc2ccccc2n1CCC(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[95] OK: [Ir+2]([c-]1cc(F)ccc1-c1nc2ccccc2n1CCC(C)C)([c-]1cc(F)ccc1-c1nc2ccccc2n1CCC(C)C)(n1c(-c2cccs2)c(-c2cccs2)nc2c3cccnc3c3ncccc3c12)
[96] OK: [Ir+2]([c-]1ccsc1-c1nc2ccccc2n1CCC(C)C)([c-]1ccsc1-c1nc2ccccc2n1CCC(C)C)(n1c(-c2cccs2)c(-c2cccs2)nc2c3cccnc3c3ncccc3c12)
[97] OK: [Ir+3]([c-]1ccc(OC)cc1-c1nc2ccccc2n1-c1ccccc1)([c-]1ccc(OC)cc1-c1nc2ccccc2n1-c1ccccc1)(n1c(-c2ccccn2)[n-]c2ccccc12)
[98] OK: [Ir+2]([c-]1ccccc1-c1nc2ccccc2n1C(C)C)([c-]1ccccc1-c1nc2ccccc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[99] OK: [Ir+2]([c-]1ccccc1-c1nc2cc(Cl)c(Cl)cc2n1C(C)C)([c-]1ccccc1-c1nc2cc(Cl)c(Cl)cc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[100] OK: [Ir+2]([c-]1ccccc1-c1nc2cc(C(F)(F)F)ccc2n1C(C)C)([c-]1ccccc1-c1nc2cc(C(F)(F)F)ccc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[101] OK: [Ir+2]([c-]1ccccc1-c1nc2ccc(OC)cc2n1C(C)C)([c-]1ccccc1-c1nc2ccc(OC)cc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[102] OK: [Ir+2]([c-]1cc(C(F)(F)F)ccc1-c1nc2ccccc2n1C(C)C)([c-]1cc(C(F)(F)F)ccc1-c1nc2ccccc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[103] OK: [Ir+2]([c-]1cc(OC)ccc1-c1nc2ccccc2n1C(C)C)([c-]1cc(OC)ccc1-c1nc2ccccc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[104] OK: [Ir+2]([c-]1cc(C(F)(F)F)ccc1-c1nc2cc(C(F)(F)F)ccc2n1C(C)C)([c-]1cc(C(F)(F)F)ccc1-c1nc2cc(C(F)(F)F)ccc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[105] OK: [Ir+2]([c-]1cc(OC)ccc1-c1nc2ccc(OC)cc2n1C(C)C)([c-]1cc(OC)ccc1-c1nc2ccc(OC)cc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[106] OK: [Ir+2]([c-]1cc(OC)ccc1-c1nc2cc(C(F)(F)F)ccc2n1C(C)C)([c-]1cc(OC)ccc1-c1nc2cc(C(F)(F)F)ccc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[107] OK: [Ir+2]([c-]1cc(C(F)(F)F)ccc1-c1nc2ccc(OC)cc2n1C(C)C)([c-]1cc(C(F)(F)F)ccc1-c1nc2ccc(OC)cc2n1C(C)C)(n1ccc(C)cc1-c1cc(C)ccn1)
[108] Ошибка генерации SMILES (строка 108): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)c1ccccc1
[109] Ошибка генерации SMILES (строка 109): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)c1ccccc1
[110] Ошибка генерации SMILES (строка 110): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)c1ccccc1
[111] Ошибка генерации SMILES (строка 111): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)N(C(C)C)C(C)C
[112] Ошибка генерации SMILES (строка 112): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)N(C(C)C)C(C)C
[113] Ошибка генерации SMILES (строка 113): Не найден донорный атом в лигандe: CC(C)/N=C(/[N-]C(C)C)N(C(C)C)C(C)C
[114] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cccc(C(F)(F)F)c1-c1nc2ccccc2s1)([c-]1cccc(C(F)(F)F)c1-c1nc2ccccc2s1)
[115] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccc(C(F)(F)F)cc1-c1nc2ccccc2s1)([c-]1ccc(C(F)(F)F)cc1-c1nc2ccccc2s1)
[116] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(C(F)(F)F)ccc1-c1nc2ccccc2s1)([c-]1cc(C(F)(F)F)ccc1-c1nc2ccccc2s1)
[117] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cccc(C(F)(F)F)c1-c1nc2ccccc2n1-c1ccccc1)([c-]1cccc(C(F)(F)F)c1-c1nc2ccccc2n1-c1ccccc1)
[118] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccc(C(F)(F)F)cc1-c1nc2ccccc2n1-c1ccccc1)([c-]1ccc(C(F)(F)F)cc1-c1nc2ccccc2n1-c1ccccc1)
[119] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(C(F)(F)F)ccc1-c1nc2ccccc2n1-c1ccccc1)([c-]1cc(C(F)(F)F)ccc1-c1nc2ccccc2n1-c1ccccc1)
[120] OK: [Ir+3]([O-]/C(C)=C\C(C)=N\c1ccccc1)([c-]1ccccc1-c1nc2ccccc2c2ccccc12)([c-]1ccccc1-c1nc2ccccc2c2ccccc12)
[121] Ошибка генерации SMILES (строка 121): Не найден донорный атом в лигандe: C/C(=C/C(C)=N/c1ccccc1)[N-]c1ccccc1
[122] OK: [Ir+3]([O-]/C(C)=C\C(C)=N\C1CCCCC1)([c-]1ccccc1-c1nc2ccccc2c2ccccc12)([c-]1ccccc1-c1nc2ccccc2c2ccccc12)
[123] OK: [Ir+3]([O-]/C(C)=C\C(C)=N\c1ccccc1)([c-]1ccccc1-c1ncc(C#N)c2ccccc12)([c-]1ccccc1-c1ncc(C#N)c2ccccc12)
[124] Ошибка генерации SMILES (строка 124): Не найден донорный атом в лигандe: C/C(=C/C(C)=N/c1c(C)cccc1C)[N-]c1c(C)cccc1C
[125] Ошибка генерации SMILES (строка 125): Не найден донорный атом в лигандe: Cc1cc(C)c(/C(=N\C(C)C)[N-]C(C)C)c(C)c1
[126] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1cccc2c1c1nc3ccccc3nc1c1ccccc21)([c-]1cccc2c1c1nc3ccccc3nc1c1ccccc21)
[127] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(-c2ccc(N(c3ccc(C(C)(C)C)cc3)c3ccc(C(C)(C)C)cc3)cc2)cc2c1c1nc3ccccc3nc1c1ccc(-c3ccc(N(c4ccc(C(C)(C)C)cc4)c4ccc(C(C)(C)C)cc4)cc3)cc21)([c-]1cc(-c2ccc(N(c3ccc(C(C)(C)C)cc3)c3ccc(C(C)(C)C)cc3)cc2)cc2c1c1nc3ccccc3nc1c1ccc(-c3ccc(N(c4ccc(C(C)(C)C)cc4)c4ccc(C(C)(C)C)cc4)cc3)cc21)
[128] OK: [Ir+3]([c-]1ccccc1-c1ccc2ccccc2n1)([c-]1ccccc1-c1ccc2ccccc2n1)(n1c(-c2ccccn2)[n-]c2ccccc12)
[129] OK: [Ir+3]([c-]1ccccc1-c1nccc2ccccc12)([c-]1ccccc1-c1nccc2ccccc12)(n1c(-c2ccccn2)[n-]c2ccccc12)
[130] OK: [Ir+3]([O-]/C(=C\C(=O)C(C)(C)C)C(C)(C)C)([c-]1c(-c2nccc3ccccc23)sc2ccsc12)([c-]1c(-c2nccc3ccccc23)sc2ccsc12)
[131] OK: [Ir+3]([O-]/C(=C\C(=O)c1ccc(Br)cc1)c1ccc(Br)cc1)([c-]1c(-c2cnc3ccccc3n2)sc2ccccc12)([c-]1c(-c2cnc3ccccc3n2)sc2ccccc12)
[132] OK: [Ir+3]([O-]/C(=C\C(=O)c1cccs1)C(F)(F)F)([c-]1c(-c2nc3ccccc3c3ccccc23)sc2ccccc12)([c-]1c(-c2nc3ccccc3c3ccccc23)sc2ccccc12)
[133] OK: [Ir+3]([c-]1c(-c2nc3ccccc3c3ccccc23)sc2ccccc12)([c-]1c(-c2nc3ccccc3c3ccccc23)sc2ccccc12)(n1c(-c2ccccc2)cc(/C([O-])=C/C(=O)c2cccs2)c2ccccc12)
[134] OK: [Ir+3]([O-]/C(=C\C(=O)c1cccs1)C(F)(F)F)([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)
[135] OK: [Ir+3]([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)(n1c(-c2ccccc2)cc(/C([O-])=C/C(=O)c2cccs2)c2ccccc12)
[136] OK: [Ir+3]([O-]/C(=C\C(=O)C(F)(F)F)C(F)(F)F)([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)
[137] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)([c-]1ccccc1-c1cc(C(=O)OC)c2ccccc2n1)
[138] OK: [Ir+2]([c-]1cc2ccccc2cc1-c1cc(C(=O)OCC)c2ccccc2n1)([c-]1cc2ccccc2cc1-c1cc(C(=O)OCC)c2ccccc2n1)(n1ccccc1-c1ccccn1)
[139] OK: [Ir+2]([c-]1cc2ccccc2cc1-c1cc(C(=O)OCCOCC)c2cc(OC)ccc2n1)([c-]1cc2ccccc2cc1-c1cc(C(=O)OCCOCC)c2cc(OC)ccc2n1)(n1ccccc1-c1ccccn1)
[140] OK: [Ir+2]([c-]1cc2ccccc2cc1-c1cc(C(=O)OCC)c2cc(F)ccc2n1)([c-]1cc2ccccc2cc1-c1cc(C(=O)OCC)c2cc(F)ccc2n1)(n1ccccc1-c1ccccn1)
[141] OK: [Ir+2]([c-]1ccc2ccccc2c1-c1cc(C(=O)OCC)c2ccccc2n1)([c-]1ccc2ccccc2c1-c1cc(C(=O)OCC)c2ccccc2n1)(n1ccccc1-c1ccccn1)
[142] OK: [Ir+2]([c-]1ccc2ccccc2c1-c1cc(C(=O)OCC)c2cc(OC)ccc2n1)([c-]1ccc2ccccc2c1-c1cc(C(=O)OCC)c2cc(OC)ccc2n1)(n1ccccc1-c1ccccn1)
[143] OK: [Ir+2]([c-]1ccc2ccccc2c1-c1cc(C(=O)OCC)c2cc(F)ccc2n1)([c-]1ccc2ccccc2c1-c1cc(C(=O)OCC)c2cc(F)ccc2n1)(n1ccccc1-c1ccccn1)
[144] OK: [Ir+3]([c-]1ccc2cccc3c(=O)n4c5ccccc5nc4c1c23)([c-]1ccc2cccc3c(=O)n4c5ccccc5nc4c1c23)(n1ccccc1-c1cc(C(F)(F)F)n[n-]1)
[145] OK: [Ir+3]([c-]1cc(N(c2ccccc2)c2ccccc2)c2cccc3c(=O)n4c5ccccc5nc4c1c23)([c-]1cc(N(c2ccccc2)c2ccccc2)c2cccc3c(=O)n4c5ccccc5nc4c1c23)(n1ccccc1-c1cc(C(F)(F)F)n[n-]1)
[146] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(-c2ccc(CCCCCC)s2)cc2c1c1nc3ccccc3nc1c1ccc(-c3ccc(CCCCCC)s3)cc21)([c-]1cc(-c2ccc(CCCCCC)s2)cc2c1c1nc3ccccc3nc1c1ccc(-c3ccc(CCCCCC)s3)cc21)
[147] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cccc2c1c1nc3cc(-c4ccc(CCCCCC)s4)c(-c4ccc(CCCCCC)s4)cc3nc1c1ccccc21)([c-]1cccc2c1c1nc3cc(-c4ccc(CCCCCC)s4)c(-c4ccc(CCCCCC)s4)cc3nc1c1ccccc21)
[148] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc2c1c1nc3ccccc3nc1c1ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc21)([c-]1cc(-c2ccc(N(c3ccccc3)c3ccccc3)cc2)cc2c1c1nc3ccccc3nc1c1ccc(-c3ccc(N(c4ccccc4)c4ccccc4)cc3)cc21)
[149] OK: [Ir+3]([O-]/C(C)=C\C(C)=O)([c-]1cccc2c1c1nc3cc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)c(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3nc1c1ccccc21)([c-]1cccc2c1c1nc3cc(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)c(-c4ccc(N(c5ccccc5)c5ccccc5)cc4)cc3nc1c1ccccc21)
[150] OK: [Ir+3]([c-]1cc(F)nc(F)c1-c1cc(-c2c(C)cc(C)cc2C)ncn1)([c-]1cc(F)nc(F)c1-c1cc(-c2c(C)cc(C)cc2C)ncn1)(n1ccccc1C(=O)[O-])
[151] OK: [Ir+3]([c-]1cc(F)nc(F)c1-c1cc(-c2c(C)cc(C)cc2C)ncn1)([c-]1cc(F)nc(F)c1-c1cc(-c2c(C)cc(C)cc2C)ncn1)(n1ccccc1-c1cc(C(F)(F)F)n[n-]1)
[152] OK: [Ir+3]([c-]1cc(F)nc(F)c1-c1cc(-c2c(C)cc(C)cc2C)ncn1)([c-]1cc(F)nc(F)c1-c1cc(-c2c(C)cc(C)cc2C)ncn1)(n1[n-]c(-c2ccccn2)nc1C(F)(F)F)

# Opt SMILES

In [18]:
Ir_2 = pd.read_csv('iridium_complexes_canonical.csv')
Ir_2

,L1,L2,L3,Counterion,Abbreviation_in_the_article,Charge,Max_wavelength(nm),PLQY,tau(s*10^-6),Solvent,DOI,Notes,PLQY_in_train,Complex_SMILES,Complex_Status,Complex_SMILES_canonical,Complex_Status_canonical
0,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C([O-])c1ccccn1,NaN,1,0,553,0.2500,4.32,CH2Cl2,10.3390/molecules27010232,NaN,1,O=C1[O-]<-[Ir+3]234567(->[c-]8cc(-c9[n]<-2c2c%...,OK,[Ir+3]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2cc...,OK
1,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,c1ccc(-c2ccccn2)nc1,FP(F)(F)(F)(F)F,2,1,570,0.1700,6.14,CH2Cl2,10.3390/molecules27010232,NaN,1,c1ccc(-[n]23<-[Ir+2]456789(->[c-]%10cc(-c2[n]<...,OK,[Ir+2]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2cc...,OK
2,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccnc(-c2cc(C(=O)O)ccn2)c1,FP(F)(F)(F)(F)F,3,1,595,0.1400,0.82,CH3OH,10.3390/molecules27010232,NaN,1,O=C(O)c1cc[n]2<-[Ir+2]345678(->[c-]9cc(-c%10[n...,OK,[Ir+2]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2cc...,OK
3,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=S(=O)([O-])c1ccc(P(c2ccc(S(=O)(=O)O[Na])cc2)...,NaN,4,0,555,0.0435,41.87,PBS,10.3390/molecules27010232,NaN,1,O=S(=O)([O][Na])c1ccc(P(c2ccc(S(=O)(=O)[O][Na]...,OK,[Ir+3]([O-]S(=O)(=O)c1ccc(P(c2ccc(S(=O)(=O)[O]...,OK
4,[c-]1ccccc1-c1ccccn1,[c-]1ccccc1-c1ccccn1,CCOP(=O)(OCC)c1ccnc(-c2cc(P(=O)(OCC)OCC)ccn2)c1,FP(F)(F)(F)(F)F,Ir(ppy)2bP,1,667,0.0020,NaN,CH3OH,10.1002/adhm.202100706,NaN,1,CCOP(=O)(OCC)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-...,OK,[Ir+2]([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccc...,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,O=C([O-])c1ccccn1,NaN,(m-CzFSOPy)2IrPic,0,554,0.3810,0.64,CH2Cl2,10.1016/j.dyepig.2018.07.019,NaN,1,CCCC[n]12<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37...,OK,[Ir+3]([c-]1cc2c(cc1-c1ccccn1)-c1cc(-c3ccc4c(c...,OK
1450,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir1-me,0,608,0.4000,2.12,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,Cc1cc2-c3cccc[n]3<-[Ir+3]345(->[c-]6cc(C(F)(F)...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1nccc2ccccc12)([...,OK
1451,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir2-cf3,0,604,0.4100,2.21,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,FC(F)(F)c1ccc2-c3c4ccccc4cc[n]3<-[Ir+3]345(->[...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1nccc2ccccc12)([...,OK
1452,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir3-me,0,628,0.6000,2.06,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,Cc1cc2-c3cccc[n]3<-[Ir+3]34567(->[c-]8cc(C(F)(...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1ncnc2ccccc12)([...,OK
1453,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir4-cf3,0,602,0.6700,2.09,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,FC(F)(F)c1ccc2-c3c4ccccc4[n]4<-[Ir+3]5678(->[c...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1ncnc2ccccc12)([...,OK

In [29]:
Ir_2

,L1,L2,L3,Counterion,Abbreviation_in_the_article,Charge,Max_wavelength(nm),PLQY,tau(s*10^-6),Solvent,...,Complex_SMILES,Complex_Status,Complex_SMILES_canonical,Complex_Status_canonical,Complex_XYZ_File,optimized_file,energy,optimization_ok,optimization_error,normalized_smiles
0,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C([O-])c1ccccn1,NaN,1,0,553,0.2500,4.32,CH2Cl2,...,O=C1[O-]<-[Ir+3]234567(->[c-]8cc(-c9[n]<-2c2c%...,OK,[Ir+3]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2cc...,OK,None,optimized_complexes_em_complex/0.xyz,-123.456,True,None,O=C1O<-[Ir+3]234567(->C8cc(-c9[n]<-2c2c%10cccc...
1,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,c1ccc(-c2ccccn2)nc1,FP(F)(F)(F)(F)F,2,1,570,0.1700,6.14,CH2Cl2,...,c1ccc(-[n]23<-[Ir+2]456789(->[c-]%10cc(-c2[n]<...,OK,[Ir+2]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2cc...,OK,None,optimized_complexes_em_complex/1.xyz,-123.456,True,None,c1ccc(-[n]23<-[Ir+2]456789(->C%10cc(-c2[n]<-4c...
2,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccnc(-c2cc(C(=O)O)ccn2)c1,FP(F)(F)(F)(F)F,3,1,595,0.1400,0.82,CH3OH,...,O=C(O)c1cc[n]2<-[Ir+2]345678(->[c-]9cc(-c%10[n...,OK,[Ir+2]([c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2cc...,OK,None,optimized_complexes_em_complex/2.xyz,-123.456,True,None,O=C(O)c1cc[n]2<-[Ir+2]345678(->C9cc(-c%10[n]<-...
3,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=S(=O)([O-])c1ccc(P(c2ccc(S(=O)(=O)O[Na])cc2)...,NaN,4,0,555,0.0435,41.87,PBS,...,O=S(=O)([O][Na])c1ccc(P(c2ccc(S(=O)(=O)[O][Na]...,OK,[Ir+3]([O-]S(=O)(=O)c1ccc(P(c2ccc(S(=O)(=O)[O]...,OK,None,optimized_complexes_em_complex/3.xyz,-123.456,True,None,O=S(=O)(O[Na])c1ccc(P(c2ccc(S(=O)(=O)O[Na])cc2...
4,[c-]1ccccc1-c1ccccn1,[c-]1ccccc1-c1ccccn1,CCOP(=O)(OCC)c1ccnc(-c2cc(P(=O)(OCC)OCC)ccn2)c1,FP(F)(F)(F)(F)F,Ir(ppy)2bP,1,667,0.0020,NaN,CH3OH,...,CCOP(=O)(OCC)c1cc[n]2<-[Ir+2]34(->[c-]5ccccc5-...,OK,[Ir+2]([c-]1ccccc1-c1ccccn1)([c-]1ccccc1-c1ccc...,OK,None,optimized_complexes_em_complex/4.xyz,-123.456,True,None,CCOP(=O)(OCC)c1cc[n]2<-[Ir+2]34(->C5ccccc5-c5c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,O=C([O-])c1ccccn1,NaN,(m-CzFSOPy)2IrPic,0,554,0.3810,0.64,CH2Cl2,...,CCCC[n]12<-[Ir+3]3456(->[O-]C(=O)c7cccc[n]<-37...,OK,[Ir+3]([c-]1cc2c(cc1-c1ccccn1)-c1cc(-c3ccc4c(c...,OK,None,optimized_complexes_em_complex/1449.xyz,-123.456,True,None,CCCC[n]12<-[Ir+3]3456(->OC(=O)c7cccc[n]<-37)(-...
1450,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir1-me,0,608,0.4000,2.12,CH2Cl2,...,Cc1cc2-c3cccc[n]3<-[Ir+3]345(->[c-]6cc(C(F)(F)...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1nccc2ccccc12)([...,OK,None,optimized_complexes_em_complex/1450.xyz,-123.456,True,None,Cc1cc2-c3cccc[n]3<-[Ir+3]345(->C6cc(C(F)(F)F)c...
1451,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir2-cf3,0,604,0.4100,2.21,CH2Cl2,...,FC(F)(F)c1ccc2-c3c4ccccc4cc[n]3<-[Ir+3]345(->[...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1nccc2ccccc12)([...,OK,None,optimized_complexes_em_complex/1451.xyz,-123.456,True,None,FC(F)(F)c1ccc2-c3c4ccccc4cc[n]3<-[Ir+3]345(->C...
1452,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir3-me,0,628,0.6000,2.06,CH2Cl2,...,Cc1cc2-c3cccc[n]3<-[Ir+3]34567(->[c-]8cc(C(F)(...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1ncnc2ccccc12)([...,OK,None,optimized_complexes_em_complex/1452.xyz,-123.456,True,None,Cc1cc2-c3cccc[n]3<-[Ir+3]34567(->C8cc(C(F)(F)F...
1453,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir4-cf3,0,602,0.6700,2.09,CH2Cl2,...,FC(F)(F)c1ccc2-c3c4ccccc4[n]4<-[Ir+3]5678(->[c...,OK,[Ir+3]([c-]1cc(C(F)(F)F)ccc1-c1ncnc2ccccc12)([...,OK,None,optimized_complexes_em_complex/1453.xyz,-123.456,True,None,FC(F)(F)c1ccc2-c3c4ccccc4[n]4<-[Ir+3]5678(->C2...

In [38]:
import re
import pandas as pd
from openbabel import pybel

def normalize_smiles(smiles_str):
    """
    Нормализует SMILES: исправляет радикалы, заряды, изотопы,
    канонизирует структуру через OpenBabel.
    """
    if pd.isna(smiles_str):
        return None
    
    smiles_str = str(smiles_str).strip()
    
    # Пустая строка
    if not smiles_str or smiles_str == '':
        return None
    
    # === ИСПРАВЛЕНИЯ ПЕРЕД ОБРАБОТКОЙ ===
    
    # 1. Удаляем простые соли (они не несут структурной информации)
    # if smiles_str in {'[Cl-]', '[Br-]', '[I-]', '[F-]', '[O-]N=O'}:
    #     return None
    
    # 2. Исправляем явные радикалы и фрагменты
    radical_fixes = {
        '[H]': 'C',      # Водород → метан (минимальная органика)
        '[C]': 'C',      # Радикал → нейтральный углерод
        '[CH]': 'C',     # Метин-радикал → углерод
        '[CH2]': 'C',    # Метилен-радикал → углерод
        '[c-]':'C',
        '[C-]':'C',
        '[O-]':'O',
        '[O]':'O',
        '[CH3]': 'C',    # Метил-радикал → углерод
        '[Si]': '[Si]',  # Кремний оставляем (может быть валиден)
        '[C]1': 'C1',    # Радикал в цикле → нормальный углерод
        '[Cl-]':'[Cl]',
        '[C]#[O]':'C#O',
        '[Br--]':'[Br]',
        '[Br-2]':'[Br]',
        '[CH-]':'C',
        '[n-]':'N',
        '[N-]':'N',
        '[C-2]':'C',
        '[N]':'N',
        '[C@@]':'C@@',
        '[C@]':'C@',
    }
    
    for radical, fixed in radical_fixes.items():
        smiles_str = smiles_str.replace(radical, fixed)
    
    # 3. Исправляем странные формы CO (монооксид углерода)
    smiles_str = smiles_str.replace('[C-2]=O', 'C=O')  # Кетон
    smiles_str = smiles_str.replace('[C#O]', 'C#N')    # Нитрил (ближайший аналог)
    smiles_str = smiles_str.replace('[C]#[O]', 'C#N')
    
    # 4. Убираем заряды (преобразуем в нейтральные формы)
    charge_patterns = [
        (r'\[c-\]', 'c'),
        (r'\[n-\]', 'n'),
        (r'\[s-\]', 's'),
        (r'\[o-\]', 'o'),
        (r'\[O-\]', 'O'),
        (r'\[N-\]', 'N'),
        (r'\[C-\]', 'C'),
        (r'\[S-\]', 'S'),
        (r'\[C\+\]', 'C'),
        (r'\[N\+\]', 'N'),
        (r'\[O\+\]', 'O'),
        (r'\[n\+\]', 'n'),
        (r'\[CH2\]', 'C'),

    ]
    
    for pattern, replacement in charge_patterns:
        smiles_str = re.sub(pattern, replacement, smiles_str)
    
    # 5. Удаляем изотопные метки
    smiles_str = re.sub(r'\[(\d+)([A-Z][a-z]?)\]', r'[\2]', smiles_str)  # [2H] → [H]
    smiles_str = re.sub(r'\[2H\]', '[H]', smiles_str)
    smiles_str = re.sub(r'\[3H\]', '[H]', smiles_str)
    
    # 6. Удаляем только тяжёлые металлы (но оставляем органометаллы с углеродом)
    heavy_metals = ['Zr', 'Ta', 'Sn', 'Ag', 'As', 'Hg', 'Pb', 'Cd', 'Na']
    metal_pattern = r'\[(' + '|'.join(heavy_metals) + r')[^\]]*\]'
    
    # Если SMILES - только металл, удаляем
    if re.match(r'^\[(' + '|'.join(heavy_metals) + r')[^\]]*\]$', smiles_str):
        return None
    
    # Если металл + органика, удаляем только металл
    smiles_str = re.sub(metal_pattern, '', smiles_str)
    
    # 7. Проверка после исправлений
    if not smiles_str or smiles_str.strip() == '':
        return None
    
    # === КАНОНИЗАЦИЯ ЧЕРЕЗ OPENBABEL ===
    try:
        mol = pybel.readstring("smi", smiles_str)
        mol.addh()  # Добавляем водороды
        
        # Канонический SMILES
        canonical_smiles = mol.write("can").strip().split()[0]
        
        return canonical_smiles
        
    except Exception as e:
        # Если OpenBabel не может обработать - возвращаем исправленный вариант
        print(f"Предупреждение: не удалось канонизировать '{smiles_str}': {e}")
        return smiles_str

# === ТЕСТЫ ===
test_cases = list(Ir_2['Complex_SMILES_canonical'])
results = []
from tqdm import tqdm
for smi in tqdm(test_cases):
    result = normalize_smiles(smi)
    results.append(result)
    # print(f"{smi:40s} → {result}")

100%|██████████| 1454/1454 [00:00<00:00, 1992.59it/s]

In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem
import subprocess
def smiles_to_3d_xtb(smiles, out_xyz='molecule_opt_2.xyz'):
    # Создаем RDKit молекулу из SMILES
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)
    # Генерируем 3D конформер
    AllChem.EmbedMolecule(mol, AllChem.ETKDG())  
    AllChem.UFFOptimizeMolecule(mol)
    # Сохраняем временный xyz файл
    temp_xyz = 'temp.xyz'
    with open(temp_xyz, 'w') as f:
        f.write(Chem.MolToXYZBlock(mol))
    # Запускаем xtb оптимизацию с выходом в out_xyz
    subprocess.run([
        'xtb', temp_xyz, 
        '--opt', '--xyz', out_xyz
    ], check=True)
    print(f'Оптимизированная структура сохранена в {out_xyz}')
for smi in results:

['OC(=O)C1=CC=C[CH]N1[Ir+3](C1[CH]C(=CC=C1c1ccccn1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1)C1[CH]C(=CC=C1c1ccccn1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1',
 'c1ccc(cc1)n1c(nc2c1c1ccccc1c1c2cccc1)C1=CC=C(C([CH]1)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C(=CC=C1c1ccccn1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1)c1ccccn1',
 'OC(=O)C1=C[CH]N(C(=C1)c1nccc(c1)C(=O)O)[Ir+2](C1[CH]C(=CC=C1c1ccccn1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1)C1[CH]C(=CC=C1c1ccccn1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1',
 'O=S(=O)(c1ccc(cc1)P(c1ccccc1P(c1ccc(cc1)S(=O)(=O)O)c1ccc(cc1)S(=O)(=O)O)c1ccc(cc1)S(=O)(=O)O)O[Ir+3](C1[CH]C(=CC=C1c1ccccn1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1)C1[CH]C(=CC=C1c1ccccn1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1',
 'CCOP(=O)(C1=C[CH]N(C(=C1)c1nccc(c1)P(=O)(OCC)OCC)[Ir+2](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1)OCC',
 'CCOP(=O)(C1=C[CH]N(C(=C1)c1nccc(c1)P(=O)(OCC)OCC)[Ir+2](C1[CH]C=CC=C1c1nccc2c1cccc2)C1[CH]C=CC=C1c1nccc2c1cccc2)OCC',
 'CCOP(=O)(C1=C[CH]N(C(=C1)c1nccc(c1)P(=O)(OCC)OCC)[Ir+2](C1[CH]C=CC=C1c1ccc2c(n1)cccc2)C1[CH]C=CC=C1c1ccc2c(n1)cccc2)OCC',
 'O=CC1=CC=C(C([CH]1)[Ir+2](C1[CH]C(=CC=C1c1ccccn1)C=O)N1[CH]C=C(C=C1c1nccc(c1)N(C)C)N(C)C)c1ccccn1',
 'O=CC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)N)N)C1[CH]C(=CC=C1c1ccccn1)C=O)c1ccccn1',
 'O=CC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)C)C)C1[CH]C(=CC=C1c1ccccn1)C=O)c1ccccn1',
 'COC1=C[CH]N(C(=C1)c1nccc(c1)OC)[Ir+2](C1[CH]C(=CC=C1c1ccccn1)C=O)C1[CH]C(=CC=C1c1ccccn1)C=O',
 'OCC1=C[CH]N(C(=C1)c1nccc(c1)CO)[Ir+2](C1[CH]C(=CC=C1c1ccccn1)C=O)C1[CH]C(=CC=C1c1ccccn1)C=O',
 'O=CC1=CC=C(C([CH]1)[Ir](C1[CH]C(=CC=C1c1ccccn1)C=O)N1[CH]C=C(C=C1c1nccc(c1)N(CC)(CC)CC)N(CC)(CC)CC)c1ccccn1',
 'OC(=O)C1CSC(N1)C1=CC=C(C([CH]1)[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)N(C)C)N(C)C)C1[CH]C(=CC=C1c1ccccn1)C1SCC(N1)C(=O)O)c1ccccn1',
 'OC(=O)C1CCSC(N1)C1=CC=C(C([CH]1)[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)N(C)C)N(C)C)C1[CH]C(=CC=C1c1ccccn1)C1SCCC(N1)C(=O)O)c1ccccn1',
 'Cc1n[nH]c(c1)C1=CC=C[CH]N1[Ir+3](C1[C](C=C(N=C1C(F)(F)F)C(F)(F)F)c1nccc2c1cccc2)C1[C](C=C(N=C1C(F)(F)F)C(F)(F)F)c1nccc2c1cccc2',
 'FC(C1=NC(=C[C](C1[Ir+3](N1[CH]C=CC=C1c1[nH]nc(c1)C(F)(F)F)C1[C](C=C(N=C1C(F)(F)F)C(F)(F)F)c1nccc2c1cccc2)c1nccc2c1cccc2)C(F)(F)F)(F)F',
 'FC(C1=NC(=C[C](C1[Ir+3](C1[C](C=C(N=C1C(F)(F)F)C(F)(F)F)c1nccc2c1cccc2)N1[CH]C=CC=C1c1[nH]nc(c1)c1ccccc1)c1nccc2c1cccc2)C(F)(F)F)(F)F',
 'CCCCCCCCN1[N]C2=C(c3nccc4c3cccc4)C(C=C(C2=N1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)[Ir+3](N1(=c2ccc(cc2=C2C1=CC=C([CH]2)C(C)(C)C)C(C)(C)C)c1ccc(cc1)S(=O)(=O)c1ccc(cc1)c1ccc(nc1)C(=O)O)C1C=C(c2ccc(cc2)N(c2ccccc2)c2ccccc2)C2=NN([N]C2=C1c1nccc2c1cccc2)CCCCCCCC',
 'CC1=C(C)C=C(C([CH]1)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C(=C(C=C1c1cnc2c(n1)cc(c(c2)C)C)C)C)c1cnc2c(n1)cc(c(c2)C)C',
 'CC1=C(C)C=C(C([CH]1)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C(=C(C=C1c1cnc2c(n1)cc(c(c2)F)F)C)C)c1cnc2c(n1)cc(c(c2)F)F',
 'FC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C(=CC=C1c1cnc2c(n1)cccc2)F)c1cnc2c(n1)cccc2',
 'FC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C(=CC=C1c1cnc2c(n1)cc(c(c2)C)C)F)c1cnc2c(n1)cc(c(c2)C)C',
 'FC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C(=CC=C1c1cnc2c(n1)cc(c(c2)F)F)F)c1cnc2c(n1)cc(c(c2)F)F',
 'FC1=C[C](c2cnc3c(n2)cccc3)C(C(=C1F)F)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[C](C=C(C(=C1F)F)F)c1cnc2c(n1)cccc2',
 'FC1=C[C](c2cnc3c(n2)cc(c(c3)C)C)C(C(=C1F)F)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[C](C=C(C(=C1F)F)F)c1cnc2c(n1)cc(c(c2)C)C',
 'FC1=C[C](c2cnc3c(n2)cc(c(c3)F)F)C(C(=C1F)F)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[C](C=C(C(=C1F)F)F)c1cnc2c(n1)cc(c(c2)F)F',
 'CC1=C[CH]N(C(=C1)c1nccc(c1)C)[Ir+2](C1[CH]C(=C(C=C1c1cc(C)c2c(n1)cccc2)C(F)(F)F)Cl)C1[CH]C(=C(C=C1c1cc(C)c2c(n1)cccc2)C(F)(F)F)Cl',
 'ClC1=C(C=C(C([CH]1)[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)C(C)(C)C)C(C)(C)C)C1[CH]C(=C(C=C1c1cc(C)c2c(n1)cccc2)C(F)(F)F)Cl)c1cc(C)c2c(n1)cccc2)C(F)(F)F',
 'c1ccc(cc1)P(c1ccccc1Oc1ccccc1P([Ir+2](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1)(c1ccccc1)c1ccccc1)c1ccccc1',
 'C1=CC=C(C([CH]1)[Ir+2](N1(=NC=C[CH]1)c1ccccn1)C1[CH]C=CC=C1c1nnc(n1c1ccccc1)c1ccccc1)c1nnc(n1c1ccccc1)c1ccccc1',
 'CN(C1=C[CH]N(C(=C1)n1cccn1)[Ir+2](C1[CH]C=CC=C1c1nnc(n1c1ccccc1)c1ccccc1)C1[CH]C=CC=C1c1nnc(n1c1ccccc1)c1ccccc1)C',
 'CN1C=CN(C1)CN1C=CN(C1[Ir+2](C1[CH]C=CC=C1c1nnc(n1c1ccccc1)c1ccccc1)C1[CH]C=CC=C1c1nnc(n1c1ccccc1)c1ccccc1)C',
 'FC1=CC(=C(C([CH]1)[Ir+3](C1[CH]C(=CC(=C1c1nccc2c1cccc2)F)F)O/C(=C\\C(=O)C(C)(C)C)/C(C)(C)C)c1nccc2c1cccc2)F',
 'FC1=C[C](F)C(C(=C1)c1nccc2c1cccc2)[Ir+3](C1[C](F)C=C(C=C1c1nccc2c1cccc2)F)O/C(=C\\C(=O)C(C)(C)C)/C(C)(C)C',
 'FC1=C(c2ccc(cc2)C(F)(F)F)C(=C(C([CH]1)[Ir+3](C1[CH]C(=C(C(=C1c1nccc2c1cccc2)F)c1ccc(cc1)C(F)(F)F)F)O/C(=C\\C(=O)C(C)(C)C)/C(C)(C)C)c1nccc2c1cccc2)F',
 'N#Cc1ccc(cc1)C1=C(F)[CH]C(C(=C1F)c1nccc2c1cccc2)[Ir+3](C1[CH]C(=C(C(=C1c1nccc2c1cccc2)F)c1ccc(cc1)C#N)F)O/C(=C\\C(=O)C(C)(C)C)/C(C)(C)C',
 'O=C(c1ccccc1)c1ccc(cc1)C1=C(F)[CH]C(C(=C1F)c1nccc2c1cccc2)[Ir+3](C1[CH]C(=C(C(=C1c1nccc2c1cccc2)F)c1ccc(cc1)C(=O)c1ccccc1)F)O/C(=C\\C(=O)C(C)(C)C)/C(C)(C)C',
 'COC(=O)c1ccc(cc1)C1=C(F)[CH]C(C(=C1F)c1nccc2c1cccc2)[Ir+3](C1[CH]C(=C(C(=C1c1nccc2c1cccc2)F)c1ccc(cc1)C(=O)OC)F)O/C(=C\\C(=O)C(C)(C)C)/C(C)(C)C',
 'N#CC1=CC=C(C([CH]1)[Ir+3](C1[CH]C(=CC=C1c1ncc(c2c1cccc2)C#N)C#N)O/C(=C\\C(=O)C)/C)c1ncc(c2c1cccc2)C#N',
 'N#Cc1cnc(c2c1cccc2)C1=CC=C([CH]C1[Ir+3](C1[CH]C(=CC=C1c1ncc(c2c1cccc2)C#N)C(C)(C)C)O/C(=C\\C(=O)C)/C)C(C)(C)C',
 'N#Cc1cnc(c2c1cccc2)C1=CC(=C[C](C1[Ir+3](C1[C](C)C=C(C=C1c1ncc(c2c1cccc2)C#N)C)O/C(=C\\C(=O)C)/C)C)C',
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1C(=Cc2c3c1c1[CH]C=CN=c1n3c1c2cccc1)c1ccccn1)C1C(=Cc2c3c1c1[CH]C=CN=c1n3c1c2cccc1)c1ccccn1',
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1C(=Cc2c3c1c1[CH]C=CC=c1n3c1c2cccn1)c1ccccn1)C1C(=Cc2c3c1c1[CH]C=CN=c1n3c1c2cccc1)c1ccccn1',
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1C(=Cc2c3c1c1[CH]C=CN=c1n3c1c2cccc1)c1nccc(c1)C(F)(F)F)C1C(=Cc2c3c1c1[CH]C=CN=c1n3c1c2cccc1)c1nccc(c1)C(F)(F)F',
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1C(=Cc2c3c1c1[CH]C=CC=c1n3c1c2cccn1)c1nccc(c1)C(F)(F)F)C1C(=Cc2c3c1c1[CH]C=CN=c1n3c1c2cccc1)c1nccc(c1)C(F)(F)F',
 'FC1=CC(=C(C([CH]1)[Ir+3](n1cccc1/C(=C\\1/C=CC=N1)/c1ccccc1)C1[CH]C(=CC(=C1c1ccccn1)F)F)c1ccccn1)F',
 'c1ccc(cc1)/C(=C/1\\C=CC=N1)/c1cccn1[Ir+3](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1',
 'c1ccc(cc1)/C(=C/1\\C=CC=N1)/c1cccn1[Ir+3](C1[CH]C=CC=C1c1nccc2c1cccc2)C1[CH]C=CC=C1c1nccc2c1cccc2',
 'c1ccc(cc1)/C(=C/1\\C=CC=N1)/c1cccn1[Ir+3](C1[CH]C(=CC=C1c1nccc2c1cccc2)N(c1ccccc1)c1ccccc1)C1[CH]C(=CC=C1c1nccc2c1cccc2)N(c1ccccc1)c1ccccc1',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C(=CC(=C1c1ccccn1)F)F)C1[CH]C(=CC(=C1c1ccccn1)F)F)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C=CC=C1c1nccc2c1cccc2)C1[CH]C=CC=C1c1nccc2c1cccc2)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C(=CC=C1c1nccc2c1cccc2)N(c1ccccc1)c1ccccc1)C1[CH]C(=CC=C1c1nccc2c1cccc2)N(c1ccccc1)c1ccccc1)/C',
 'c1ccc(cc1)C(c1ccccc1)CC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C(=CC=C1c1ccccn1)CC(c1ccccc1)c1ccccc1)c1ccccn1',
 'c1ccc(cc1)N1(=NC(=C[CH]1)c1ccccn1)[Ir+2](C1[CH]C(=CC=C1c1ccccn1)CC(c1ccccc1)c1ccccc1)C1[CH]C(=CC=C1c1ccccn1)CC(c1ccccc1)c1ccccc1',
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1C(=Cc2c3c1c1[CH]C=CC=c1n3c1c2cccc1)c1ccccn1)C1C(=Cc2c3c1c1[CH]C=CC=c1n3c1c2cccc1)c1ccccn1',
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1C(=Cc2c3c1c1[CH]C=CC=c1n3c1c2cccc1)c1nccc(c1)C(F)(F)F)C1C(=Cc2c3c1c1[CH]C=CC=c1n3c1c2cccc1)c1nccc(c1)C(F)(F)F',
 None,
 None,
 None,
 'CC(=O)/C=C(\\O[Ir+3](C1c2ccccc2S[C]1c1nccc2c1cccc2)C1[CH]C(=CC(=C1c1ccccn1)F)F)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1c2ccccc2S[C]1c1nccc2c1cccc2)C1[CH]C=CC=C1c1ccccn1)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1c2ccccc2S[C]1c1nccc2c1cccc2)C1[CH]C=CC=C1c1nc2ccccc2nc1c1ccccc1)/C',
 'COc1cc2c(cc1OC)ncnc2C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1ncnc2c1cc(OC)c(c2)OC)O/C(=C\\C(=O)C)/C',
 'COc1cc2c(cc1OC)ncnc2C1=CC=C([CH]C1[Ir+3](C1[CH]C(=CC=C1c1ncnc2c1cc(OC)c(c2)OC)C(C)(C)C)O/C(=C\\C(=O)C)/C)C(C)(C)C',
 'FC(c1nnc(n1c1ccccc1)C1=CC=C[CH]C1[Ir+2](C1[CH]C=CC=C1c1nnc(n1c1ccccc1)C(F)(F)F)N1[CH]C=CC=C1c1ccccn1)(F)F',
 'CC1=C[CH]N(C(=C1)c1nccc(c1)C)[Ir+2](C1[CH]C=CC=C1c1nnc(n1c1ccccc1)C(F)(F)F)C1[CH]C=CC=C1c1nnc(n1c1ccccc1)C(F)(F)F',
 'FC(c1nnc(n1c1ccccc1)C1=CC=C[CH]C1[Ir+2](N1(=C(N=C[CH]1)c1ccccn1)c1ccccc1)C1[CH]C=CC=C1c1nnc(n1c1ccccc1)C(F)(F)F)(F)F',
 'O/N=C/c1ccnc(c1)C1=CC(=C[CH]N1[Ir+2](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1)C',
 'N#Cc1ccnc(c1)C1=CC(=C[CH]N1[Ir+2](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1)C',
 'CC(CCn1c(nc2c1cc1ccccc1c2)C1=CC=C[CH]C1[Ir+2](C1[CH]C=CC=C1c1nc2c(n1CCC(C)C)cc1c(c2)cccc1)N1[CH]C=CC=C1c1ccccn1)C',
 'CC(CCn1c(nc2c1cc1ccccc1c2)C1=CC=C[CH]C1[Ir+2](C1[CH]C=CC=C1c1nc2c(n1CCC(C)C)cc1c(c2)cccc1)N1[CH]C=C(C=C1c1nccc(c1)C)C)C',
 'CC(CCn1c(nc2c1cc1ccccc1c2)C1=CC=C[CH]C1[Ir+2](C1[CH]C=CC=C1c1nc2c(n1CCC(C)C)cc1c(c2)cccc1)N1C=CC=c2c1c1[N]C=CC=c1cc2)C',
 'COC1=C[CH]C(C(=C1)c1nccc(c1)C(F)(F)F)[Ir+3](C1[CH]C=C(C=C1c1nccc(c1)C(F)(F)F)OC)O/C(=C\\C(=O)C)/C',
 'COC1=C[CH]C(C(=C1)c1nccc(c1)C(F)(F)F)[Ir+3](C1[C](OC)C=CC=C1c1nccc(c1)C(F)(F)F)O/C(=C\\C(=O)C)/C',
 'CO[C]1C=CC=C(C1[Ir+3](C1[C](OC)C=CC=C1c1nccc(c1)C(F)(F)F)O/C(=C\\C(=O)C)/C)c1nccc(c1)C(F)(F)F',
 'COC1=C[CH]C(C(=C1)c1ccc(cn1)C(F)(F)F)[Ir+3](C1[CH]C=C(C=C1c1ccc(cn1)C(F)(F)F)OC)O/C(=C\\C(=O)C)/C',
 'COC1=C[CH]C(C(=C1)c1ccc(cn1)C(F)(F)F)[Ir+3](C1[C](OC)C=CC=C1c1ccc(cn1)C(F)(F)F)O/C(=C\\C(=O)C)/C',
 'CO[C]1C=CC=C(C1[Ir+3](C1[C](OC)C=CC=C1c1ccc(cn1)C(F)(F)F)O/C(=C\\C(=O)C)/C)c1ccc(cn1)C(F)(F)F',
 'CC(=O)/C=C(\\O[Ir+3](C1C=Cc2c3c1c1nc4cc(c5ccc(cc5)N(c5ccccc5)c5ccccc5)c(cc4nc1c1c3c(cc2)C=C[CH]1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)C1C=Cc2c3c1c1nc4cc(c5ccc(cc5)N(c5ccccc5)c5ccccc5)c(cc4nc1c1c3c(cc2)C=C[CH]1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)/C',
 'CCCCCCc1ccc(s1)c1cc2nc3c(nc2cc1c1ccc(s1)CCCCCC)c1[CH]C=Cc2c1c1c3C(C=Cc1cc2)[Ir+3](C1C=Cc2c3c1c1nc4cc(c5ccc(s5)CCCCCC)c(cc4nc1c1c3c(cc2)C=C[CH]1)c1ccc(s1)CCCCCC)O/C(=C\\C(=O)C)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1C=Cc2c3c1c1nc4cc(c5ccc(s5)N(c5ccccc5)c5ccccc5)c(cc4nc1c1c3c(cc2)C=C[CH]1)c1ccc(s1)N(c1ccccc1)c1ccccc1)C1C=Cc2c3c1c1nc4cc(c5ccc(s5)N(c5ccccc5)c5ccccc5)c(cc4nc1c1c3c(cc2)C=C[CH]1)c1ccc(s1)N(c1ccccc1)c1ccccc1)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1C=C(C=C2C1=c1nc3cc4ccccc4cc3nc1=C1[C]2C=C(C=C1)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)C1C=C(C=C2C1=c1nc3cc4ccccc4cc3nc1=C1[C]2C=C(C=C1)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)/C',
 'C/C(=N\\c1ccccc1)/C=C(\\O[Ir+3](C1[C](Sc2c1cccc2)c1ccc2c(n1)cccc2)C1[C](Sc2c1cccc2)c1ccc2c(n1)cccc2)/C',
 'CC(N(C(=S[Ir+3](C1[C](Sc2c1cccc2)c1ccc2c(n1)cccc2)C1[C](Sc2c1cccc2)c1ccc2c(n1)cccc2)S)C(C)C)C',
 None,
 'C/C(=N\\c1ccccc1)/C=C(\\O[Ir+3](C1c2ccccc2S[C]1c1nc2ccccc2c2c1cccc2)C1c2ccccc2S[C]1c1nc2ccccc2c2c1cccc2)/C',
 None,
 None,
 None,
 'C1=C[N]c2c(=N1)ccc1=Nc3c(N(c21)[Ir+2](C1[CH]C=CC=C1c1nccc2c1cccc2)C1[CH]C=CC=C1c1nccc2c1cccc2)ccc1c3cccc1',
 'CC1(C)c2ccccc2C2=C1C=C(c1nccc3c1cccc3)C([CH]2)[Ir+2](N1c2c(=Nc3c1ccc1c3cccc1)ccc1=NC=C[N]c21)C1[CH]C2=C(C=C1c1nccc3c1cccc3)C(c1c2cccc1)(C)C',
 'CC(CCn1c(nc2c1cccc2)C1=CC=C([CH]C1[Ir+2](C1[CH]C(=CC=C1c1nc2c(n1CCC(C)C)cccc2)F)N1[CH]C=C(C=C1c1nccc(c1)C)C)F)C',
 'CC(CCn1c(nc2c1cccc2)[C]1SC=CC1[Ir+2](C1C=CS[C]1c1nc2c(n1CCC(C)C)cccc2)N1[CH]C=C(C=C1c1nccc(c1)C)C)C',
 'CC(CCn1c(nc2c1cccc2)C1=CC=C([CH]C1[Ir+2](C1[CH]C(=CC=C1c1nc2c(n1CCC(C)C)cccc2)F)N1C(=C(N=c2c1c1cccnc1c1c2=CC=C[N]1)c1cccs1)c1cccs1)F)C',
 'CC(CCn1c(nc2c1cccc2)[C]1SC=CC1[Ir+2](C1C=CS[C]1c1nc2c(n1CCC(C)C)cccc2)N1C(=C(N=c2c1c1cccnc1c1c2=CC=C[N]1)c1cccs1)c1cccs1)C',
 'COC1=C[CH]C(C(=C1)c1nc2c(n1c1ccccc1)cccc2)[Ir+3](C1[CH]C=C(C=C1c1nc2c(n1c1ccccc1)cccc2)OC)N1[C](Nc2c1cccc2)c1ccccn1',
 'Cc1ccnc(c1)C1=CC(=C[CH]N1[Ir+2](C1[CH]C=CC=C1c1nc2c(n1C(C)C)cccc2)C1[CH]C=CC=C1c1nc2c(n1C(C)C)cccc2)C',
 'Cc1ccnc(c1)C1=CC(=C[CH]N1[Ir+2](C1[CH]C=CC=C1c1nc2c(n1C(C)C)cc(c(c2)Cl)Cl)C1[CH]C=CC=C1c1nc2c(n1C(C)C)cc(c(c2)Cl)Cl)C',
 'CC1=C[CH]N(C(=C1)c1nccc(c1)C)[Ir+2](C1[CH]C=CC=C1c1nc2c(n1C(C)C)ccc(c2)C(F)(F)F)C1[CH]C=CC=C1c1nc2c(n1C(C)C)ccc(c2)C(F)(F)F',
 'COc1ccc2c(c1)n(C(C)C)c(n2)C1=CC=C[CH]C1[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)C)C)C1[CH]C=CC=C1c1nc2c(n1C(C)C)cc(cc2)OC',
 'Cc1ccnc(c1)C1=CC(=C[CH]N1[Ir+2](C1[CH]C(=CC=C1c1nc2c(n1C(C)C)cccc2)C(F)(F)F)C1[CH]C(=CC=C1c1nc2c(n1C(C)C)cccc2)C(F)(F)F)C',
 'COC1=CC=C(C([CH]1)[Ir+2](C1[CH]C(=CC=C1c1nc2c(n1C(C)C)cccc2)OC)N1[CH]C=C(C=C1c1nccc(c1)C)C)c1nc2c(n1C(C)C)cccc2',
 'CC1=C[CH]N(C(=C1)c1nccc(c1)C)[Ir+2](C1[CH]C(=CC=C1c1nc2c(n1C(C)C)ccc(c2)C(F)(F)F)C(F)(F)F)C1[CH]C(=CC=C1c1nc2c(n1C(C)C)ccc(c2)C(F)(F)F)C(F)(F)F',
 'COC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)C)C)C1[CH]C(=CC=C1c1nc2c(n1C(C)C)cc(cc2)OC)OC)c1nc2c(n1C(C)C)cc(cc2)OC',
 'COC1=CC=C(C([CH]1)[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)C)C)C1[CH]C(=CC=C1c1nc2c(n1C(C)C)ccc(c2)C(F)(F)F)OC)c1nc2c(n1C(C)C)ccc(c2)C(F)(F)F',
 'COc1ccc2c(c1)n(C(C)C)c(n2)C1=CC=C([CH]C1[Ir+2](N1[CH]C=C(C=C1c1nccc(c1)C)C)C1[CH]C(=CC=C1c1nc2c(n1C(C)C)cc(cc2)OC)C(F)(F)F)C(F)(F)F',
 None,
 None,
 None,
 None,
 None,
 None,
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C=CC(=C1c1nc2c(s1)cccc2)C(F)(F)F)C1[CH]C=CC(=C1c1nc2c(s1)cccc2)C(F)(F)F)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C=C(C=C1c1nc2c(s1)cccc2)C(F)(F)F)C1[CH]C=C(C=C1c1nc2c(s1)cccc2)C(F)(F)F)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C(=CC=C1c1nc2c(s1)cccc2)C(F)(F)F)C1[CH]C(=CC=C1c1nc2c(s1)cccc2)C(F)(F)F)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C=CC(=C1c1nc2c(n1c1ccccc1)cccc2)C(F)(F)F)C1[CH]C=CC(=C1c1nc2c(n1c1ccccc1)cccc2)C(F)(F)F)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C=C(C=C1c1nc2c(n1c1ccccc1)cccc2)C(F)(F)F)C1[CH]C=C(C=C1c1nc2c(n1c1ccccc1)cccc2)C(F)(F)F)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1[CH]C(=CC=C1c1nc2c(n1c1ccccc1)cccc2)C(F)(F)F)C1[CH]C(=CC=C1c1nc2c(n1c1ccccc1)cccc2)C(F)(F)F)/C',
 'C/C(=N\\c1ccccc1)/C=C(\\O[Ir+3](C1[CH]C=CC=C1c1nc2ccccc2c2c1cccc2)C1[CH]C=CC=C1c1nc2ccccc2c2c1cccc2)/C',
 None,
 'C/C(=N\\C1CCCCC1)/C=C(\\O[Ir+3](C1[CH]C=CC=C1c1nc2ccccc2c2c1cccc2)C1[CH]C=CC=C1c1nc2ccccc2c2c1cccc2)/C',
 'N#Cc1cnc(c2c1cccc2)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1ncc(c2c1cccc2)C#N)O/C(=C\\C(=N\\c1ccccc1)\\C)/C',
 None,
 None,
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1C=CC=C2C1=c1nc3ccccc3nc1=C1[C]2C=CC=C1)C1C=CC=C2C1=c1nc3ccccc3nc1=C1[C]2C=CC=C1',
 'CC(=O)/C=C(\\O[Ir+3](C1C=C(C=C2C1=c1nc3ccccc3nc1=C1[C]2C=C(C=C1)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)C1C=C(C=C2C1=c1nc3ccccc3nc1=C1[C]2C=C(C=C1)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)c1ccc(cc1)N(c1ccc(cc1)C(C)(C)C)c1ccc(cc1)C(C)(C)C)/C',
 'c1ccc(nc1)[C]1Nc2c(N1[Ir+3](C1[CH]C=CC=C1c1ccc3c(n1)cccc3)C1[CH]C=CC=C1c1ccc3c(n1)cccc3)cccc2',
 'c1ccc(nc1)[C]1Nc2c(N1[Ir+3](C1[CH]C=CC=C1c1nccc3c1cccc3)C1[CH]C=CC=C1c1nccc3c1cccc3)cccc2',
 'O=C(C(C)(C)C)/C=C(/C(C)(C)C)\\O[Ir+3](C1c2sccc2S[C]1c1nccc2c1cccc2)C1c2sccc2S[C]1c1nccc2c1cccc2',
 'Brc1ccc(cc1)/C(=C/C(=O)c1ccc(cc1)Br)/O[Ir+3](C1[C](Sc2c1cccc2)c1cnc2c(n1)cccc2)C1[C](Sc2c1cccc2)c1cnc2c(n1)cccc2',
 'O=C(c1cccs1)/C=C(/C(F)(F)F)\\O[Ir+3](C1c2ccccc2S[C]1c1nc2ccccc2c2c1cccc2)C1c2ccccc2S[C]1c1nc2ccccc2c2c1cccc2',
 'O=C(c1cccs1)/C=C(/C1=C2C=CC=C[C]2N(C(=C1)c1ccccc1)[Ir+3](C1c2ccccc2S[C]1c1nc2ccccc2c2c1cccc2)C1c2ccccc2S[C]1c1nc2ccccc2c2c1cccc2)\\O',
 'COC(=O)c1cc(nc2c1cccc2)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2ccccc2c(c1)C(=O)OC)O/C(=C\\C(=O)c1cccs1)/C(F)(F)F',
 'COC(=O)c1cc(nc2c1cccc2)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2ccccc2c(c1)C(=O)OC)N1C(=CC(=C2[C]1C=CC=C2)/C(=C/C(=O)c1cccs1)/O)c1ccccc1',
 'COC(=O)c1cc(nc2c1cccc2)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2ccccc2c(c1)C(=O)OC)O/C(=C\\C(=O)C(F)(F)F)/C(F)(F)F',
 'COC(=O)c1cc(nc2c1cccc2)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2ccccc2c(c1)C(=O)OC)O/C(=C\\C(=O)C)/C',
 'CCOC(=O)c1cc(nc2c1cccc2)C1=C[C]2C=CC=CC2=CC1[Ir+2](C1C=C2C=CC=C[C]2C=C1c1nc2ccccc2c(c1)C(=O)OCC)N1[CH]C=CC=C1c1ccccn1',
 'CCOCCOC(=O)c1cc(nc2c1cc(OC)cc2)C1=C[C]2C=CC=CC2=CC1[Ir+2](C1C=C2C=CC=C[C]2C=C1c1nc2ccc(cc2c(c1)C(=O)OCCOCC)OC)N1[CH]C=CC=C1c1ccccn1',
 'CCOC(=O)c1cc(nc2c1cc(F)cc2)C1=C[C]2C=CC=CC2=CC1[Ir+2](C1C=C2C=CC=C[C]2C=C1c1nc2ccc(cc2c(c1)C(=O)OCC)F)N1[CH]C=CC=C1c1ccccn1',
 'CCOC(=O)c1cc(nc2c1cccc2)C1=c2ccccc2=C[CH]C1[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C=c2c(=C1c1nc3ccccc3c(c1)C(=O)OCC)cccc2',
 'CCOC(=O)c1cc(nc2c1cc(OC)cc2)C1=c2ccccc2=C[CH]C1[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C=c2c(=C1c1nc3ccc(cc3c(c1)C(=O)OCC)OC)cccc2',
 'CCOC(=O)c1cc(nc2c1cc(F)cc2)C1=c2ccccc2=C[CH]C1[Ir+2](N1[CH]C=CC=C1c1ccccn1)C1[CH]C=c2c(=C1c1nc3ccc(cc3c(c1)C(=O)OCC)F)cccc2',
 'O=c1c2cccc3c2c(c2n1c1=CC=C[CH]c1n2)C(C=C3)[Ir+3](C1C=Cc2c3c1c1nc4c(=CC=C[CH]4)n1c(=O)c3ccc2)N1[CH]C=CC=C1c1[nH]nc(c1)C(F)(F)F',
 'O=c1c2cccc3c2c(c2n1c1=CC=C[CH]c1n2)C(C=C3N(c1ccccc1)c1ccccc1)[Ir+3](C1C=C(N(c2ccccc2)c2ccccc2)c2c3c1c1nc4c(=CC=C[CH]4)n1c(=O)c3ccc2)N1[CH]C=CC=C1c1[nH]nc(c1)C(F)(F)F',
 'CCCCCCc1ccc(s1)C1=CC(C2=c3c(=C4[C](C2=C1)C=C(C=C4)c1ccc(s1)CCCCCC)nc1c(n3)cccc1)[Ir+3](C1C=C(C=C2C1=c1nc3ccccc3nc1=C1[C]2C=C(C=C1)c1ccc(s1)CCCCCC)c1ccc(s1)CCCCCC)O/C(=C\\C(=O)C)/C',
 'CCCCCCc1ccc(s1)c1cc2nc3=C4C(=CC=CC4[Ir+3](C4C=CC=C5C4=c4nc6cc(c7ccc(s7)CCCCCC)c(cc6nc4=C4[C]5C=CC=C4)c4ccc(s4)CCCCCC)O/C(=C\\C(=O)C)/C)[C]4C(=c3nc2cc1c1ccc(s1)CCCCCC)C=CC=C4',
 'CC(=O)/C=C(\\O[Ir+3](C1C=C(C=C2C1=c1nc3ccccc3nc1=C1[C]2C=C(C=C1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)C1C=C(C=C2C1=c1nc3ccccc3nc1=C1[C]2C=C(C=C1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)/C',
 'CC(=O)/C=C(\\O[Ir+3](C1C=CC=C2C1=c1nc3cc(c4ccc(cc4)N(c4ccccc4)c4ccccc4)c(cc3nc1=C1[C]2C=CC=C1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)C1C=CC=C2C1=c1nc3cc(c4ccc(cc4)N(c4ccccc4)c4ccccc4)c(cc3nc1=C1[C]2C=CC=C1)c1ccc(cc1)N(c1ccccc1)c1ccccc1)/C',
 'FC1=NC(=C(C([CH]1)[Ir+3](N1[CH]C=CC=C1C(=O)O)C1[CH]C(=NC(=C1c1ncnc(c1)c1c(C)cc(cc1C)C)F)F)c1ncnc(c1)c1c(C)cc(cc1C)C)F',
 'FC1=NC(=C(C([CH]1)[Ir+3](N1[CH]C=CC=C1c1[nH]nc(c1)C(F)(F)F)C1[CH]C(=NC(=C1c1ncnc(c1)c1c(C)cc(cc1C)C)F)F)c1ncnc(c1)c1c(C)cc(cc1C)C)F',
 'FC1=NC(=C(C([CH]1)[Ir+3](N1N[C](N=C1C(F)(F)F)c1ccccn1)C1[CH]C(=NC(=C1c1ncnc(c1)c1c(C)cc(cc1C)C)F)F)c1ncnc(c1)c1c(C)cc(cc1C)C)F',
 'Cc1nc2ccccc2nc1C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2ccccc2nc1C)N1[CH]C=CC=C1C(=O)O',
 'Cc1nc2cc(C)c(cc2nc1C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2cc(C)c(cc2nc1C)C)N1[CH]C=CC=C1C(=O)O)C',
 'Cc1nc2cc(Cl)c(cc2nc1C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2cc(Cl)c(cc2nc1C)Cl)N1[CH]C=CC=C1C(=O)O)Cl',
 'Cc1nc2cc(F)c(cc2nc1C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2cc(F)c(cc2nc1C)F)N1[CH]C=CC=C1C(=O)O)F',
 'Cc1cc2nc(c3ccccc3)c(nc2cc1C)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2cc(C)c(cc2nc1c1ccccc1)C)N1[CH]C=CC=C1C(=O)O',
 'Clc1cc2nc(c3ccccc3)c(nc2cc1Cl)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2cc(Cl)c(cc2nc1c1ccccc1)Cl)N1[CH]C=CC=C1C(=O)O',
 'Fc1cc2nc(c3ccccc3)c(nc2cc1F)C1=CC=C[CH]C1[Ir+3](C1[CH]C=CC=C1c1nc2cc(F)c(cc2nc1c1ccccc1)F)N1[CH]C=CC=C1C(=O)O',
 'OC(=O)C1=CN([CH]C=N1)[Ir+3](C1[CH]C=CC=C1c1nc2cc(C)c(cc2nc1C)C)C1[CH]C=CC=C1c1nc2cc(C)c(cc2nc1C)C',
 'OC(=O)C1=CN([CH]C=N1)[Ir+3](C1[CH]C=CC=C1c1nc2cc(C)c(cc2nc1c1ccccc1)C)C1[CH]C=CC=C1c1nc2cc(C)c(cc2nc1c1ccccc1)C',
 'OC(=O)C1=CN([CH]C=N1)[Ir+3](C1[CH]C=CC=C1c1nc2cc(F)c(cc2nc1c1ccccc1)F)C1[CH]C=CC=C1c1nc2cc(F)c(cc2nc1c1ccccc1)F',
 'CCOP(=O)(CC1=C[CH]N(C(=C1)c1nccc(c1)CP(=O)(OCC)OCC)[Ir+2](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1)OCC',
 'OP(=O)(CC1=C[CH]N(C(=C1)c1nccc(c1)CP(=O)(O)O)[Ir+2](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1)O',
 'FC(C1=CC(=C[C](C1[Ir+2](N1C=CN=c2c1c1[N]C=CN=c1cc2)C1[C](C=C(C=C1C(F)(F)F)C(F)(F)F)c1ccccn1)c1ccccn1)C(F)(F)F)(F)F',
 'FC(C1=CC(=C[C](C1[Ir+2](C1[C](C=C(C=C1C(F)(F)F)C(F)(F)F)c1ccccn1)N1c2ccccc2N=c2c1c1[N]C=CN=c1cc2)c1ccccn1)C(F)(F)F)(F)F',
 'FC(C1=CC(=C[C](C1[Ir+2](C1[C](C=C(C=C1C(F)(F)F)C(F)(F)F)c1ccccn1)N1c2c(=Nc3c1ccc1c3cccc1)ccc1=NC=C[N]c21)c1ccccn1)C(F)(F)F)(F)F',
 'c1ccc(cc1)N1(=C2[C]3C=CC=CC3=c3c(=C2N=C1c1ccccn1)cccc3)[Ir+2](C1[CH]C=CC=C1c1ccccn1)C1[CH]C=CC=C1c1ccccn1',
 'c1ccc(nc1)[C]1Sc2c(C1[Ir+2](N1(=C3[C]4C=CC=CC4=c4c(=C3N=C1c1ccccn1)cccc4)c1ccccc1)C1[C](Sc3c1cccc3)c1ccccn1)cccc2',
 'COC(=O)c1cc(nc2c1cccc2)C1=CC=C[CH]C1[Ir+2](N1(=C2[C]3C=CC=CC3=c3c(=C2N=C1c1ccccn1)cccc3)c1ccccc1)C1[CH]C=CC=C1c1nc2ccccc2c(c1)C(=O)OC',
 'c1ccc(cc1)n1c2c(nc1C1=CC=C[CH]C1[Ir+2](N1(=C3[C]4C=CC=CC4=c4c(=C3N=C1c1ccccn1)cccc4)c1ccccc1)C1[CH]C=CC=C1c1nc3c(n1c1ccccc1)c1ccccc1c1c3cccc1)c1ccccc1c1c2cccc1',
 'IC1=C[CH]C(C(=C1)c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1)[Ir+2](N1(=C2[C]3C=CC=CC3=c3c(=C2N=C1c1ccccn1)cccc3)c1ccccc1)C1[CH]C=C(C=C1c1nc2c(n1c1ccccc1)c1ccccc1c1c2cccc1)I',

In [42]:
pd.DataFrame(results, columns=['SMILES']).to_csv('SMILES_Ir_Em.csv')

# Solvent

In [6]:
sol = df['Solvent']
sol

0       CH2Cl2
1       CH2Cl2
2        CH3OH
3          PBS
4        CH3OH
         ...
1449    CH2Cl2
1450    CH2Cl2
1451    CH2Cl2
1452    CH2Cl2
1453    CH2Cl2
Name: Solvent, Length: 1454, dtype: object

In [8]:
import pandas as pd
import numpy as np

# Словарь названий растворителей и их SMILES
solvent_to_smiles = {
    '2-MeTHF': 'CC1COCCO1',              # 2-Methyltetrahydrofuran
    'C2H5OH': 'CCO',                     # Ethanol
    'CH2Cl2': 'ClCCl',                   # Dichloromethane
    'CH3CN': 'CC#N',                     # Acetonitrile
    'CH3OH': 'CO',                       # Methanol
    'CHCl3': 'ClC(Cl)Cl',                # Chloroform
    'DCE': 'ClCCCl',                     # 1,2-Dichloroethane
    'DMF': 'CN(C)C=O',                   # Dimethylformamide
    'DMSO': 'CS(=O)C',                   # Dimethyl sulfoxide
    'H2O': 'O',                          # Water
    'PBS': None,                         # Phosphate Buffered Saline — не молекула, нет SMILES
    'THF': 'C1CCOC1',                    # Tetrahydrofuran
    'acetone': 'CC(=O)C',                # Acetone
    'cyclohexane': 'C1CCCCC1',           # Cyclohexane
    'toluene': 'Cc1ccccc1',              # Toluene
    np.nan: None                         # Обработка NaN
}

# Исходный список растворителей (в том порядке, как у вас)
solvents = [
    '2-MeTHF',
    'C2H5OH',
    'CH2Cl2',
    'CH3CN',
    'CH3OH',
    'CHCl3',
    'DCE',
    'DMF',
    'DMSO',
    'H2O',
    'PBS',
    'THF',
    'acetone',
    'cyclohexane',
    np.nan,
    'toluene'
]

# Создаём DataFrame
df = pd.DataFrame({'Solvent': solvents})

# Добавляем столбец SMILES с использованием map
df['SMILES_Solvent'] = df['Solvent'].map(solvent_to_smiles)

# Выводим результат
print(df)

        Solvent SMILES_Solvent
0       2-MeTHF      CC1COCCO1
1        C2H5OH            CCO
2        CH2Cl2          ClCCl
3         CH3CN           CC#N
4         CH3OH             CO
5         CHCl3      ClC(Cl)Cl
6           DCE         ClCCCl
7           DMF       CN(C)C=O
8          DMSO        CS(=O)C
9           H2O              O
10          PBS           None
11          THF        C1CCOC1
12      acetone        CC(=O)C
13  cyclohexane       C1CCCCC1
14          NaN           None
15      toluene      Cc1ccccc1

In [10]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
import subprocess
import os

# Название папки для сохранения
OUTPUT_DIR = "optimized_solvents_Ir"

# Создаём папку, если её нет
os.makedirs(OUTPUT_DIR, exist_ok=True)

def smiles_to_3d_xtb(smiles, out_xyz_path):
    """
    Преобразует SMILES в 3D-структуру, оптимизирует её с помощью xTB и сохраняет в указанный путь.
    """
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise ValueError("RDKit не смог распарсить SMILES")
        
        mol = Chem.AddHs(mol)
        res = AllChem.EmbedMolecule(mol, AllChem.ETKDG())
        if res == -1:
            raise RuntimeError("Не удалось сгенерировать 3D-конформер")
        
        AllChem.UFFOptimizeMolecule(mol)
        
        temp_xyz = 'temp_mol.xyz'
        with open(temp_xyz, 'w') as f:
            f.write(Chem.MolToXYZBlock(mol))
        
        result = subprocess.run([
            'xtb', temp_xyz, '--opt', '--xyz', out_xyz_path
        ], capture_output=True, text=True)
        
        if result.returncode != 0:
            raise RuntimeError(f"xTB failed:\n{result.stderr}")
        
        if os.path.exists(temp_xyz):
            os.remove(temp_xyz)
            
        print(f"✅ Успешно: {out_xyz_path}")
        return True
        
    except Exception as e:
        print(f"❌ Ошибка для SMILES '{smiles}': {e}")
        return False

def safe_filename(name):
    """Преобразует название в безопасное имя файла."""
    name = str(name).strip()
    return "".join(c if c.isalnum() or c in ('-', '_') else '_' for c in name)

# --- Данные ---
solvent_to_smiles = {
    '2-MeTHF': 'CC1COCCO1',
    'C2H5OH': 'CCO',
    'CH2Cl2': 'ClCCl',
    'CH3CN': 'CC#N',
    'CH3OH': 'CO',
    'CHCl3': 'ClC(Cl)Cl',
    'DCE': 'ClCCCl',
    'DMF': 'CN(C)C=O',
    'DMSO': 'CS(=O)C',
    'H2O': 'O',
    'PBS': None,
    'THF': 'C1CCOC1',
    'acetone': 'CC(=O)C',
    'cyclohexane': 'C1CCCCC1',
    'toluene': 'Cc1ccccc1'
}

df = pd.DataFrame({
    'Solvent': list(solvent_to_smiles.keys()),
    'SMILES': list(solvent_to_smiles.values())
})

# Убираем строки без SMILES
df = df.dropna(subset=['SMILES'])
df = df[df['SMILES'] != '']

# Обработка каждой молекулы
for _, row in df.iterrows():
    solvent = row['Solvent']
    smiles = row['SMILES']
    
    safe_name = safe_filename(solvent)
    out_path = os.path.join(OUTPUT_DIR, f"{safe_name}.xyz")
    
    print(f"\nОбрабатываю: {solvent} → {out_path}")
    smiles_to_3d_xtb(smiles, out_xyz_path=out_path)

Обрабатываю: 2-MeTHF → optimized_solvents_Ir/2-MeTHF.xyz
✅ Успешно: optimized_solvents_Ir/2-MeTHF.xyz

Обрабатываю: C2H5OH → optimized_solvents_Ir/C2H5OH.xyz
✅ Успешно: optimized_solvents_Ir/C2H5OH.xyz

Обрабатываю: CH2Cl2 → optimized_solvents_Ir/CH2Cl2.xyz
✅ Успешно: optimized_solvents_Ir/CH2Cl2.xyz

Обрабатываю: CH3CN → optimized_solvents_Ir/CH3CN.xyz
✅ Успешно: optimized_solvents_Ir/CH3CN.xyz

Обрабатываю: CH3OH → optimized_solvents_Ir/CH3OH.xyz
✅ Успешно: optimized_solvents_Ir/CH3OH.xyz

Обрабатываю: CHCl3 → optimized_solvents_Ir/CHCl3.xyz
✅ Успешно: optimized_solvents_Ir/CHCl3.xyz

Обрабатываю: DCE → optimized_solvents_Ir/DCE.xyz
✅ Успешно: optimized_solvents_Ir/DCE.xyz

Обрабатываю: DMF → optimized_solvents_Ir/DMF.xyz
✅ Успешно: optimized_solvents_Ir/DMF.xyz

Обрабатываю: DMSO → optimized_solvents_Ir/DMSO.xyz
✅ Успешно: optimized_solvents_Ir/DMSO.xyz

Обрабатываю: H2O → optimized_solvents_Ir/H2O.xyz
✅ Успешно: optimized_solvents_Ir/H2O.xyz

Обрабатываю: THF → optimized_solvents_Ir/THF.xyz
✅ Успешно: optimized_solvents_Ir/THF.xyz

Обрабатываю: acetone → optimized_solvents_Ir/acetone.xyz
✅ Успешно: optimized_solvents_Ir/acetone.xyz

Обрабатываю: cyclohexane → optimized_solvents_Ir/cyclohexane.xyz
✅ Успешно: optimized_solvents_Ir/cyclohexane.xyz

Обрабатываю: toluene → optimized_solvents_Ir/toluene.xyz
✅ Успешно: optimized_solvents_Ir/toluene.xyz

In [44]:
from rdkit import Chem
from rdkit.Chem import AllChem
import os

# Словарь растворителей
solvent_to_smiles = {
    '2-MeTHF': 'CC1COCCO1',
    'C2H5OH': 'CCO',
    'CH2Cl2': 'ClCCl',
    'CH3CN': 'CC#N',
    'CH3OH': 'CO',
    'CHCl3': 'ClC(Cl)Cl',
    'DCE': 'ClCCCl',
    'DMF': 'CN(C)C=O',
    'DMSO': 'CS(=O)C',
    'H2O': 'O',
    'PBS': None,
    'THF': 'C1CCOC1',
    'acetone': 'CC(=O)C',
    'cyclohexane': 'C1CCCCC1',
    'toluene': 'Cc1ccccc1'
}

# Создаём папку для сохранения xyz-файлов
os.makedirs("optimized_solvents_xyz", exist_ok=True)

def mol_to_xyz(mol, filename):
    """Сохраняет RDKit-молекулу в формат .xyz"""
    conf = mol.GetConformer()
    atoms = mol.GetAtoms()
    n_atoms = mol.GetNumAtoms()

    with open(filename, 'w') as f:
        f.write(f"{n_atoms}\n")
        f.write("Optimized with RDKit\n")
        for atom, pos in zip(atoms, conf.GetPositions()):
            symbol = atom.GetSymbol()
            x, y, z = pos
            f.write(f"{symbol:2s} {x:12.6f} {y:12.6f} {z:12.6f}\n")

# Обработка каждой молекулы
for name, smiles in solvent_to_smiles.items():
    if smiles is None:
        print(f"Skipping {name} (no SMILES provided)")
        continue

    print(f"Processing {name} ({smiles})...")

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"❌ Failed to parse SMILES for {name}")
        continue

    mol = Chem.AddHs(mol)

    # Embed 3D coordinates
    success = AllChem.EmbedMolecule(mol, randomSeed=0xf00d)
    if success != 0:
        print(f"❌ Embedding failed for {name}")
        continue

    # Optimize: MMFF first
    ff_result = AllChem.MMFFOptimizeMolecule(mol)
    if ff_result == -1:
        print(f"⚠️ MMFF not applicable for {name}, trying UFF...")
        uff_result = AllChem.UFFOptimizeMolecule(mol)
        if uff_result == -1:
            print(f"❌ Both MMFF and UFF failed for {name}")
            continue

    # Сохраняем в .xyz
    out_path = os.path.join("optimized_solvents_xyz", f"{name}.xyz")
    mol_to_xyz(mol, out_path)
    print(f"✅ Saved to {out_path}")

print("\n✨ All done! XYZ files are in 'optimized_solvents_xyz/'")

Processing 2-MeTHF (CC1COCCO1)...
✅ Saved to optimized_solvents_xyz/2-MeTHF.xyz
Processing C2H5OH (CCO)...
✅ Saved to optimized_solvents_xyz/C2H5OH.xyz
Processing CH2Cl2 (ClCCl)...
✅ Saved to optimized_solvents_xyz/CH2Cl2.xyz
Processing CH3CN (CC#N)...
✅ Saved to optimized_solvents_xyz/CH3CN.xyz
Processing CH3OH (CO)...
✅ Saved to optimized_solvents_xyz/CH3OH.xyz
Processing CHCl3 (ClC(Cl)Cl)...
✅ Saved to optimized_solvents_xyz/CHCl3.xyz
Processing DCE (ClCCCl)...
✅ Saved to optimized_solvents_xyz/DCE.xyz
Processing DMF (CN(C)C=O)...
✅ Saved to optimized_solvents_xyz/DMF.xyz
Processing DMSO (CS(=O)C)...
✅ Saved to optimized_solvents_xyz/DMSO.xyz
Processing H2O (O)...
✅ Saved to optimized_solvents_xyz/H2O.xyz
Skipping PBS (no SMILES provided)
Processing THF (C1CCOC1)...
✅ Saved to optimized_solvents_xyz/THF.xyz
Processing acetone (CC(=O)C)...
✅ Saved to optimized_solvents_xyz/acetone.xyz
Processing cyclohexane (C1CCCCC1)...
✅ Saved to optimized_solvents_xyz/cyclohexane.xyz
Processing toluene (Cc1ccccc1)...
✅ Saved to optimized_solvents_xyz/toluene.xyz

✨ All done! XYZ files are in 'optimized_solvents_xyz/'

In [9]:
df.to_csv('Sol_Ir.csv')