In [2]:
import pandas as pd
df = pd.read_csv('/Users/egorilin/Desktop/MSU_AI/IrLumDB.csv')
df

,L1,L2,L3,Counterion,Abbreviation_in_the_article,Charge,Max_wavelength(nm),PLQY,tau(s*10^-6),Solvent,DOI,Notes,PLQY_in_train
0,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C([O-])c1ccccn1,NaN,1,0,553,0.2500,4.32,CH2Cl2,10.3390/molecules27010232,NaN,1
1,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,c1ccc(-c2ccccn2)nc1,FP(F)(F)(F)(F)F,2,1,570,0.1700,6.14,CH2Cl2,10.3390/molecules27010232,NaN,1
2,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccnc(-c2cc(C(=O)O)ccn2)c1,FP(F)(F)(F)(F)F,3,1,595,0.1400,0.82,CH3OH,10.3390/molecules27010232,NaN,1
3,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=S(=O)([O-])c1ccc(P(c2ccc(S(=O)(=O)O[Na])cc2)...,NaN,4,0,555,0.0435,41.87,PBS,10.3390/molecules27010232,NaN,1
4,[c-]1ccccc1-c1ccccn1,[c-]1ccccc1-c1ccccn1,CCOP(=O)(OCC)c1ccnc(-c2cc(P(=O)(OCC)OCC)ccn2)c1,FP(F)(F)(F)(F)F,Ir(ppy)2bP,1,667,0.0020,NaN,CH3OH,10.1002/adhm.202100706,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,O=C([O-])c1ccccn1,NaN,(m-CzFSOPy)2IrPic,0,554,0.3810,0.64,CH2Cl2,10.1016/j.dyepig.2018.07.019,NaN,1
1450,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir1-me,0,608,0.4000,2.12,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1
1451,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir2-cf3,0,604,0.4100,2.21,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1
1452,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir3-me,0,628,0.6000,2.06,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1
1453,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir4-cf3,0,602,0.6700,2.09,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1

In [4]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer  # This just enables the feature
from sklearn.impute import IterativeImputer  # This is the actual imputer class

# Create the imputer instance with parameters
imp_abs = IterativeImputer(random_state=42)

# Fit and transform
imp_abs.fit(np.array(df['Max_wavelength(nm)']).reshape(-1,1))
change_nm_abs = imp_abs.transform(np.array(df['Max_wavelength(nm)']).reshape(-1,1))
change_nm_abs = change_nm_abs.flatten()
df['Max_wavelength(nm)'] = change_nm_abs

In [5]:
test = pd.DataFrame(change_nm_abs, columns=['Emission (nm)'])
test.to_csv('./new_metal_em.csv')

In [7]:
solv = set(df['Solvent'])
solv

{'2-MeTHF',
 'C2H5OH',
 'CH2Cl2',
 'CH3CN',
 'CH3OH',
 'CHCl3',
 'DCE',
 'DMF',
 'DMSO',
 'H2O',
 'PBS',
 'THF',
 'acetone',
 'cyclohexane',
 nan,
 'toluene'}

In [8]:
import pandas as pd
import numpy as np

# Создаем словарь соответствия растворителя и его SMILES
solvent_to_smiles = {
    '2-MeTHF': 'CC1CCCO1',
    'C2H5OH': 'CCO',
    'CH2Cl2': 'ClCCl',
    'CH3CN': 'CC#N',
    'CH3OH': 'CO',
    'CHCl3': 'C(Cl)(Cl)Cl',
    'DCE': 'ClCCCl',
    'DMF': 'CN(C)C=O',
    'DMSO': 'CS(=O)C',
    'H2O': 'O',
    'PBS': np.nan,  # или 'N/A', если предпочитаете строку
    'THF': 'C1CCOC1',
    'acetone': 'CC(=O)C',
    'cyclohexane': 'C1CCCCC1',
    'toluene': 'Cc1ccccc1',
    'nan': np.nan,
    np.nan: np.nan  # обрабатываем пропущенные значения
}

# Применяем словарь к колонке 'Solvent' и создаем новую колонку 'Solvent_SMILES'
df['Solvent_SMILES'] = df['Solvent'].map(solvent_to_smiles)

# Если в колонке 'Solvent' есть значения, которых нет в словаре,
# они будут преобразованы в NaN в новой колонке.
# Вы можете проверить это:
print("Уникальные SMILES:")
print(df['Solvent_SMILES'].unique())

Уникальные SMILES:
['ClCCl' 'CO' nan 'CS(=O)C' 'CC#N' 'C1CCOC1' 'C(Cl)(Cl)Cl' 'Cc1ccccc1'
 'ClCCCl' 'CN(C)C=O' 'CC1CCCO1' 'O' 'CCO' 'C1CCCCC1' 'CC(=O)C']

In [9]:
df

,L1,L2,L3,Counterion,Abbreviation_in_the_article,Charge,Max_wavelength(nm),PLQY,tau(s*10^-6),Solvent,DOI,Notes,PLQY_in_train,Solvent_SMILES
0,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C([O-])c1ccccn1,NaN,1,0,553.0,0.2500,4.32,CH2Cl2,10.3390/molecules27010232,NaN,1,ClCCl
1,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,c1ccc(-c2ccccn2)nc1,FP(F)(F)(F)(F)F,2,1,570.0,0.1700,6.14,CH2Cl2,10.3390/molecules27010232,NaN,1,ClCCl
2,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccnc(-c2cc(C(=O)O)ccn2)c1,FP(F)(F)(F)(F)F,3,1,595.0,0.1400,0.82,CH3OH,10.3390/molecules27010232,NaN,1,CO
3,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=S(=O)([O-])c1ccc(P(c2ccc(S(=O)(=O)O[Na])cc2)...,NaN,4,0,555.0,0.0435,41.87,PBS,10.3390/molecules27010232,NaN,1,NaN
4,[c-]1ccccc1-c1ccccn1,[c-]1ccccc1-c1ccccn1,CCOP(=O)(OCC)c1ccnc(-c2cc(P(=O)(OCC)OCC)ccn2)c1,FP(F)(F)(F)(F)F,Ir(ppy)2bP,1,667.0,0.0020,NaN,CH3OH,10.1002/adhm.202100706,NaN,1,CO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,O=C([O-])c1ccccn1,NaN,(m-CzFSOPy)2IrPic,0,554.0,0.3810,0.64,CH2Cl2,10.1016/j.dyepig.2018.07.019,NaN,1,ClCCl
1450,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir1-me,0,608.0,0.4000,2.12,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,ClCCl
1451,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir2-cf3,0,604.0,0.4100,2.21,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,ClCCl
1452,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir3-me,0,628.0,0.6000,2.06,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,ClCCl
1453,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir4-cf3,0,602.0,0.6700,2.09,CH2Cl2,10.1016/j.jorganchem.2018.09.009,NaN,1,ClCCl

In [10]:
lig_1 = list(df['L1'])
lig_2 = list(df['L2'])
lig_3 = list(df['L3'])
solv = list(df['Solvent_SMILES'])

In [11]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from tqdm import tqdm
import pybel  # Open Babel Python bindings
import warnings
warnings.filterwarnings('ignore')

# Функция нормализации SMILES через Open Babel
def normalize_smiles_with_openbabel(smiles_str):
    """
    Нормализует SMILES строку с использованием Open Babel.
    Возвращает канонический SMILES с исправленной структурой или None при ошибке.
    """
    if pd.isna(smiles_str) or smiles_str is None or str(smiles_str).strip() == '':
        return None
    
    try:
        # Читаем SMILES через Open Babel
        mol = pybel.readstring("smi", str(smiles_str).strip())
        # Удаляем частичные заряды (если есть)
        mol.OBMol.DeletePartialCharges()
        # Устанавливаем ароматичность
        mol.OBMol.SetAromaticPerceived()
        # Конвертируем обратно в SMILES (канонический, с исправленной структурой)
        normalized_smiles = mol.write("smi", opt={"a": True, "h": True}).strip()
        # Удаляем точку с запятой и лишние пробелы
        normalized_smiles = normalized_smiles.split()[0].strip()
        return normalized_smiles
    except Exception as e:
        #print(f"Ошибка нормализации SMILES '{smiles_str}': {str(e)}")
        return None

# Функция для генерации Morgan fingerprint из SMILES
def smiles_to_morgan(smiles, radius=2, nBits=2048):
    """
    Конвертирует SMILES в Morgan fingerprint.
    Возвращает numpy array длиной nBits или нулевой вектор если SMILES некорректный/NaN
    """
    if pd.isna(smiles) or smiles is None or smiles.strip() == '':
        return np.zeros(nBits, dtype=int)
    
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return np.zeros(nBits, dtype=int)
        
        # Генерация Morgan fingerprint как битового вектора
        fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=nBits)
        return np.array(fp)
    except Exception as e:
        #print(f"Ошибка при генерации fingerprint для '{smiles}': {str(e)}")
        return np.zeros(nBits, dtype=int)

# Основной код обработки
def process_smiles_and_generate_fps(df, output_normalized_file='normalized_smiles.csv'):
    """
    Основная функция обработки:
    1. Нормализует SMILES через Open Babel
    2. Сохраняет нормализованные SMILES в отдельный файл
    3. Генерирует Morgan fingerprints на основе нормализованных SMILES
    4. Добавляет fingerprints в исходный DataFrame
    
    Args:
        df: Исходный DataFrame
        output_normalized_file: Имя файла для сохранения нормализованных SMILES
    
    Returns:
        tuple: (DataFrame с fingerprints, DataFrame с нормализованными SMILES)
    """
    
    print("Начало обработки данных...")
    print(f"Исходный DataFrame: {df.shape[0]} строк, {df.shape[1]} колонок")
    
    # Создаем копию для нормализованных SMILES
    normalized_df = pd.DataFrame()
    normalized_df['index'] = df.index.copy()
    
    # Список столбцов для нормализации
    smiles_columns = {
        'lig_1': 'lig_1_normalized',
        'lig_2': 'lig_2_normalized', 
        'lig_3': 'lig_3_normalized',
        'Solvent_SMILES': 'solvent_normalized'
    }
    
    print("\n=== Этап 1: Нормализация SMILES через Open Babel ===")
    
    # Нормализуем каждый столбец
    for original_col, normalized_col in smiles_columns.items():
        if original_col in df.columns:
            print(f"Нормализация колонки '{original_col}'...")
            
            # Применяем нормализацию с прогресс-баром
            normalized_smiles_list = []
            for smiles in tqdm(df[original_col].values, desc=f"Нормализация {original_col}"):
                normalized_smiles = normalize_smiles_with_openbabel(smiles)
                normalized_smiles_list.append(normalized_smiles)
            
            # Сохраняем в оба DataFrame
            normalized_df[normalized_col] = normalized_smiles_list
            
            print(f"  - Успешно обработано: {len([x for x in normalized_smiles_list if x is not None])} из {len(normalized_smiles_list)}")
        else:
            print(f"Предупреждение: Колонка '{original_col}' не найдена в DataFrame")
    
    # Сохраняем нормализованные SMILES в отдельный файл
    print(f"\nСохранение нормализованных SMILES в файл: {output_normalized_file}")
    normalized_df.to_csv(output_normalized_file, index=False)
    print(f"Нормализованный dataset сохранен: {normalized_df.shape[0]} строк, {normalized_df.shape[1]} колонок")
    
    print("\n=== Этап 2: Генерация Morgan fingerprints на основе нормализованных SMILES ===")
    
    # Создаем копию исходного DataFrame для добавления fingerprints
    result_df = df.copy()
    
    # Параметры fingerprint
    nBits = 2048
    radius = 2
    print(f"Параметры Morgan fingerprint: radius={radius}, nBits={nBits}")
    
    # Обработка каждого типа молекул
    fingerprint_configs = [
        ('lig_1_normalized', 'lig_1', 'Morgan_1_'),
        ('lig_2_normalized', 'lig_2', 'Morgan_2_'),
        ('lig_3_normalized', 'lig_3', 'Morgan_3_'),
        ('solvent_normalized', 'Solvent_SMILES', 'Morgan_solv_abs_')
    ]
    
    for normalized_col, original_col, prefix in fingerprint_configs:
        if normalized_col in normalized_df.columns:
            print(f"\nГенерация fingerprints для '{original_col}' на основе нормализованных SMILES...")
            
            # Получаем нормализованные SMILES
            smiles_list = normalized_df[normalized_col].tolist()
            
            # Генерируем fingerprints
            fps = []
            for smiles in tqdm(smiles_list, desc=f"Генерация {prefix[:-1]}"):
                fp = smiles_to_morgan(smiles, radius, nBits) if smiles else np.zeros(nBits, dtype=int)
                fps.append(fp)
            
            # Добавляем колонки в result_df
            print(f"Добавление {nBits} колонок для '{prefix[:-1]}'...")
            for bit_idx in range(nBits):
                col_name = f"{prefix}{bit_idx}"
                result_df[col_name] = [int(fp[bit_idx]) for fp in fps]
            
            print(f"  - Создано колонок: {nBits}")
        else:
            print(f"Пропуск '{original_col}': нет нормализованных данных")
    
    print("\n=== Завершение обработки ===")
    print(f"Итоговый DataFrame: {result_df.shape[0]} строк, {result_df.shape[1]} колонок")
    
    # Статистика по созданным fingerprints
    created_fps = []
    for prefix in ['Morgan_1_', 'Morgan_2_', 'Morgan_3_', 'Morgan_solv_abs_']:
        cols = [col for col in result_df.columns if col.startswith(prefix)]
        if cols:
            created_fps.append(f"{prefix[:-1]}: {len(cols)} битов")
    
    if created_fps:
        print("\nСозданные fingerprint колонки:")
        for fp_info in created_fps:
            print(f"  - {fp_info}")
    
    return result_df, normalized_df

# Пример использования
if __name__ == "__main__":
    # Загрузка данных (замените на ваш реальный путь)
    # df = pd.read_csv('your_data.csv')
    
    # Пример данных для демонстрации
    print("Пример использования кода:")
    print("1. Загрузите ваш DataFrame:")
    print("   df = pd.read_csv('ваш_файл.csv')")
    print("\n2. Запустите обработку:")
    print("   result_df, normalized_df = process_smiles_and_generate_fps(df, 'normalized_smiles.csv')")
    print("\n3. Проверьте результаты:")
    print("   print(f'Исходные колонки: {df.columns.tolist()}')")
    print("   print(f'Колонки с fingerprints: {[col for col in result_df.columns if col.startswith(\"Morgan_\")][:5]}...')'")
    print("   print(f'Нормализованные SMILES сохранены в: normalized_smiles.csv')")
    
    # Дополнительные рекомендации
    print("\n=== Важные замечания ===")
    print("1. Убедитесь, что установлены необходимые пакеты:")
    print("   pip install pandas numpy rdkit openbabel tqdm")
    print("\n2. Для Open Babel может потребоваться установка системных зависимостей:")
    print("   sudo apt-get install openbabel (Linux)")
    print("   brew install open-babel (Mac)")
    print("   conda install -c conda-forge openbabel (Anaconda)")
    print("\n3. Для больших датасетов:")
    print("   - Рассмотрите возможность уменьшения nBits (например, до 1024)")
    print("   - Используйте параллельную обработку с joblib")
    print("   - Сохраняйте промежуточные результаты")
    print("\n4. Проверка качества нормализации:")
    print("   - Сравните оригинальные и нормализованные SMILES")
    print("   - Проверьте количество успешно обработанных молекул")
    print("   - Визуализируйте проблемные молекулы с помощью RDKit")

Пример использования кода:
1. Загрузите ваш DataFrame:
   df = pd.read_csv('ваш_файл.csv')

2. Запустите обработку:
   result_df, normalized_df = process_smiles_and_generate_fps(df, 'normalized_smiles.csv')

3. Проверьте результаты:
   print(f'Исходные колонки: {df.columns.tolist()}')
   print(f'Колонки с fingerprints: {[col for col in result_df.columns if col.startswith("Morgan_")][:5]}...')'
   print(f'Нормализованные SMILES сохранены в: normalized_smiles.csv')

=== Важные замечания ===
1. Убедитесь, что установлены необходимые пакеты:
   pip install pandas numpy rdkit openbabel tqdm

2. Для Open Babel может потребоваться установка системных зависимостей:
   sudo apt-get install openbabel (Linux)
   brew install open-babel (Mac)
   conda install -c conda-forge openbabel (Anaconda)

3. Для больших датасетов:
   - Рассмотрите возможность уменьшения nBits (например, до 1024)
   - Используйте параллельную обработку с joblib
   - Сохраняйте промежуточные результаты

4. Проверка качества нормализации:
   - Сравните оригинальные и нормализованные SMILES
   - Проверьте количество успешно обработанных молекул
   - Визуализируйте проблемные молекулы с помощью RDKit

In [12]:
import re
import pandas as pd
from openbabel import pybel

def normalize_smiles(smiles_str):
    """
    Нормализует SMILES: исправляет радикалы, заряды, изотопы,
    канонизирует структуру через OpenBabel.
    """
    if pd.isna(smiles_str):
        return None
    
    smiles_str = str(smiles_str).strip()
    
    # Пустая строка
    if not smiles_str or smiles_str == '':
        return None
    
    # === ИСПРАВЛЕНИЯ ПЕРЕД ОБРАБОТКОЙ ===
    
    # 1. Удаляем простые соли (они не несут структурной информации)
    # if smiles_str in {'[Cl-]', '[Br-]', '[I-]', '[F-]', '[O-]N=O'}:
    #     return None
    
    # 2. Исправляем явные радикалы и фрагменты
    radical_fixes = {
        '[H]': 'C',      # Водород → метан (минимальная органика)
        '[C]': 'C',      # Радикал → нейтральный углерод
        '[CH]': 'C',     # Метин-радикал → углерод
        '[CH2]': 'C',    # Метилен-радикал → углерод
        '[c-]':'C',
        '[C-]':'C',
        '[O-]':'O',
        '[O]':'O',
        '[CH3]': 'C',    # Метил-радикал → углерод
        '[Si]': '[Si]',  # Кремний оставляем (может быть валиден)
        '[C]1': 'C1',    # Радикал в цикле → нормальный углерод
        '[Cl-]':'[Cl]',
        '[C]#[O]':'C#O',
        '[Br--]':'[Br]',
        '[Br-2]':'[Br]',
        '[CH-]':'C',
        '[n-]':'N',
        '[N-]':'N',
        '[C-2]':'C',
        '[N]':'N',
        '[C@@]':'C@@',
        '[C@]':'C@',
    }
    
    for radical, fixed in radical_fixes.items():
        smiles_str = smiles_str.replace(radical, fixed)
    
    # 3. Исправляем странные формы CO (монооксид углерода)
    smiles_str = smiles_str.replace('[C-2]=O', 'C=O')  # Кетон
    smiles_str = smiles_str.replace('[C#O]', 'C#N')    # Нитрил (ближайший аналог)
    smiles_str = smiles_str.replace('[C]#[O]', 'C#N')
    
    # 4. Убираем заряды (преобразуем в нейтральные формы)
    charge_patterns = [
        (r'\[c-\]', 'c'),
        (r'\[n-\]', 'n'),
        (r'\[s-\]', 's'),
        (r'\[o-\]', 'o'),
        (r'\[O-\]', 'O'),
        (r'\[N-\]', 'N'),
        (r'\[C-\]', 'C'),
        (r'\[S-\]', 'S'),
        (r'\[C\+\]', 'C'),
        (r'\[N\+\]', 'N'),
        (r'\[O\+\]', 'O'),
        (r'\[n\+\]', 'n'),
        (r'\[CH2\]', 'C'),

    ]
    
    for pattern, replacement in charge_patterns:
        smiles_str = re.sub(pattern, replacement, smiles_str)
    
    # 5. Удаляем изотопные метки
    smiles_str = re.sub(r'\[(\d+)([A-Z][a-z]?)\]', r'[\2]', smiles_str)  # [2H] → [H]
    smiles_str = re.sub(r'\[2H\]', '[H]', smiles_str)
    smiles_str = re.sub(r'\[3H\]', '[H]', smiles_str)
    
    # 6. Удаляем только тяжёлые металлы (но оставляем органометаллы с углеродом)
    heavy_metals = ['Zr', 'Ta', 'Sn', 'Ag', 'As', 'Hg', 'Pb', 'Cd']
    metal_pattern = r'\[(' + '|'.join(heavy_metals) + r')[^\]]*\]'
    
    # Если SMILES - только металл, удаляем
    if re.match(r'^\[(' + '|'.join(heavy_metals) + r')[^\]]*\]$', smiles_str):
        return None
    
    # Если металл + органика, удаляем только металл
    smiles_str = re.sub(metal_pattern, '', smiles_str)
    
    # 7. Проверка после исправлений
    if not smiles_str or smiles_str.strip() == '':
        return None
    
    # === КАНОНИЗАЦИЯ ЧЕРЕЗ OPENBABEL ===
    try:
        mol = pybel.readstring("smi", smiles_str)
        mol.addh()  # Добавляем водороды
        
        # Канонический SMILES
        canonical_smiles = mol.write("can").strip().split()[0]
        
        return canonical_smiles
        
    except Exception as e:
        # Если OpenBabel не может обработать - возвращаем исправленный вариант
        print(f"Предупреждение: не удалось канонизировать '{smiles_str}': {e}")
        return smiles_str

# === ТЕСТЫ ===
test_cases = [
    '[Ir+2]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc(OC)cc1-c1cc(OC)ccn1)',  # Ваш пример с радикалом
]

for smi in test_cases:
    result = normalize_smiles(smi)
    print(f"{smi:40s} → {result}")

[Ir+2]([c-]1cc(C=O)ccc1-c1ccccn1)([c-]1cc(C=O)ccc1-c1ccccn1)(n1ccc(OC)cc1-c1cc(OC)ccn1) → COC1=C[CH]N(C(=C1)c1nccc(c1)OC)[Ir+2](C1[CH]C(=CC=C1c1ccccn1)C=O)C1[CH]C(=CC=C1c1ccccn1)C=O

==============================
*** Open Babel Warning  in ParseSmiles
  Failed to kekulize aromatic SMILES

In [13]:
result_df, normalized_df = process_smiles_and_generate_fps(df, 'normalized_smiles_em.csv')

Начало обработки данных...
Исходный DataFrame: 1454 строк, 14 колонок

=== Этап 1: Нормализация SMILES через Open Babel ===
Предупреждение: Колонка 'lig_1' не найдена в DataFrame
Предупреждение: Колонка 'lig_2' не найдена в DataFrame
Предупреждение: Колонка 'lig_3' не найдена в DataFrame
Нормализация колонки 'Solvent_SMILES'...

Нормализация Solvent_SMILES: 100%|██████████| 1454/1454 [00:00<00:00, 133578.32it/s]

  - Успешно обработано: 0 из 1454

Сохранение нормализованных SMILES в файл: normalized_smiles_em.csv
Нормализованный dataset сохранен: 1454 строк, 2 колонок

=== Этап 2: Генерация Morgan fingerprints на основе нормализованных SMILES ===
Параметры Morgan fingerprint: radius=2, nBits=2048
Пропуск 'lig_1': нет нормализованных данных
Пропуск 'lig_2': нет нормализованных данных
Пропуск 'lig_3': нет нормализованных данных

Генерация fingerprints для 'Solvent_SMILES' на основе нормализованных SMILES...

Генерация Morgan_solv_abs: 100%|██████████| 1454/1454 [00:00<00:00, 412815.14it/s]

Добавление 2048 колонок для 'Morgan_solv_abs'...

  - Создано колонок: 2048

=== Завершение обработки ===
Итоговый DataFrame: 1454 строк, 2062 колонок

Созданные fingerprint колонки:
  - Morgan_solv_abs: 2048 битов

In [14]:
result_df

,L1,L2,L3,Counterion,Abbreviation_in_the_article,Charge,Max_wavelength(nm),PLQY,tau(s*10^-6),Solvent,...,Morgan_solv_abs_2038,Morgan_solv_abs_2039,Morgan_solv_abs_2040,Morgan_solv_abs_2041,Morgan_solv_abs_2042,Morgan_solv_abs_2043,Morgan_solv_abs_2044,Morgan_solv_abs_2045,Morgan_solv_abs_2046,Morgan_solv_abs_2047
0,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C([O-])c1ccccn1,NaN,1,0,553.0,0.2500,4.32,CH2Cl2,...,0,0,0,0,0,0,0,0,0,0
1,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,c1ccc(-c2ccccn2)nc1,FP(F)(F)(F)(F)F,2,1,570.0,0.1700,6.14,CH2Cl2,...,0,0,0,0,0,0,0,0,0,0
2,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccnc(-c2cc(C(=O)O)ccn2)c1,FP(F)(F)(F)(F)F,3,1,595.0,0.1400,0.82,CH3OH,...,0,0,0,0,0,0,0,0,0,0
3,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=S(=O)([O-])c1ccc(P(c2ccc(S(=O)(=O)O[Na])cc2)...,NaN,4,0,555.0,0.0435,41.87,PBS,...,0,0,0,0,0,0,0,0,0,0
4,[c-]1ccccc1-c1ccccn1,[c-]1ccccc1-c1ccccn1,CCOP(=O)(OCC)c1ccnc(-c2cc(P(=O)(OCC)OCC)ccn2)c1,FP(F)(F)(F)(F)F,Ir(ppy)2bP,1,667.0,0.0020,NaN,CH3OH,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,O=C([O-])c1ccccn1,NaN,(m-CzFSOPy)2IrPic,0,554.0,0.3810,0.64,CH2Cl2,...,0,0,0,0,0,0,0,0,0,0
1450,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir1-me,0,608.0,0.4000,2.12,CH2Cl2,...,0,0,0,0,0,0,0,0,0,0
1451,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PIQ-Ir2-cf3,0,604.0,0.4100,2.21,CH2Cl2,...,0,0,0,0,0,0,0,0,0,0
1452,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,Cc1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir3-me,0,628.0,0.6000,2.06,CH2Cl2,...,0,0,0,0,0,0,0,0,0,0
1453,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)[n-]n1,NaN,PQZ-Ir4-cf3,0,602.0,0.6700,2.09,CH2Cl2,...,0,0,0,0,0,0,0,0,0,0

In [17]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from tqdm import tqdm
import pybel  # Open Babel Python bindings
import re  # Добавлен импорт для регулярных выражений
import warnings
warnings.filterwarnings('ignore')
from copy import deepcopy

# === УЛУЧШЕННАЯ ФУНКЦИЯ НОРМАЛИЗАЦИИ SMILES ===
def normalize_smiles_with_openbabel(smiles_str):
    """
    Супер-функция нормализации SMILES:
    1. Исправляет радикалы, заряды, изотопы
    2. Удаляет тяжелые металлы и простые соли
    3. Канонизирует структуру через OpenBabel
    4. Возвращает валидный SMILES или None при ошибке
    """
    if pd.isna(smiles_str):
        return None
    smiles_str_ = deepcopy(smiles_str)
    smiles_str = str(smiles_str).strip()
    
    # Пустая строка
    if not smiles_str or smiles_str == '':
        return None
    
    # === ИСПРАВЛЕНИЯ ПЕРЕД ОБРАБОТКОЙ ===
    
    # 1. Удаляем простые соли (они не несут структурной информации)
    # if smiles_str in {'[Cl-]', '[Br-]', '[I-]', '[F-]', '[O-]N=O'}:
    #     return None
    
    radical_fixes = {
        '[H]': 'C',      # Водород → метан (минимальная органика)
        '[C]': 'C',      # Радикал → нейтральный углерод
        '[CH]': 'C',     # Метин-радикал → углерод
        '[CH2]': 'C',    # Метилен-радикал → углерод
        '[c-]':'C',
        '[C-]':'C',
        '[O-]':'O',
        '[O]':'O',
        '[CH3]': 'C',    # Метил-радикал → углерод
        '[Si]': '[Si]',  # Кремний оставляем (может быть валиден)
        '[C]1': 'C1',    # Радикал в цикле → нормальный углерод
        '[Cl-]':'[Cl]',
        '[C]#[O]':'C#O',
        '[Br--]':'[Br]',
        '[Br-2]':'[Br]',
        '[CH-]':'C',
        '[n-]':'N',
        '[N-]':'N',
        '[C-2]':'C',
        '[N]':'N',
        '[C@@]':'C@@',
        '[C@]':'C@',
    }
    
    for radical, fixed in radical_fixes.items():
        smiles_str = smiles_str.replace(radical, fixed)
    
    # 3. Исправляем странные формы CO (монооксид углерода)
    smiles_str = smiles_str.replace('[C-2]=O', 'C=O')  # Кетон
    smiles_str = smiles_str.replace('[C#O]', 'C#N')    # Нитрил (ближайший аналог)
    smiles_str = smiles_str.replace('[C]#[O]', 'C#N')
    
    # 4. Убираем заряды (преобразуем в нейтральные формы)
    charge_patterns = [
        (r'\[c-\]', 'c'),
        (r'\[n-\]', 'n'),
        (r'\[s-\]', 's'),
        (r'\[o-\]', 'o'),
        (r'\[O-\]', 'O'),
        (r'\[N-\]', 'N'),
        (r'\[C-\]', 'C'),
        (r'\[S-\]', 'S'),
        (r'\[C\+\]', 'C'),
        (r'\[N\+\]', 'N'),
        (r'\[O\+\]', 'O'),
        (r'\[n\+\]', 'n'),
        (r'\[CH2\]', 'C'),

    ]
    
    for pattern, replacement in charge_patterns:
        smiles_str = re.sub(pattern, replacement, smiles_str)
    
    # 5. Удаляем изотопные метки
    smiles_str = re.sub(r'\[(\d+)([A-Z][a-z]?)\]', r'[\2]', smiles_str)  # [2H] → [H]
    smiles_str = re.sub(r'\[2H\]', '[H]', smiles_str)
    smiles_str = re.sub(r'\[3H\]', '[H]', smiles_str)
    
    # 6. Удаляем только тяжёлые металлы (но оставляем органометаллы с углеродом)
    heavy_metals = ['Zr', 'Ta', 'Sn', 'Ag', 'As', 'Hg', 'Pb', 'Cd','Na']
    metal_pattern = r'\[(' + '|'.join(heavy_metals) + r')[^\]]*\]'
    
    # Если SMILES - только металл, удаляем
    if re.match(r'^\[(' + '|'.join(heavy_metals) + r')[^\]]*\]$', smiles_str):
        return None
    
    # Если металл + органика, удаляем только металл
    smiles_str = re.sub(metal_pattern, '', smiles_str)
    
    # 7. Проверка после исправлений
    if not smiles_str or smiles_str.strip() == '':
        return smiles_str_
    
    # === ЭТАП 2: КАНОНИЗАЦИЯ ЧЕРЕЗ OPENBABEL ===
    try:
        # Парсим SMILES через OpenBabel
        mol = pybel.readstring("smi", smiles_str)
        
        # Критические проверки валидности
        if mol.OBMol.NumAtoms() == 0:
            return None
        
        # Добавляем водороды и стандартизуем структуру
        mol.addh()
        mol.OBMol.SetAromaticPerceived()  # Явно устанавливаем ароматичность
        mol.OBMol.DeletePartialCharges()   # Удаляем частичные заряды
        
        # Генерируем канонический SMILES
        canonical_smiles = mol.write("can", opt={"h": True}).strip()
        canonical_smiles = canonical_smiles.split()[0]  # Удаляем комментарии
        
        # Финальная валидация RDKit
        if Chem.MolFromSmiles(canonical_smiles) is None:
            return smiles_str_
            
        return canonical_smiles
        
    except Exception:
        # Безопасный fallback: пробуем предобработанный SMILES
        if Chem.MolFromSmiles(smiles_str) is not None:
            return smiles_str
        return smiles_str_

# Функция для генерации Morgan fingerprint из SMILES
def smiles_to_morgan(smiles, radius=2, nBits=2048):
    """
    Конвертирует SMILES в Morgan fingerprint.
    Возвращает numpy array длиной nBits или нулевой вектор если SMILES некорректный/NaN
    """
    if not smiles or pd.isna(smiles):
        return np.zeros(nBits, dtype=np.int8)
    
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return np.zeros(nBits, dtype=np.int8)
        
        # Оптимизированная генерация fingerprint
        fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=nBits)
        return np.array(fp, dtype=np.int8)
    except Exception:
        return np.zeros(nBits, dtype=np.int8)

# Основной код обработки
def process_smiles_and_generate_fps(df, output_normalized_file='normalized_smiles.csv'):
    """
    Основная функция обработки:
    1. Нормализует SMILES через улучшенную супер-функцию
    2. Сохраняет нормализованные SMILES в отдельный файл
    3. Генерирует Morgan fingerprints на основе нормализованных SMILES
    4. Добавляет fingerprints в исходный DataFrame
    
    Args:
        df: Исходный DataFrame
        output_normalized_file: Имя файла для сохранения нормализованных SMILES
    
    Returns:
        tuple: (DataFrame с fingerprints, DataFrame с нормализованными SMILES)
    """
    
    print("🚀 Начало обработки данных...")
    print(f"📊 Исходный DataFrame: {df.shape[0]} строк, {df.shape[1]} колонок")
    
    # Создаем копию для нормализованных SMILES
    normalized_df = pd.DataFrame()
    normalized_df['index'] = df.index.copy()
    
    # Список столбцов для нормализации
    smiles_columns = {
        'L1': 'lig_1_normalized',
        'L2': 'lig_2_normalized', 
        'L3': 'lig_3_normalized',
        'Solvent_SMILES': 'solvent_normalized'
    }
    
    print("\n✨ === Этап 1: Продвинутая нормализация SMILES ===")
    
    # Нормализуем каждый столбец
    stats = {}
    for original_col, normalized_col in smiles_columns.items():
        if original_col not in df.columns:
            print(f"⚠️  Предупреждение: Колонка '{original_col}' не найдена в DataFrame")
            continue
            
        print(f"\n🔧 Нормализация колонки '{original_col}'...")
        valid_count = 0
        normalized_list = []
        
        # Обработка с прогресс-баром
        for smiles in tqdm(df[original_col].values, desc=f"Обработка {original_col}"):
            norm_smiles = normalize_smiles_with_openbabel(smiles)
            normalized_list.append(norm_smiles)
            if norm_smiles:
                valid_count += 1
        
        normalized_df[normalized_col] = normalized_list
        stats[original_col] = (valid_count, len(normalized_list))
        print(f"✅ Успешно: {valid_count}/{len(normalized_list)} молекул")
    
    # Сохраняем нормализованные SMILES
    print(f"\n💾 Сохранение нормализованных SMILES в: {output_normalized_file}")
    normalized_df.to_csv(output_normalized_file, index=False)
    print(f"✅ Файл сохранен: {normalized_df.shape[0]} строк")
    
    print("\n🧠 === Этап 2: Генерация Morgan fingerprints ===")
    
    # Подготовка результирующего DataFrame
    result_df = df.copy()
    nBits = 2048
    radius = 2
    print(f"⚙️  Параметры fingerprint: radius={radius}, nBits={nBits}")
    
    # Генерация fingerprints для каждого типа молекул
    fingerprint_configs = [
        ('lig_1_normalized', 'L1', 'Morgan_1_'),
        ('lig_2_normalized', 'L2', 'Morgan_2_'),
        ('lig_3_normalized', 'L3', 'Morgan_3_'),
        ('solvent_normalized', 'Solvent_SMILES', 'Morgan_solv_abs_')
    ]
    
    total_bits = 0
    for norm_col, orig_col, prefix in fingerprint_configs:
        if norm_col not in normalized_df.columns:
            print(f"⏭️  Пропуск '{orig_col}': нет нормализованных данных")
            continue
            
        print(f"\n🧪 Генерация fingerprints для '{orig_col}'...")
        fps = []
        
        # Генерация векторов
        for smiles in tqdm(normalized_df[norm_col], desc=f"Fingerprint {prefix.strip('_')}"):
            fps.append(smiles_to_morgan(smiles, radius, nBits))
        
        # Добавление колонок в DataFrame
        print(f"עמוד Добавление {nBits} битовых колонок...")
        for bit_idx in range(nBits):
            col_name = f"{prefix}{bit_idx}"
            result_df[col_name] = [int(fp[bit_idx]) for fp in fps]
        total_bits += nBits
    
    # === ФИНАЛЬНАЯ СТАТИСТИКА ===
    print("\n🎉 === Обработка завершена! ===")
    print(f"📈 Итоговый DataFrame: {result_df.shape[0]} строк, {result_df.shape[1]} колонок")
    print(f"🧬 Создано fingerprint-колонок: {total_bits}")
    
    # Детальная статистика по колонкам
    print("\n📊 Детальная статистика нормализации:")
    for col, (valid, total) in stats.items():
        print(f"  - {col}: {valid}/{total} ({valid/total:.1%})")
    
    # Проверка качества нормализации
    invalid_count = sum(1 for col in normalized_df.columns if col.endswith('_normalized') 
                        for val in normalized_df[col] if val is None)
    if invalid_count:
        print(f"\n⚠️  Внимание: обнаружено {invalid_count} некорректных SMILES! "
              f"Проверьте файл '{output_normalized_file}'")
    
    return result_df, normalized_df

# Пример использования
if __name__ == "__main__":
    # Загрузка данных (пример)
    print("🧪 Демонстрация работы супер-функции нормализации:")
    test_smiles = [
        'C1=CC=[C]C(=C1)c1c2ccccc2ccn1',  # Радикал в цикле
        '[O-]N=O',                         # Простая соль
        '[CH3][C-2]=O',                    # Аномальный формальдегид
        '[2H]C([3H])([4H])C',              # Изотопы
        'CCO.[Pb]',                        # Тяжелый металл
        'N[C@@H](C)C(=O)O'                 # Валидная аминокислота
    ]
    
    print("\n🔍 Тестирование нормализации:")
    for smi in test_smiles:
        result = normalize_smiles_with_openbabel(smi)
        status = "✅ Валидный" if result else "❌ Невалидный"
        print(f"  {smi:25s} → {status} → {result or 'None'}")
    
    print("\n💡 Инструкция по использованию:")
    print("1. Загрузите данные: df = pd.read_csv('ваш_файл.csv')")
    print("2. Запустите обработку: result_df, norm_df = process_smiles_and_generate_fps(df)")
    print("3. Сохраните результаты: result_df.to_csv('результаты.csv', index=False)")
    
    print("\n⚡ Рекомендации для больших датасетов:")
    print("   - Используйте nBits=1024 для ускорения")
    print("   - Запускайте обработку на GPU-сервере")
    print("   - Разбивайте данные на чанки при работе с >1M строк")

🧪 Демонстрация работы супер-функции нормализации:

🔍 Тестирование нормализации:
  C1=CC=[C]C(=C1)c1c2ccccc2ccn1 → ✅ Валидный → C1=CC=CC(=C1)c1c2ccccc2ccn1
  [O-]N=O                   → ✅ Валидный → ON=O
  [CH3][C-2]=O              → ✅ Валидный → CC=O
  [2H]C([3H])([4H])C        → ✅ Валидный → [H]C([H])([H])C
  CCO.[Pb]                  → ✅ Валидный → CCO.[Pb]
  N[C@@H](C)C(=O)O          → ✅ Валидный → N[C@@H](C)C(=O)O

💡 Инструкция по использованию:
1. Загрузите данные: df = pd.read_csv('ваш_файл.csv')
2. Запустите обработку: result_df, norm_df = process_smiles_and_generate_fps(df)
3. Сохраните результаты: result_df.to_csv('результаты.csv', index=False)

⚡ Рекомендации для больших датасетов:
   - Используйте nBits=1024 для ускорения
   - Запускайте обработку на GPU-сервере
   - Разбивайте данные на чанки при работе с >1M строк

[12:50:34] SMILES Parse Error: syntax error while parsing: CCO.
[12:50:34] SMILES Parse Error: check for mistakes around position 4:
[12:50:34] CCO.
[12:50:34] ~~~^
[12:50:34] SMILES Parse Error: Failed parsing SMILES 'CCO.' for input: 'CCO.'

In [18]:
result_df, normalized_df = process_smiles_and_generate_fps(df, 'normalized_smiles_em_2.csv')
result_df.to_csv('result_em_2.csv', index=False)

🚀 Начало обработки данных...
📊 Исходный DataFrame: 1454 строк, 14 колонок

✨ === Этап 1: Продвинутая нормализация SMILES ===

🔧 Нормализация колонки 'L1'...

Обработка L1:   0%|          | 0/1454 [00:00<?, ?it/s][12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 9 11 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 17 18 23
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 17 18 23
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 17 18 23
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 10 11 23 24 44 45
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 15 16
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 3 14 15 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 11 13 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 3 16 17 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 7 9 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 7 9 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 15 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 3 14 15 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 15 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 7 9 11 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 12 13 15 17 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 9 11 13 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 20 21
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 3 16 17 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26 27
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26 27
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 17 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 17 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26 27
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 35 55 56 57 58 59 60 61
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 43 44
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 34 53 54 55 56 57 58 59
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 13 14 16 17 18 19 20 21 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
Обработка L1:   6%|▌         | 87/1454 [00:00<00:01, 866.76it/s][12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 9 10 12 23 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 20 21
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 22 23
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 23 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 13 14 16 17 18 19 20 21 49 50 51 52 53 54 55 56 57 58 59 60 61
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 21 23 24 25 26 27 28 29 30 31 32
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 10 11 13 14 15 16 17 18 30 31 32 33 34 35 36 37 38 39 40 41 42
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 58 59
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 30 50 51 52 53 54 55 56 57 58 59
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 13 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 13 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 13 14 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 13 14 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 13 14 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 5 29
[12:50:37] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
Обработка L1:  12%|█▏        | 176/1454 [00:00<00:01, 875.03it/s][12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 19 20 21 22 23 24
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 6 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 12
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 3 10 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 26 27
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 26 27
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 26 27
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 28 29
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 28 29
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 5 28 29
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 16 17 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 22 23 24 25 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 22 23 24 25 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 22 23 24 25 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 10 11
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
Обработка L1:  18%|█▊        | 265/1454 [00:00<00:01, 881.80it/s][12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 16 17 18 19 20 21 23 24 25 26 27 28
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 5 7 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 7
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 4 6 7
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 13 14
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:37] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5

✅ Успешно: 1454/1454 молекул

🔧 Нормализация колонки 'L2'...

Обработка L2:   0%|          | 0/1454 [00:00<?, ?it/s][12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 26 27 28
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 5 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 7 8 10 17 18
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 8 9 11 18 19
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 4 6 17 18 23
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 4 6 17 18 23
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 4 6 17 18 23
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 9 10 11 23 24 44 45
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 17 18
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 17 18
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 15 16
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 7 9 10 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 17 18
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 3 14 15 17
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 7 9 11 13 15
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 3 16 17 19
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 4 6 7 9 14
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 4 6 7 9 14
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 15 17
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 3 14 15 17
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 15 17
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 6 7 9 11 22
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 12 13 15 17 28
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 8 9 11 13 24
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 4 5 7 20 21
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 3 16 17 19
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26 27
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26 27
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 16 17 18
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 16 17 18
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 17 18 19
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 17 18 19
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 17 18 19 20 21 22 23 24
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14 15 16 17 19 20 21 22 23 24 25 26 27
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 12
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 9 11 12 17 18
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 17
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 17
[12:50:38] Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 4 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 35 55 56 57 58 59 60 61
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 43 44
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 34 53 54 55 56 57 58 59
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 13 14 16 17 18 19 20 21 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
Обработка L2:   6%|▋         | 92/1454 [00:00<00:01, 914.86it/s][12:50:39] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 9 10 12 23 24
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 12 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 12 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 4 6 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 5 18 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 5 20 21
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 5 22 23
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 18 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 18 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 7 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 24
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 23 24
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 13 14 16 17 18 19 20 21 49 50 51 52 53 54 55 56 57 58 59 60 61
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 21 23 24 25 26 27 28 29 30 31 32
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 10 11 13 14 15 16 17 18 30 31 32 33 34 35 36 37 38 39 40 41 42
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 14 15 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 58 59
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 30 50 51 52 53 54 55 56 57 58 59
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 13 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 13 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 6 13 14 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 6 13 14 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 6 13 14 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 5 29
[12:50:39] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 17 18 19 20 21 22
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 19 20 21 22 23 24
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9 10 11
Обработка L2:  13%|█▎        | 184/1454 [00:00<00:01, 892.00it/s][12:50:39] Can't kekulize mol.  Unkekulized atoms: 6 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 12
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 12 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 3 10 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 26 27
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 26 27
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 26 27
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 5 28 29
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 5 28 29
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 5 28 29
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9 10 11 12 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 8 9 10 11 12 13 14 15 16 17 18 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 22 23 24 25 26 27 28
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 22 23 24 25 26 27 28
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 22 23 24 25 26 27 28
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 7 8 9
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16 17 18 19 20
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 9 10 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 6 8 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 6 7 8 9 10 11
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 13 14 15 16 17 18
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 8 10 11 12 13 14 15
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 16 17 18 19 20 21 23 24 25 26 27 28
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 9 11 12 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 5 7 18 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 11 13 14 15 16
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 12 14 15 16 17
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 2 3 4 5 6 7 8 10 11 12 13 14 15 16 17 18 19
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 6 7
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 4 6 7
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
Обработка L2:  19%|█▉        | 277/1454 [00:00<00:01, 906.87it/s][12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 13 14
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 5 7 8 9 10
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5
[12:50:39] Can't kekulize mol.  Unkekulized atoms: 1 2 4 11 13

✅ Успешно: 1454/1454 молекул

🔧 Нормализация колонки 'L3'...

Обработка L3:   0%|          | 0/1454 [00:00<?, ?it/s][12:50:40] Explicit valence for atom # 2 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 58 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 27 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 15 N, 4, is greater than permitted
Обработка L3:  65%|██████▌   | 948/1454 [00:00<00:00, 9387.35it/s][12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 13
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 13
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 13
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 19
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 19
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 15
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 15
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 15
[12:50:40] Can't kekulize mol.  Unkekulized atoms: 2 4 15
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 58 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 58 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 58 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 58 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:50:40] Explicit valence for atom # 1 N, 4, is greater than permitted
Обработка L3: 100%|██████████| 1454/1454 [00:00<00:00, 8397.39it/s]

✅ Успешно: 1454/1454 молекул

🔧 Нормализация колонки 'Solvent_SMILES'...

Обработка Solvent_SMILES: 100%|██████████| 1454/1454 [00:00<00:00, 46332.17it/s]

✅ Успешно: 1439/1454 молекул

💾 Сохранение нормализованных SMILES в: normalized_smiles_em_2.csv
✅ Файл сохранен: 1454 строк

🧠 === Этап 2: Генерация Morgan fingerprints ===
⚙️  Параметры fingerprint: radius=2, nBits=2048

🧪 Генерация fingerprints для 'L1'...

Fingerprint Morgan_1:   0%|          | 0/1454 [00:00<?, ?it/s][12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:   3%|▎         | 39/1454 [00:00<00:03, 386.74it/s][12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:   5%|▌         | 79/1454 [00:00<00:03, 390.60it/s][12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:40] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:   8%|▊         | 119/1454 [00:00<00:03, 394.00it/s][12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:  11%|█         | 159/1454 [00:00<00:03, 393.10it/s][12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:  14%|█▎        | 199/1454 [00:00<00:03, 381.26it/s][12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:  16%|█▋        | 238/1454 [00:00<00:03, 380.68it/s][12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:  19%|█▉        | 277/1454 [00:00<00:03, 358.62it/s][12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_1:  22%|██▏       | 314/1454 [00:00<00:03, 302.53it/s][12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator
[12:50:41] DEPRECATION WARNING: please use MorganGenerator

עמוד Добавление 2048 битовых колонок...

🧪 Генерация fingerprints для 'L2'...

Fingerprint Morgan_2:   0%|          | 0/1454 [00:00<?, ?it/s][12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:   3%|▎         | 39/1454 [00:00<00:03, 385.93it/s][12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:   5%|▌         | 78/1454 [00:00<00:03, 351.01it/s][12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:46] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:   8%|▊         | 114/1454 [00:00<00:04, 314.31it/s][12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:  10%|█         | 147/1454 [00:00<00:04, 319.32it/s][12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:  12%|█▏        | 180/1454 [00:00<00:03, 319.53it/s][12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:  15%|█▍        | 217/1454 [00:00<00:03, 334.99it/s][12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:  18%|█▊        | 258/1454 [00:00<00:03, 356.80it/s][12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_2:  20%|██        | 294/1454 [00:00<00:03, 329.08it/s][12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator
[12:50:47] DEPRECATION WARNING: please use MorganGenerator

עמוד Добавление 2048 битовых колонок...

🧪 Генерация fingerprints для 'L3'...

Fingerprint Morgan_3:   0%|          | 0/1454 [00:00<?, ?it/s][12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:53] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:   2%|▏         | 31/1454 [00:00<00:04, 309.02it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:   4%|▍         | 62/1454 [00:00<00:05, 272.18it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:   7%|▋         | 95/1454 [00:00<00:04, 293.89it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:   9%|▉         | 134/1454 [00:00<00:04, 327.96it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:  12%|█▏        | 175/1454 [00:00<00:03, 355.38it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:  15%|█▍        | 216/1454 [00:00<00:03, 370.54it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:  17%|█▋        | 254/1454 [00:00<00:03, 355.24it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:  20%|█▉        | 290/1454 [00:00<00:03, 308.36it/s][12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:54] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_3:  22%|██▏       | 322/1454 [00:01<00:04, 263.46it/s][12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator
[12:50:55] DEPRECATION WARNING: please use MorganGenerator

עמוד Добавление 2048 битовых колонок...

🧪 Генерация fingerprints для 'Solvent_SMILES'...

Fingerprint Morgan_solv_abs:   0%|          | 0/1454 [00:00<?, ?it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:   2%|▏         | 33/1454 [00:00<00:04, 321.11it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:   5%|▍         | 66/1454 [00:00<00:04, 306.78it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:   7%|▋         | 103/1454 [00:00<00:04, 331.59it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:  10%|▉         | 141/1454 [00:00<00:03, 348.59it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:  12%|█▏        | 176/1454 [00:00<00:04, 314.10it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:  14%|█▍        | 208/1454 [00:00<00:04, 302.36it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:  16%|█▋        | 239/1454 [00:00<00:04, 291.70it/s][12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:00] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:  19%|█▊        | 269/1454 [00:00<00:04, 289.40it/s][12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
Fingerprint Morgan_solv_abs:  21%|██        | 299/1454 [00:00<00:04, 279.82it/s][12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator
[12:51:01] DEPRECATION WARNING: please use MorganGenerator

עמוד Добавление 2048 битовых колонок...

🎉 === Обработка завершена! ===
📈 Итоговый DataFrame: 1454 строк, 8206 колонок
🧬 Создано fingerprint-колонок: 8192

📊 Детальная статистика нормализации:
  - L1: 1454/1454 (100.0%)
  - L2: 1454/1454 (100.0%)
  - L3: 1454/1454 (100.0%)
  - Solvent_SMILES: 1439/1454 (99.0%)

⚠️  Внимание: обнаружено 15 некорректных SMILES! Проверьте файл 'normalized_smiles_em_2.csv'

In [19]:
normalized_df

,index,lig_1_normalized,lig_2_normalized,lig_3_normalized,solvent_normalized
0,0,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccccn1,ClCCl
1,1,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,c1ccc(-c2ccccn2)nc1,ClCCl
2,2,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=C(O)c1ccnc(-c2cc(C(=O)O)ccn2)c1,CO
3,3,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,[c-]1cc(-c2nc3c4ccccc4c4ccccc4c3n2-c2ccccc2)cc...,O=S(=O)(O)c1ccc(P(c2ccc(S(=O)(=O)O)cc2)c2ccccc...,None
4,4,[c-]1ccccc1-c1ccccn1,[c-]1ccccc1-c1ccccn1,CCOP(=O)(OCC)c1ccnc(-c2cc(P(=O)(OCC)OCC)ccn2)c1,CO
...,...,...,...,...,...
1449,1449,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,CCCCn1c2ccccc2c2cc(-c3ccc4c(c3)-c3cc(-c5ccccn5...,O=C(O)c1ccccn1,ClCCl
1450,1450,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,Cc1cc(-c2ccccn2)Nn1,ClCCl
1451,1451,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2nccc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)Nn1,ClCCl
1452,1452,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,Cc1cc(-c2ccccn2)Nn1,ClCCl
1453,1453,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1c[c-]c(-c2ncnc3ccccc23)cc1,FC(F)(F)c1cc(-c2ccccn2)Nn1,ClCCl

In [20]:
sum(sum(np.array(result_df.loc[:, 'Morgan_1_0':'Morgan_solv_abs_2047'])))

134583